<?php
declare(strict_types=1);
require __DIR__.'/phpRegistrationHarness.php';
require __DIR__.'/../api/client_request_withdrawal.php';
loadFunctions(__DIR__.'/../api/index.php',['releaseBookingSlots','bookingHeldQuantity']);
$pdo->exec("ALTER TABLE bookings ADD COLUMN session_version INTEGER DEFAULT 0;
CREATE TABLE booking_sessions(id INTEGER PRIMARY KEY,organization_id INTEGER,booking_id INTEGER);
CREATE TABLE reschedule_requests(id INTEGER PRIMARY KEY,organization_id INTEGER,client_id INTEGER,booking_id INTEGER,proposed_date TEXT,proposed_start_time TEXT,proposed_end_time TEXT,status TEXT,decided_by INTEGER,decided_at TEXT);
CREATE TABLE client_studio_booking_requests(id INTEGER PRIMARY KEY,organization_id INTEGER,client_id INTEGER,package_status TEXT,deposit_amount INTEGER);
CREATE TABLE client_studio_booking_dates(id INTEGER PRIMARY KEY,organization_id INTEGER,request_id INTEGER,date TEXT,start_time TEXT,end_time TEXT,status TEXT,note TEXT,decided_by INTEGER,decided_at TEXT);
INSERT INTO clients(id,organization_id,name) VALUES(1,1,'Client One'),(2,1,'Client Two'),(3,2,'Other Org');
INSERT INTO users(id,organization_id,role,is_active) VALUES(1,1,'owner',1),(2,1,'admin',1),(3,1,'operations',1),(4,2,'owner',1),(5,1,'owner',0);
INSERT INTO client_packages(id,organization_id,client_id,billing_unit,purchased_quantity,purchased_minutes,held_quantity,held_minutes,consumed_quantity,consumed_minutes,total_price,paid_amount,status) VALUES(1,1,1,'hour',10,600,2,120,0,0,1800,900,'active');
INSERT INTO bookings(id,organization_id,client_id,client_package_id,date,start_time,end_time,status) VALUES(1,1,1,1,'2020-01-01','12:00:00','14:00:00','pending'),(2,1,1,1,'2020-01-02','12:00:00','14:00:00','cancel_requested'),(3,1,1,1,'2020-01-03','12:00:00','14:00:00','confirmed'),(4,1,2,NULL,'2020-01-04','12:00:00','14:00:00','pending'),(5,2,1,NULL,'2020-01-05','12:00:00','14:00:00','pending');
INSERT INTO booking_status_history(id,booking_id,from_status,to_status) VALUES(1,1,NULL,'pending'),(2,2,'confirmed','cancel_requested');
INSERT INTO booking_slots(id,organization_id,booking_id,resource_id,slot_date,slot_start) VALUES(1,1,1,1,'2020-01-01','12:00:00'),(2,1,2,1,'2020-01-02','12:00:00');
INSERT INTO package_usage_ledger(client_package_id,booking_id,movement_type,quantity,quantity_minutes,event_key) VALUES(1,1,'hold',2,120,'fixture');
INSERT INTO reschedule_requests VALUES(11,1,1,3,'2020-02-01','15:00','17:00','pending',NULL,NULL),(12,1,1,3,'2020-03-01','15:00','17:00','approved',NULL,NULL);
INSERT INTO client_studio_booking_requests VALUES(20,1,1,'pending',900);
INSERT INTO client_studio_booking_dates VALUES(21,1,20,'2020-02-02','12:00','14:00','pending',NULL,NULL,NULL),(22,1,20,'2020-02-03','12:00','14:00','approved',NULL,NULL,NULL);");
$client=['id'=>10,'role'=>'client','organization_id'=>1,'client_id'=>1];
$withdraw=fn(string $kind,int $id,int $version=0)=>withdrawClientAppointmentRequest($pdo,$client,$kind,$id,['request_version'=>$version]);
$status=fn(string $table,int $id)=>$pdo->query("SELECT status FROM $table WHERE id=$id")->fetchColumn();
check(count(clientPendingAppointmentRequests($pdo,$client)['items'])===4,'Only this client and organization pending requests are listed');
failure('request_not_found',fn()=>$withdraw('booking',4));failure('request_not_found',fn()=>$withdraw('booking',5));
failure('forbidden',fn()=>withdrawClientAppointmentRequest($pdo,['role'=>'owner'],'booking',1,[]));
failure('request_version_conflict',fn()=>$withdraw('booking',1,999));
check($status('bookings',1)==='pending','Stale request leaves booking intact');
$withdraw('reschedule',11);check($status('reschedule_requests',11)==='withdrawn','Reschedule can be withdrawn even past the notice period');
check($status('bookings',3)==='confirmed' && $pdo->query('SELECT date FROM bookings WHERE id=3')->fetchColumn()==='2020-01-03','Original booking date and status untouched');
failure('request_already_decided',fn()=>$withdraw('reschedule',11));failure('request_already_decided',fn()=>$withdraw('reschedule',12));
$withdraw('cancellation',2,2);check($status('bookings',2)==='confirmed','Withdrawing cancellation restores confirmed booking');
check((int)$pdo->query('SELECT COUNT(*) FROM booking_slots WHERE booking_id=2')->fetchColumn()===1,'Cancellation withdrawal preserves reserved slot');
failure('request_already_decided',fn()=>$withdraw('cancellation',2,2));
$withdraw('studio',21);check($status('client_studio_booking_dates',21)==='withdrawn','Studio appointment withdrawn');
check($pdo->query('SELECT package_status FROM client_studio_booking_requests WHERE id=20')->fetchColumn()==='pending' && (int)$pdo->query('SELECT deposit_amount FROM client_studio_booking_requests WHERE id=20')->fetchColumn()===900,'Package and deposit remain untouched');
failure('request_already_decided',fn()=>$withdraw('studio',22));
$withdraw('booking',1,1);check($status('bookings',1)==='cancelled','Pending new booking withdrawn without notice deadline');
check((int)$pdo->query('SELECT COUNT(*) FROM booking_slots WHERE booking_id=1')->fetchColumn()===0,'Slot released');
check((float)$pdo->query('SELECT held_quantity FROM client_packages WHERE id=1')->fetchColumn()===0.0,'Held hours released exactly once');
check((float)$pdo->query('SELECT consumed_quantity FROM client_packages WHERE id=1')->fetchColumn()===0.0,'No hours charged');
check((float)$pdo->query('SELECT paid_amount FROM client_packages WHERE id=1')->fetchColumn()===900.0,'No financial changes');
failure('request_already_decided',fn()=>$withdraw('booking',1,1));
check((int)$pdo->query("SELECT COUNT(*) FROM package_usage_ledger WHERE movement_type='release'")->fetchColumn()===1,'Repeated request cannot duplicate release');
failure('request_already_decided',fn()=>$withdraw('booking',3));
check(clientPendingAppointmentRequests($pdo,$client)['items']===[],'Withdrawn requests no longer await approval');
check(!$pdo->inTransaction(),'No open transaction after failure');
$pdo->exec("INSERT INTO reschedule_requests VALUES(30,1,1,3,'2030-02-01','15:00','17:00','pending',NULL,NULL); ALTER TABLE users RENAME TO saved_users");
try{$withdraw('reschedule',30);throw new RuntimeException('Expected notification failure');}catch(PDOException $e){check($status('reschedule_requests',30)==='pending','Failure to queue administration notification rolls back withdrawal');}
$pdo->exec('ALTER TABLE saved_users RENAME TO users');
echo "$checks request withdrawal checks passed\n";
