<?php
declare(strict_types=1);
require __DIR__.'/phpRegistrationHarness.php';
$payload=['registration_token'=>verifiedGrant($pdo,'first@example.test'),'name'=>'عميل تجريبي','phone'=>'01012345678','job'=>'مهندس','password'=>'TestPass123','password_confirmation'=>'TestPass123'];
$result=registrationComplete($pdo,[],$payload);
check($result['registered']===true && countRows($pdo,'clients')===1 && countRows($pdo,'users')===1,'Verified signup immediately creates one client and account');
check(countRows($pdo,'client_intake_requests')===0 && countRows($pdo,'client_packages')===0 && countRows($pdo,'bookings')===0,'Signup is independent and creates no admin request or booking');
$account=$pdo->query('SELECT * FROM users')->fetch();$client=$pdo->query('SELECT * FROM clients')->fetch();
check($account['role']==='client' && (int)$account['is_active']===1 && (int)$account['client_id']===(int)$client['id'],'Verified account is active and linked immediately');
check($client['registration_source']==='website','Website registration is persisted on client record');
check($client['email']==='first@example.test' && $client['job']==='مهندس' && $client['phone1']==='01012345678','Verified email and customer details are saved');
check(password_verify('TestPass123',$account['password_hash']) && $account['password_hash']!=='TestPass123','Credentials are hashed');
check(registrationComplete($pdo,[],$payload)===$result && countRows($pdo,'clients')===1,'Same verified submission is idempotent');
failure('registration_already_submitted',fn()=>registrationComplete($pdo,[],array_replace($payload,['name'=>'Changed name'])));
failure('password_confirmation_mismatch',fn()=>registrationComplete($pdo,[],array_replace($payload,['password_confirmation'=>'Other password'])));
failure('email_verification_required',fn()=>registrationComplete($pdo,[],array_replace($payload,['registration_token'=>str_repeat('a',64)])));
failure('registration_booking_separate',fn()=>registrationComplete($pdo,[],array_replace($payload,['service_id'=>101])));
failure('registration_identity_exists',fn()=>registrationComplete($pdo,[],array_replace($payload,['registration_token'=>verifiedGrant($pdo,'other@example.test')])));
$expired=array_replace($payload,['registration_token'=>verifiedGrant($pdo,'expired@example.test'),'phone'=>'01012345671']);
$pdo->exec("UPDATE registration_email_challenges SET grant_expires_at='2030-01-01 09:59:59' WHERE email='expired@example.test'");
failure('email_verification_expired',fn()=>registrationComplete($pdo,[],$expired));
$pdo->exec("INSERT INTO clients(organization_id,name,phone1,status) VALUES(1,'Manual client','01088888888','active')");
check($pdo->query('SELECT registration_source FROM clients ORDER BY id DESC LIMIT 1')->fetchColumn()==='manual','Manually created clients do not receive website label');
check(countRows($pdo,'users')===1,'Invalid registration creates no extra accounts');
$owner=['id'=>900,'organization_id'=>1,'role'=>'owner'];
check(route($pdo,$account,'/client/intake-requests','GET')['items']===[],'Automatic signup has no registration approval pending');
failure('forbidden',fn()=>route($pdo,$account,'/intake-requests','GET'));
check(registrationService($pdo,1,101)['deposit_amount']==='1700.00','Public deposit is 50 percent, independent of legacy service setting');

$service=registrationService($pdo,1,101);
$friday=registrationAvailability($pdo,1,$service,'2030-01-11',60);check(!$friday['available'] && !$friday['slots'],'Friday is closed');
$day=registrationAvailability($pdo,1,$service,'2030-01-10',60);check(count($day['slots'])===10 && $day['slots'][0]['start_time']==='12:00' && end($day['slots'])['end_time']==='22:00','Availability covers noon through 10 pm');
foreach($day['slots'] as $slot)check(array_keys($slot)===['resource_id','start_time','end_time'],'Availability has no private names');
$now=cairoNow();check(clientBookingWindowError('2030-01-11','12:00','13:00',$now)[0]==='client_booking_friday_closed','Friday cannot be submitted manually');
check(clientBookingWindowError('2030-01-10','11:59','13:00',$now)[0]==='client_booking_outside_hours','Before noon rejected');
check(clientBookingWindowError('2030-01-10','21:00','22:01',$now)[0]==='client_booking_outside_hours','After closing rejected');
check(clientBookingWindowError('2030-01-10','12:00','22:00',$now)===null,'Exact window is valid');
check(validateClientBookingTimeGrid('12:00','22:00',600)===600,'Client allows ten-hour maximum');
check(validBusinessBooking('00:00','24:00',30),'Admin all-day range preserved');
$booking=['date'=>'2030-01-03','start_time'=>'10:00','status'=>'confirmed'];check(!clientCancellationIsLate($booking,$now),'Exactly 48h may cancel');
check(clientCancellationIsLate(array_replace($booking,['start_time'=>'09:59']),$now),'Less than 48h remains confirmed');
check(!clientCancellationIsLate(array_replace($booking,['status'=>'pending','start_time'=>'09:59']),$now),'Unconfirmed request may be cancelled');
check(!registrationMailerReady([]),'Unconfigured email cannot claim ready');
check(registrationEmail(' TEST@Example.Test ')==='test@example.test','Email identity normalized');
$raw=$pdo->query('SELECT * FROM services')->fetch();check(registrationServiceSnapshot(array_replace($raw,['is_draft'=>1]))===null,'Draft service hidden');
check(registrationServiceSnapshot(array_replace($raw,['price'=>'0.00']))===null,'Unpriced services cannot advertise a paid online booking');
check(registrationServiceSnapshot(array_replace($raw,['billing_unit'=>'reel','total_reels'=>10]))===null,'Non-photography service hidden');
check(registrationServiceSnapshot(array_replace($raw,['billing_unit'=>'day']))['validity_days']===1,'Daily package validity is one shooting day');
$challenge=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO registration_email_challenges(organization_id,challenge_hash,email,code_hash,expires_at) VALUES(1,?,?,?,?)')->execute([hash('sha256',$challenge),'code@example.test',password_hash('123456',PASSWORD_DEFAULT),'2030-01-01 10:10:00']);
failure('verification_code_invalid',fn()=>route($pdo,null,'/registration/verify-email','POST',['challenge_id'=>$challenge,'code'=>'000000']));
check((int)$pdo->query("SELECT attempts FROM registration_email_challenges WHERE email='code@example.test'")->fetchColumn()===1,'Wrong OTP increments persisted attempts');
$verification=route($pdo,null,'/registration/verify-email','POST',['challenge_id'=>$challenge,'code'=>'123456']);
check(strlen($verification['registration_token'])===64,'Verified email yields opaque grant');
$row=$pdo->query("SELECT * FROM registration_email_challenges WHERE email='code@example.test'")->fetch();
check($row['code_hash']==='verified' && $row['grant_hash']===hash('sha256',$verification['registration_token']),'OTP destroyed and only hashed grant stored');
failure('verification_code_invalid',fn()=>route($pdo,null,'/registration/verify-email','POST',['challenge_id'=>$challenge,'code'=>'123456']));
$codeRow=['attempts'=>0,'expires_at'=>'2030-01-01 09:59:59'];check(registrationCodeError($codeRow,$now)==='verification_code_expired','Expired code denied');
check(registrationCodeError(array_replace($codeRow,['attempts'=>5]),$now)==='verification_attempts_exhausted','Five bad attempts lock code');
registrationRateLimit($pdo,'test','person',2,3600);registrationRateLimit($pdo,'test','person',2,3600);failure('registration_rate_limited',fn()=>registrationRateLimit($pdo,'test','person',2,3600));
registrationRateLimit($pdo,'cooldown','person',5,3600,60);failure('registration_rate_limited',fn()=>registrationRateLimit($pdo,'cooldown','person',5,3600,60));
foreach(['/intake-requests','/bookings','/data/users','/notifications','/attendance/summary','/events','/system-backups/export'] as $path)check(!registrationApplicantRouteAllowed($path,'GET'),'Applicant cannot read '.$path);
foreach(['/intake-requests/1/decision','/bookings/request','/auth/password','/data/clients'] as $path)check(!registrationApplicantRouteAllowed($path,'POST'),'Applicant cannot write '.$path);
check(registrationApplicantRouteAllowed('/client/intake-requests','GET') && registrationApplicantRouteAllowed('/auth/logout','POST'),'Applicant can track and logout');
check(registrationText("ملاحظة أولى\nملاحظة ثانية",1500,'note',false,true)!=='','Decision notes support line breaks');
check(clientBookingNoticeIsLate(['date'=>'2030-01-03','start_time'=>'09:59'],$now),'Reschedule notice is evaluated in Cairo');
check(!clientBookingNoticeIsLate(['date'=>'2030-01-03','start_time'=>'10:00'],$now),'Reschedule accepts exact 48-hour boundary');
check(registrationApplicantRouteAllowed('/data/app_config','GET') && !registrationApplicantRouteAllowed('/data/app_config','PATCH'),'Applicant may read public brand config only');
echo "PASS $checks automatic registration, source label, privacy, OTP and booking policy checks\n";
