<?php
declare(strict_types=1);
require __DIR__.'/phpRegistrationHarness.php';
$payload=['altcha'=>verifiedBotProof($pdo),'first_name'=>' أحمد ','second_name'=>'محمد','last_name'=>'عبد   الرحمن','phone'=>'01012345678','job'=>'مهندس','password'=>'TestPass123','password_confirmation'=>'TestPass123'];
foreach(['first_name','second_name','last_name'] as $field){
    foreach([null,'','   ',[],12,str_repeat('أ',51),"محمد\nأحمد"] as $invalid)failure('invalid_registration_details',fn()=>registrationComplete($pdo,[],array_replace($payload,[$field=>$invalid])));
    $missing=$payload;unset($missing[$field]);failure('invalid_registration_details',fn()=>registrationComplete($pdo,[],$missing));
}
$legacy=$payload;unset($legacy['first_name'],$legacy['second_name'],$legacy['last_name']);$legacy['name']='أحمد محمد علي';
failure('invalid_registration_details',fn()=>registrationComplete($pdo,[],$legacy));
check(countRows($pdo,'users')===0 && countRows($pdo,'clients')===0,'Invalid name cannot create any account through direct API');
$result=registrationComplete($pdo,[],$payload);
check($result['registered']===true && countRows($pdo,'clients')===1 && countRows($pdo,'users')===1,'Verified signup immediately creates one client and account');
check(countRows($pdo,'client_intake_requests')===0 && countRows($pdo,'client_packages')===0 && countRows($pdo,'bookings')===0,'Signup is independent and creates no admin request or booking');
$account=$pdo->query('SELECT * FROM users')->fetch();$client=$pdo->query('SELECT * FROM clients')->fetch();
check($account['role']==='client' && (int)$account['is_active']===1 && (int)$account['client_id']===(int)$client['id'],'Verified account is active and linked immediately');
check($client['name']==='أحمد محمد عبد الرحمن' && $account['full_name']===$client['name'],'All name parts persist consistently including compound family name');
check($client['registration_source']==='website','Website registration is persisted on client record');
check($client['email']===null && $account['email']===null && $client['job']==='مهندس' && $client['phone1']==='01012345678','Phone-only account has null email and saves customer details');
check(password_verify('TestPass123',$account['password_hash']) && $account['password_hash']!=='TestPass123','Credentials are hashed');
check(registrationComplete($pdo,[],$payload)===$result && countRows($pdo,'clients')===1,'Same verified submission is idempotent');
failure('registration_already_submitted',fn()=>registrationComplete($pdo,[],array_replace($payload,['first_name'=>'محمود'])));
failure('password_confirmation_mismatch',fn()=>registrationComplete($pdo,[],array_replace($payload,['password_confirmation'=>'Other password'])));
failure('bot_verification_required',fn()=>registrationComplete($pdo,[],array_replace($payload,['altcha'=>'','registration_token'=>str_repeat('a',64)])));
failure('registration_booking_separate',fn()=>registrationComplete($pdo,[],array_replace($payload,['service_id'=>101])));
failure('registration_identity_exists',fn()=>registrationComplete($pdo,[],array_replace($payload,['altcha'=>verifiedBotProof($pdo)])));
$expired=array_replace($payload,['altcha'=>verifiedBotProof($pdo),'phone'=>'01012345671']);
$expiredProof=registrationBotPayload($expired['altcha']);
$pdo->prepare('UPDATE registration_bot_challenges SET expires_at=? WHERE challenge_hash=?')->execute([cairoNow()->getTimestamp()-1,hash('sha256',$expiredProof->challenge->signature)]);
failure('bot_verification_expired',fn()=>registrationComplete($pdo,[],$expired));
$pdo->exec("INSERT INTO clients(organization_id,name,phone1,status) VALUES(1,'Manual client','01088888888','active')");
check($pdo->query('SELECT registration_source FROM clients ORDER BY id DESC LIMIT 1')->fetchColumn()==='manual','Manually created clients do not receive website label');
check(countRows($pdo,'users')===1,'Invalid registration creates no extra accounts');
$owner=['id'=>900,'organization_id'=>1,'role'=>'owner'];
check(route($pdo,$account,'/client/intake-requests','GET')['items']===[],'Automatic signup has no registration approval pending');
failure('forbidden',fn()=>route($pdo,$account,'/intake-requests','GET'));
check(registrationService($pdo,1,101)['deposit_amount']==='1700.00','Public deposit is 50 percent, independent of legacy service setting');

$service=registrationService($pdo,1,101);
$friday=registrationAvailability($pdo,1,$service,'2030-01-11',60);check(!$friday['available'] && !$friday['slots'],'Friday is closed');
$day=registrationAvailability($pdo,1,$service,'2030-01-10',60);check(count($day['slots'])===10 && $day['slots'][0]['start_time']==='12:00' && end($day['slots'])['end_time']==='22:00','Availability covers noon through 10 pm');
foreach($day['slots'] as $slot)check(array_keys($slot)===['resource_id','start_time','end_time'],'Availability has no private names');
$now=cairoNow();check(clientBookingWindowError('2030-01-11','12:00','13:00',$now)[0]==='client_booking_friday_closed','Friday cannot be submitted manually');
check(clientBookingWindowError('2030-01-10','11:59','13:00',$now)[0]==='client_booking_outside_hours','Before noon rejected');
check(clientBookingWindowError('2030-01-10','21:00','22:01',$now)[0]==='client_booking_outside_hours','After closing rejected');
check(clientBookingWindowError('2030-01-10','12:00','22:00',$now)===null,'Exact window is valid');
check(validateClientBookingTimeGrid('12:00','22:00',600)===600,'Client allows ten-hour maximum');
check(validBusinessBooking('00:00','24:00',30),'Admin all-day range preserved');
$booking=['date'=>'2030-01-03','start_time'=>'10:00','status'=>'confirmed'];check(!clientCancellationIsLate($booking,$now),'Exactly 48h may cancel');
check(clientCancellationIsLate(array_replace($booking,['start_time'=>'09:59']),$now),'Less than 48h remains confirmed');
check(!clientCancellationIsLate(array_replace($booking,['status'=>'pending','start_time'=>'09:59']),$now),'Unconfirmed request may be cancelled');
$raw=$pdo->query('SELECT * FROM services')->fetch();check(registrationServiceSnapshot(array_replace($raw,['is_draft'=>1]))===null,'Draft service hidden');
check(registrationServiceSnapshot(array_replace($raw,['price'=>'0.00']))===null,'Unpriced services cannot advertise a paid online booking');
check(registrationServiceSnapshot(array_replace($raw,['billing_unit'=>'reel','total_reels'=>10]))===null,'Non-photography service hidden');
check(registrationServiceSnapshot(array_replace($raw,['billing_unit'=>'day']))['validity_days']===1,'Daily package validity is one shooting day');
failure('email_verification_removed',fn()=>route($pdo,null,'/registration/email-code','POST',['email'=>'unused@example.test']));
failure('email_verification_removed',fn()=>route($pdo,null,'/registration/verify-email','POST',['code'=>'123456']));
check(countRows($pdo,'registration_email_challenges')===0,'Retired endpoints never issue email codes');
$next=array_replace($payload,['altcha'=>verifiedBotProof($pdo),'phone'=>'01012345679','email'=>'ignored@example.test','role'=>'owner']);
failure('bot_verification_failed',fn()=>registrationComplete($pdo,[],array_replace($next,['website'=>'spam.example'])));
$_COOKIE['mt_csrf']=str_repeat('d',64);
failure('bot_verification_failed',fn()=>registrationComplete($pdo,[],$next));
$_COOKIE['mt_csrf']=str_repeat('c',64);
$decoded=json_decode(base64_decode($next['altcha']),true);
$forged=$decoded;$forged['solution']['derivedKey']=str_repeat('0',64);
failure('bot_verification_failed',fn()=>registrationComplete($pdo,[],array_replace($next,['altcha'=>base64_encode(json_encode($forged))])));
$forged=$decoded;$forged['challenge']['parameters']['cost']=1;
failure('bot_verification_failed',fn()=>registrationComplete($pdo,[],array_replace($next,['altcha'=>base64_encode(json_encode($forged))])));
$forged=$decoded;$forged['challenge']['parameters']['expiresAt']+=100000;
failure('bot_verification_failed',fn()=>registrationComplete($pdo,[],array_replace($next,['altcha'=>base64_encode(json_encode($forged))])));
$forged=$decoded;$forged['challenge']['signature']=str_repeat('a',64);
failure('bot_verification_failed',fn()=>registrationComplete($pdo,[],array_replace($next,['altcha'=>base64_encode(json_encode($forged))])));
foreach([[],123,'not-base64',base64_encode('{}')] as $invalid)failure(is_string($invalid)?'bot_verification_failed':'bot_verification_required',fn()=>registrationComplete($pdo,[],array_replace($next,['altcha'=>$invalid])));
check(countRows($pdo,'users')===1,'Invalid or browser-mismatched proofs never create accounts');
$created=registrationComplete($pdo,[],$next);
$newUser=$pdo->query('SELECT * FROM users ORDER BY id DESC LIMIT 1')->fetch();
check($created['registered'] && $newUser['role']==='client' && $newUser['email']===null,'New phone-only accounts ignore supplied email and privileged role');
$manual=array_replace($payload,['altcha'=>verifiedBotProof($pdo),'phone'=>'+20 1088888888']);
failure('registration_identity_exists',fn()=>registrationComplete($pdo,[],$manual));
check($pdo->query("SELECT COUNT(*) FROM registration_bot_challenges WHERE consumed_at IS NOT NULL")->fetchColumn()===2,'Only committed account creations consume challenges');
$catalog=route($pdo,null,'/registration/catalog','GET');
check($catalog['bot_protection']==='altcha' && $catalog['email_verification_required']===false,'Public catalog no longer requires email service');
registrationRateLimit($pdo,'test','person',2,3600);registrationRateLimit($pdo,'test','person',2,3600);failure('registration_rate_limited',fn()=>registrationRateLimit($pdo,'test','person',2,3600));
registrationRateLimit($pdo,'cooldown','person',5,3600,60);failure('registration_rate_limited',fn()=>registrationRateLimit($pdo,'cooldown','person',5,3600,60));
foreach(['/intake-requests','/bookings','/data/users','/notifications','/attendance/summary','/events','/system-backups/export'] as $path)check(!registrationApplicantRouteAllowed($path,'GET'),'Applicant cannot read '.$path);
foreach(['/intake-requests/1/decision','/bookings/request','/auth/password','/data/clients'] as $path)check(!registrationApplicantRouteAllowed($path,'POST'),'Applicant cannot write '.$path);
check(registrationApplicantRouteAllowed('/client/intake-requests','GET') && registrationApplicantRouteAllowed('/auth/logout','POST'),'Applicant can track and logout');
check(registrationText("ملاحظة أولى\nملاحظة ثانية",1500,'note',false,true)!=='','Decision notes support line breaks');
check(clientBookingNoticeIsLate(['date'=>'2030-01-03','start_time'=>'09:59'],$now),'Reschedule notice is evaluated in Cairo');
check(!clientBookingNoticeIsLate(['date'=>'2030-01-03','start_time'=>'10:00'],$now),'Reschedule accepts exact 48-hour boundary');
check(registrationApplicantRouteAllowed('/data/app_config','GET') && !registrationApplicantRouteAllowed('/data/app_config','PATCH'),'Applicant may read public brand config only');
echo "PASS $checks automatic registration, source label, privacy, bot verification and booking policy checks\n";
