import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { CLIENT_ACTIONS } from '../src/lib/clientAnalytics.js';
import { createSiteAnalytics,analyticsPlatform,analyticsSource,analyticsDevice } from '../src/lib/siteAnalytics.js';
import { createMetaPixelTracker } from '../src/lib/metaPixel.js';
function fake(){let id=1;const entries=new Map(),sent=[],timers=[];const storage={getItem:k=>entries.get(k)||null,setItem:(k,v)=>entries.set(k,v)};const win={crypto:{randomUUID:()=>`00000000-0000-4000-8000-${String(id++).padStart(12,'0')}`},localStorage:storage,sessionStorage:storage,location:{search:'?tab=schedule&private=secret',hostname:'example.com'},navigator:{userAgent:'Android Mobile'},matchMedia:()=>({matches:false}),setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout:()=>{},addEventListener:()=>{},fetch:async(_url,options)=>{sent.push(JSON.parse(options.body));return {ok:true};}};const doc={referrer:'https://www.facebook.com/private?token=secret',addEventListener:()=>{}};return{win,doc,sent,entries,timers};}
test('collector and server event vocabularies match',()=>{const names=JSON.parse(readFileSync(new URL('../api/site_analytics_events.json',import.meta.url),'utf8'));assert.deepEqual(new Set(names),new Set(['PageView','ClientScreenViewed','AndroidAppDownload','ClientInteraction',...Object.values(CLIENT_ACTIONS).map(x=>x[1])]));});
test('tracking contains only approved dimensions, no search values or form metadata',async()=>{const f=fake();const tracker=createSiteAnalytics(f.win,f.doc);tracker.record('ClientInteraction','/dashboard',{control:'button',password:'secret',href:'private'});tracker.record('Unrecognized','/login');await tracker.flush();const event=f.sent[0].events[0];assert.equal(event.screen,'schedule');assert.equal(event.source,'facebook');assert.equal(event.platform,'web');assert.equal(event.device,'mobile');assert.ok(!JSON.stringify(f.sent).includes('secret'));assert.ok(!JSON.stringify(f.sent).includes('private'));assert.equal(f.sent[0].events.length,1);});
test('sessions persist then expire after inactivity, unique visitor remains',async()=>{const f=fake();const t=createSiteAnalytics(f.win,f.doc);t.record('PageView','/login');await t.flush();const first=f.sent[0].events[0];t.record('PageView','/register');await t.flush();assert.equal(f.sent[1].events[0].session,first.session);const state=JSON.parse(f.entries.get('mta_analytics_session_web'));state.last=Date.now()-31*60000;f.entries.set('mta_analytics_session_web',JSON.stringify(state));t.record('PageView','/login');await t.flush();assert.notEqual(f.sent[2].events[0].session,first.session);assert.equal(f.sent[2].events[0].visitor,first.visitor);});
test('mobile browser is distinct from Android customer app, app attribution survives navigation',()=>{const f=fake();assert.equal(analyticsPlatform(f.win,f.doc),'web');f.win.location.search='?source=android-app';assert.equal(analyticsPlatform(f.win,f.doc),'android_app');f.win.location.search='';assert.equal(analyticsPlatform(f.win,f.doc),'android_app');assert.equal(analyticsSource(f.win.location,'','android_app'),'app');assert.equal(analyticsDevice('iPad Tablet'),'tablet');});
test('failed transport retries same event IDs and batch stays bounded',async()=>{const f=fake();let fail=true;f.win.fetch=async(_url,options)=>{f.sent.push(JSON.parse(options.body));if(fail)throw Error('offline');return{ok:true};};const t=createSiteAnalytics(f.win,f.doc);t.record('PageView','/login');await t.flush();fail=false;await t.flush();assert.equal(f.sent[0].events[0].id,f.sent[1].events[0].id);assert.ok(f.sent.every(x=>x.events.length<=20));});
test('first party events survive broken or blocked Meta and are deduplicated on rerender',()=>{const events=[];const tracker=createMetaPixelTracker({fbq:()=>{throw Error('blocked');}},{querySelector:()=>true},(...args)=>events.push(args));tracker.page('/login');tracker.page('/login');tracker.action('/login',null,'login');tracker.page('/p-secret/login','owner');assert.deepEqual(events.map(x=>x[0]),['PageView','ClientLogin']);});
test('queued events survive navigation and keep the same ID for server deduplication',async()=>{const f=fake();const first=createSiteAnalytics(f.win,f.doc);first.record('CompleteRegistration','/register');const stored=JSON.parse(f.entries.get('mta_analytics_pending'));assert.equal(stored.length,1);const next=createSiteAnalytics(f.win,f.doc);await next.flush();assert.equal(f.sent[0].events[0].id,stored[0].event.id);assert.deepEqual(JSON.parse(f.entries.get('mta_analytics_pending')),[]);});
