import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Check, Clapperboard, CloudUpload, Film, History, MapPin, Plus, RefreshCw, Save, Search, Trash2, X } from 'lucide-react';
import { dataClient } from '../dataClient';
import useChangeSync from '../hooks/useChangeSync';
import useModalDialog from '../hooks/useModalDialog';
import { useData } from '../store/DataContext';
import { formatBookingDate, formatTime12 } from '../lib/businessFormat';
import { ACTIVE_POST_PRODUCTION_STATUSES, POST_PRODUCTION_STATUS, postProductionDuration, postProductionMeta, postProductionSessionLabel } from '../lib/postProduction';
import './ERPPostProduction.css';

const emptyLink = () => ({ title: '', link_kind: 'folder', url: '', is_active: 1 });
const tomorrow = () => { const date = new Date(); date.setDate(date.getDate() + 1); return date.toISOString().slice(0, 10); };
const defaultExpiry = () => { const date = new Date(); date.setDate(date.getDate() + 7); date.setHours(20, 0, 0, 0); return date.toISOString().slice(0, 16); };
const toLocalInput = value => { const date = new Date(value); if (Number.isNaN(date.getTime())) return defaultExpiry(); const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return local.toISOString().slice(0, 16); };

export default function ERPPostProduction() {
  const { currentUser } = useData(); const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [statusFilter, setStatusFilter] = useState('active'); const [clientFilter, setClientFilter] = useState('all'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(''); const [dialogError, setDialogError] = useState(''); const [pendingStatus, setPendingStatus] = useState(''); const [links, setLinks] = useState([]);
  const [pickup, setPickup] = useState({ revision: 0, expires_at: null, windows: [] }); const [pickupExpiry, setPickupExpiry] = useState(defaultExpiry); const [pickupWindows, setPickupWindows] = useState([]); const [pickupError, setPickupError] = useState(''); const [pickupBusy, setPickupBusy] = useState(false); const [pickupLoading, setPickupLoading] = useState(false); const pickupRequestRef = useRef(0); const dialogTriggerRef = useRef(null);
  const selectedId = selected?.id; const selectedVersion = selected?.version;
  const resetPickupEditor = useCallback(() => { pickupRequestRef.current += 1; setPickup({ revision: 0, expires_at: null, windows: [] }); setPickupExpiry(defaultExpiry()); setPickupWindows([]); setPickupError(''); setPickupBusy(false); setPickupLoading(false); }, []);
  const closeDialog = useCallback(() => { setSelected(null); setPendingStatus(''); setDialogError(''); resetPickupEditor(); }, [resetPickupEditor]); const dialogRef = useModalDialog(Boolean(selected), closeDialog, { returnFocusRef: dialogTriggerRef });

  const loadJobs = useCallback(async (quiet = false) => {
    if (!quiet) setLoading(true); setError(''); const { data, error: requestError } = await dataClient.request('/post-production?status=all', { method: 'GET' });
    if (requestError) setError(requestError.message || 'تعذر تحميل مركز المونتاج.');
    else { const items = Array.isArray(data?.items) ? data.items : []; setJobs(items); setSelected(current => current ? items.find(item => Number(item.id) === Number(current.id)) || null : null); }
    if (!quiet) setLoading(false);
  }, []);
  const loadPickup = useCallback(async jobId => {
    if (!Number(jobId)) return; const requestId = pickupRequestRef.current + 1; pickupRequestRef.current = requestId; setPickupLoading(true); setPickupError(''); setPickup({ revision: 0, expires_at: null, windows: [] }); setPickupExpiry(defaultExpiry()); setPickupWindows([]);
    const { data, error: requestError } = await dataClient.request(`/post-production/${Number(jobId)}/pickup-availability`, { method: 'GET' });
    if (requestId !== pickupRequestRef.current) return;
    setPickupLoading(false); if (requestError) { setPickupError(requestError.message || 'تعذر تحميل فترة استلام هذه المهمة.'); return; }
    const value = data || { revision: 0, expires_at: null, windows: [] }; setPickup(value); setPickupExpiry(value.expires_at ? toLocalInput(value.expires_at) : defaultExpiry()); setPickupWindows(Array.isArray(value.windows) ? value.windows : []);
  }, []);
  // Remote state is intentionally hydrated when the page mounts.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { loadJobs(); }, [loadJobs]);
  // Keep the editor in sync after an optimistic-version refresh.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (selected) setLinks((selected.delivery_links || []).map(link => ({ title: link.title, link_kind: link.link_kind, url: link.url, is_active: Number(link.is_active) }))); }, [selected, selectedId, selectedVersion]);
  useChangeSync(useCallback(topics => { if (topics.includes('post_production')) loadJobs(true); }, [loadJobs]), !currentUser?.is_local_preview);

  const clients = useMemo(() => [...new Map(jobs.map(job => [Number(job.client_id), job.client_name])).entries()].sort((a, b) => String(a[1]).localeCompare(String(b[1]), 'ar')), [jobs]);
  const filtered = useMemo(() => jobs.filter(job => {
    if (statusFilter === 'active' && !ACTIVE_POST_PRODUCTION_STATUSES.includes(job.status)) return false; if (statusFilter !== 'all' && statusFilter !== 'active' && job.status !== statusFilter) return false;
    if (clientFilter !== 'all' && Number(job.client_id) !== Number(clientFilter)) return false; const needle = search.trim().toLocaleLowerCase('ar'); return !needle || `${job.client_name} ${job.service} ${job.package_name || ''} ${job.booking_id}`.toLocaleLowerCase('ar').includes(needle);
  }), [clientFilter, jobs, search, statusFilter]);
  const kpis = useMemo(() => ({ editing: jobs.filter(job => ['editing_in_progress', 'editing_completed'].includes(job.status)).length, upload: jobs.filter(job => ['uploading', 'upload_completed'].includes(job.status)).length, pickup: jobs.filter(job => job.status === 'ready_for_pickup').length, delivered: jobs.filter(job => job.status === 'delivered').length }), [jobs]);
  const announce = message => { setNotice(message); window.setTimeout(() => setNotice(''), 4500); };
  const openJob = (job, event) => { dialogTriggerRef.current = event.currentTarget; setSelected(job); setDialogError(''); setPendingStatus(''); loadPickup(job.id); };

  const updateStatus = async () => {
    if (!selected || !pendingStatus) return; setBusy('status'); setDialogError(''); const { error: requestError } = await dataClient.request(`/post-production/${selected.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: pendingStatus, expected_version: Number(selected.version) }) }); setBusy('');
    if (requestError) { setDialogError(requestError.message || 'تعذر تغيير الحالة.'); if (requestError.status === 409 || requestError.code === 'post_production_version_conflict') await loadJobs(true); return; }
    setPendingStatus(''); announce(`تم تغيير الحالة إلى: ${postProductionMeta(pendingStatus).label}`); await loadJobs(true);
  };
  const saveLinks = async event => {
    event.preventDefault(); if (!selected) return; setBusy('links'); setDialogError(''); const { error: requestError } = await dataClient.request(`/post-production/${selected.id}/delivery-links`, { method: 'PUT', body: JSON.stringify({ expected_version: Number(selected.version), links }) }); setBusy('');
    if (requestError) { setDialogError(requestError.message || 'تعذر حفظ روابط التسليم.'); if (requestError.status === 409 || requestError.code === 'post_production_version_conflict') await loadJobs(true); return; }
    announce('تم حفظ روابط Google Drive بأمان.'); await loadJobs(true);
  };
  const publishLegacy = async () => {
    if (!selected) return; setBusy('publish'); setDialogError(''); const { error: requestError } = await dataClient.request(`/post-production/${selected.id}/publish`, { method: 'POST', body: JSON.stringify({ status: selected.status, expected_version: Number(selected.version) }) }); setBusy('');
    if (requestError) return setDialogError(requestError.message || 'تعذر نشر الجلسة القديمة.'); announce('تمت مراجعة الجلسة وإظهارها للعميل.'); await loadJobs(true);
  };
  const savePickup = async event => {
    event.preventDefault(); if (!selected) return; setPickupBusy(true); setPickupError(''); const { data, error: requestError } = await dataClient.request(`/post-production/${selected.id}/pickup-availability`, { method: 'PUT', body: JSON.stringify({ expected_revision: Number(pickup.revision || 0), expires_at: new Date(pickupExpiry).toISOString(), windows: pickupWindows }) }); setPickupBusy(false);
    if (requestError) { setPickupError(requestError.message || 'تعذر حفظ فترة استلام هذه المهمة.'); if (requestError.status === 409 || requestError.code === 'pickup_revision_conflict') await loadPickup(selected.id); return; }
    setPickup(data); setPickupExpiry(data.expires_at ? toLocalInput(data.expires_at) : pickupExpiry); setPickupWindows(Array.isArray(data.windows) ? data.windows : []); announce('تم تحديث فترة استلام هذه المهمة.');
  };

  return <main className="post-production-center" dir="rtl">
    <header className="post-production-head"><div><span>الخدمات والعمل</span><h1>المونتاج والتسليم</h1><p>تابع كل جلسة مكتملة من المونتاج حتى رفع الفيديو أو استلامه من الشركة.</p></div><button type="button" onClick={() => loadJobs()} aria-label="تحديث مركز المونتاج"><RefreshCw className={loading ? 'is-spinning' : ''} /></button></header>
    {notice && <div className="post-production-notice" role="status"><Check /> {notice}</div>}
    <section className="post-production-kpis" aria-label="ملخص حالات المونتاج">{[['editing', Clapperboard, 'قيد المونتاج'], ['upload', CloudUpload, 'الرفع والجاهز رقميًا'], ['pickup', MapPin, 'جاهز للاستلام'], ['delivered', Check, 'تم التسليم']].map(([key, Icon, label]) => <article key={key}><Icon /><span>{label}</span><strong>{error ? '—' : kpis[key]}</strong></article>)}</section>
    <section className="post-production-toolbar" aria-label="تصفية جلسات المونتاج"><label className="post-production-search"><Search /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="ابحث بالعميل أو الخدمة أو رقم الحجز" /></label><label><span>الحالة</span><select value={statusFilter} onChange={event => setStatusFilter(event.target.value)}><option value="active">العمل النشط</option><option value="all">كل الحالات</option>{Object.entries(POST_PRODUCTION_STATUS).map(([value, meta]) => <option value={value} key={value}>{meta.label}</option>)}</select></label><label><span>العميل</span><select value={clientFilter} onChange={event => setClientFilter(event.target.value)}><option value="all">كل العملاء</option>{clients.map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></label></section>
    {loading && <CenterState icon={RefreshCw} spinning title="جارٍ تجهيز مركز المونتاج" text="نجمع الجلسات والتاريخ وروابط التسليم…" />}
    {!loading && error && <CenterState icon={Film} title="تعذر تحميل مركز المونتاج" text={error} action="إعادة المحاولة" onAction={() => loadJobs()} error />}
    {!loading && !error && !filtered.length && <CenterState icon={Clapperboard} title="لا توجد جلسات تطابق الفلتر" text="غيّر الحالة أو العميل، أو انتظر اكتمال جلسة تصوير جديدة." />}
    {!loading && !error && filtered.length > 0 && <section className="post-production-list" aria-label="جلسات المونتاج">{filtered.map(job => { const meta = postProductionMeta(job.status); return <article className={`post-production-record tone-${meta.tone}`} key={job.id}><div className="post-production-record__identity"><i><Clapperboard /></i><div><span>جلسة #{job.booking_id}</span><h2>{job.client_name}</h2><p>{postProductionSessionLabel(job)}</p></div></div><dl><div><dt>التاريخ والوقت</dt><dd>{formatBookingDate(job.session_date)} · {formatTime12(job.start_time, '--:--')}</dd></div><div><dt>المدة المصورة</dt><dd>{postProductionDuration(job.actual_seconds)}</dd></div><div><dt>آخر تغيير</dt><dd>{job.status_changed_at ? new Intl.DateTimeFormat('ar-EG', { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' }).format(new Date(job.status_changed_at)) : '—'}</dd></div><div><dt>روابط التسليم</dt><dd>{job.delivery_link_count || 0}</dd></div></dl><div className="post-production-record__state"><b>{meta.label}</b>{Number(job.needs_review) === 1 ? <span className="is-review">يحتاج مراجعة قبل الظهور للعميل</span> : <span>{Number(job.is_client_visible) === 1 ? 'ظاهر للعميل' : 'غير ظاهر للعميل'}</span>}</div><button type="button" onClick={event => openJob(job, event)}>التفاصيل والتحكم</button></article>; })}</section>}

    {selected && <div className="post-production-modal" onMouseDown={event => { if (event.target === event.currentTarget) closeDialog(); }}><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="post-production-dialog-title" className="post-production-dialog"><header><div><span>جلسة #{selected.booking_id}</span><h2 id="post-production-dialog-title">{selected.client_name} — {postProductionSessionLabel(selected)}</h2><p>{formatBookingDate(selected.session_date)} · {postProductionDuration(selected.actual_seconds)}</p></div><button type="button" data-dialog-initial onClick={closeDialog} aria-label="إغلاق"><X /></button></header>{dialogError && <div className="post-production-dialog__error" role="alert">{dialogError}</div>}
      <section className="post-production-dialog__section"><div className="post-production-dialog__title"><div><span>الحالة الحالية</span><h3>{postProductionMeta(selected.status).label}</h3></div><b>نسخة {selected.version}</b></div><OwnerProgressRail status={selected.status} />{Number(selected.needs_review) === 1 ? <div className="post-production-legacy"><p>هذه جلسة قديمة أُضيفت للمراجعة ولم تظهر للعميل.</p><button type="button" disabled={busy === 'publish' || !['owner', 'admin'].includes(currentUser?.role)} onClick={publishLegacy}>{busy === 'publish' ? 'جارٍ النشر…' : 'اعتماد الحالة وإظهارها للعميل'}</button></div> : selected.valid_next_statuses?.length ? <div className="post-production-next"><p>اختر الخطوة التالية فقط. سيصل للعميل إشعار يوضح الحالة الجديدة.</p><div>{selected.valid_next_statuses.map(status => <button key={status} className={pendingStatus === status ? 'active' : ''} onClick={() => setPendingStatus(status)}>{postProductionMeta(status).label}</button>)}</div>{pendingStatus && <div className="post-production-confirm"><p>تأكيد النقل إلى «{postProductionMeta(pendingStatus).label}» وإرسال إشعار للعميل؟</p><button type="button" disabled={busy === 'status'} onClick={updateStatus}>{busy === 'status' ? 'جارٍ الحفظ…' : 'تأكيد الحالة'}</button><button type="button" onClick={() => setPendingStatus('')}>رجوع</button></div>}</div> : <p className="post-production-complete"><Check /> اكتمل مسار هذه الجلسة وتم تسليمها.</p>}</section>
      <form className="post-production-dialog__section" onSubmit={saveLinks}><div className="post-production-dialog__title"><div><span>التسليم الرقمي</span><h3>روابط Google Drive</h3></div><button type="button" onClick={() => setLinks(current => [...current, emptyLink()])}><Plus /> إضافة رابط</button></div><p className="post-production-help">يُسمح بروابط HTTPS من Google Drive فقط. تظهر للعميل بعد اكتمال الرفع.</p><div className="post-production-links">{links.map((link, index) => <article key={index}><label>اسم الرابط<input required value={link.title} onChange={event => setLinks(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} /></label><label>النوع<select value={link.link_kind} onChange={event => setLinks(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, link_kind: event.target.value } : item))}><option value="folder">فولدر</option><option value="video">فيديو</option></select></label><label className="post-production-link-url">الرابط<input required type="url" inputMode="url" dir="ltr" placeholder="https://drive.google.com/..." value={link.url} onChange={event => setLinks(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, url: event.target.value } : item))} /></label><label className="post-production-link-active"><input type="checkbox" checked={Number(link.is_active) === 1} onChange={event => setLinks(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, is_active: event.target.checked ? 1 : 0 } : item))} /> نشط</label><button type="button" className="post-production-link-remove" aria-label={`حذف الرابط ${index + 1}`} onClick={() => setLinks(current => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 /></button></article>)}</div><button className="post-production-save" disabled={busy === 'links'}><Save /> {busy === 'links' ? 'جارٍ الحفظ…' : 'حفظ مجموعة الروابط'}</button></form>
      <PickupEditor jobId={selected.id} pickup={pickup} expiry={pickupExpiry} setExpiry={setPickupExpiry} windows={pickupWindows} setWindows={setPickupWindows} error={pickupError} busy={pickupBusy} loading={pickupLoading} onSubmit={savePickup} onRefresh={() => loadPickup(selected.id)} />
      <section className="post-production-dialog__section"><div className="post-production-dialog__title"><div><span>سجل لا يتغير</span><h3>تاريخ الحالات</h3></div><History /></div><ol className="post-production-history">{(selected.history || []).map(item => <li key={item.id || item.version}><i /><div><strong>{postProductionMeta(item.to_status).label}</strong><time>{new Intl.DateTimeFormat('ar-EG', { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' }).format(new Date(item.changed_at))}</time></div><b>v{item.version}</b></li>)}</ol></section>
    </section></div>}
  </main>;
}

function OwnerProgressRail({ status }) {
  const index = status === 'editing_in_progress' ? 0 : ['editing_completed', 'uploading'].includes(status) ? 1 : ['upload_completed', 'ready_for_pickup'].includes(status) ? 2 : 3;
  const steps = [[Clapperboard, 'المونتاج'], [CloudUpload, 'التجهيز والرفع'], [MapPin, 'جاهز'], [Check, 'التسليم']];
  return <ol className="owner-production-rail" aria-label={`تقدم الجلسة: ${postProductionMeta(status).label}`}>{steps.map(([Icon, label], step) => <li key={label} className={step < index ? 'is-done' : step === index ? 'is-current' : step === index + 1 ? 'is-next' : ''}><i><Icon /></i><span>{label}<small>{step === index ? 'الحالي' : step === index + 1 ? 'التالي' : step < index ? 'اكتمل' : ''}</small></span></li>)}</ol>;
}

function CenterState({ icon: Icon, title, text, action, onAction, spinning = false, error = false }) { return <div className={`post-production-state${error ? ' is-error' : ''}`}><Icon className={spinning ? 'is-spinning' : ''} /><strong>{title}</strong><p>{text}</p>{action && <button type="button" onClick={onAction}>{action}</button>}</div>; }

function PickupEditor({ jobId, pickup, expiry, setExpiry, windows, setWindows, error, busy, loading, onSubmit, onRefresh }) {
  const addWindow = () => setWindows(current => [...current, { date: tomorrow(), start_time: '14:00', end_time: '18:00', label: 'متاحون في الشركة' }]);
  return <section className="post-production-dialog__section pickup-editor" aria-labelledby={`pickup-editor-title-${jobId}`}><header><div><span><MapPin /> الاستلام من مقر الشركة</span><h3 id={`pickup-editor-title-${jobId}`}>فترة استلام هذه المهمة</h3><p>تخص جلسة #{jobId} فقط، وهي مؤقتة ولا تنشئ حجزًا في جدول المواعيد.</p></div><button type="button" onClick={onRefresh} aria-label="تحديث فترة استلام المهمة"><RefreshCw className={loading ? 'is-spinning' : ''} /></button></header>{error && <div className="pickup-editor__error" role="alert">{error}</div>}{loading ? <div className="pickup-editor__loading" role="status"><RefreshCw className="is-spinning" /> جارٍ تحميل فترة هذه المهمة…</div> : <form onSubmit={onSubmit}><label className="pickup-expiry">صلاحية الإعلان حتى<input required type="datetime-local" value={expiry} onChange={event => setExpiry(event.target.value)} /></label><div className="pickup-window-list">{windows.map((window, index) => <article key={index}><label>التاريخ<input required type="date" value={window.date} onChange={event => setWindows(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, date: event.target.value } : item))} /></label><label>من<input required type="time" value={window.start_time} onChange={event => setWindows(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, start_time: event.target.value } : item))} /></label><label>إلى<input required type="time" value={window.end_time} onChange={event => setWindows(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, end_time: event.target.value } : item))} /></label><label className="pickup-window-label">الوصف<input required value={window.label} onChange={event => setWindows(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item))} /></label><button type="button" aria-label={`حذف الفترة ${index + 1}`} onClick={() => setWindows(current => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 /></button></article>)}</div><div className="pickup-editor__actions"><button type="button" onClick={addWindow} disabled={windows.length >= 20}><Plus /> إضافة فترة</button><button type="submit" disabled={busy}><Save /> {busy ? 'جارٍ الحفظ…' : `حفظ للمهمة — النسخة ${Number(pickup.revision || 0)}`}</button></div></form>}</section>;
}
