import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, startOfMonth, startOfWeek, subMonths } from 'date-fns';
import { ar } from 'date-fns/locale';
import { ArrowDown, ArrowUp, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, CircleDollarSign, ClipboardCheck, Clock3, Filter, FolderKanban, LayoutList, Plus, RefreshCw, Save, Search, Settings2, Sparkles, WalletCards, X } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { useData } from '../store/DataContext';
import './ERPProjects.css';
import { safeUiError } from '../lib/uiError';
import { formatTime12 } from '../lib/businessFormat';
import './ERPProjectsLifecycle.css';
import ERPPageHero from './ERPPageHero';
import CustomServiceCatalog from './CustomServiceCatalog';
import { serviceMeta } from './customServices';
import CustomServiceForm from './CustomServiceForm';
import './ERPProjectsCustomServices.css';
import OwnerRecordActions from './OwnerRecordActions';

const PROJECT_STATUS={planning:['تخطيط','planning'],active:['نشط','active'],on_hold:['متوقف مؤقتًا','hold'],completed:['مكتمل','done'],cancelled:['ملغي','muted']};
const TASK_STATUS={todo:'قيد الانتظار',in_progress:'قيد التنفيذ',review:'للمراجعة',done:'مكتملة',blocked:'متوقفة'};
const CONTENT_STATUS={idea:['فكرة','muted'],draft:['مسودة','planning'],in_review:['للمراجعة','review'],approved:['معتمد','approved'],scheduled:['مجدول','scheduled'],published:['منشور','done'],rejected:['مرفوض','danger']};
const PLATFORM={instagram:'Instagram',facebook:'Facebook',tiktok:'TikTok',youtube:'YouTube',linkedin:'LinkedIn',website:'Website'};
const CONTENT_TYPE={post:'منشور',reel:'ريل',story:'ستوري',video:'فيديو',ad:'إعلان',article:'مقال'};
const PRIORITY={low:'منخفضة',normal:'عادية',high:'عالية',urgent:'عاجلة'};
const MILESTONE_STATUS={pending:'قادمة',in_progress:'قيد التنفيذ',review:'للمراجعة',completed:'مكتملة',blocked:'متوقفة'};
const UNIT_LABEL={hour:'ساعة تصوير',episode:'حلقة',reel:'ريل',project:'مشروع',month:'شهر',event:'فعالية',video:'فيديو',platform:'منصة'};
const blankTask={title:'',description:'',priority:'normal',assigned_to:'',due_at:''};
const blankContent={title:'',content_type:'post',platform:'instagram',status:'idea',scheduled_at:'',caption:''};
const dateText=value=>value?format(new Date(`${String(value).slice(0,10)}T12:00:00`),'d MMMM yyyy',{locale:ar}):'غير محدد';
const dateTimeText=value=>value?format(new Date(value.replace(' ','T')),'d MMM، h:mm a',{locale:ar}):'غير محدد';
const apiDateTime=value=>value?`${value.replace('T',' ')}:00`:null;

export default function ERPProjects(){
  const{currentUser}=useData();
  const canManage=['owner','admin','operations'].includes(currentUser?.role);
  const isOwner=currentUser?.role==='owner';
  const[projects,setProjects]=useState([]),[tasks,setTasks]=useState([]),[content,setContent]=useState([]),[clients,setClients]=useState([]),[users,setUsers]=useState([]);
  const[projectItems,setProjectItems]=useState([]),[milestones,setMilestones]=useState([]),[bookings,setBookings]=useState([]),[invoices,setInvoices]=useState([]);
  const[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('projects'),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[serviceFilter,setServiceFilter]=useState('all'),[initialService,setInitialService]=useState('reels');
  const[month,setMonth]=useState(startOfMonth(new Date())),[selectedDay,setSelectedDay]=useState(new Date()),[taskForm,setTaskForm]=useState(blankTask),[contentForm,setContentForm]=useState(blankContent);
  const[modal,setModal]=useState(null),[selectedProject,setSelectedProject]=useState(null),[busy,setBusy]=useState('');
  const[editingChild,setEditingChild]=useState(null);
  const dialogRef=useRef(null),triggerRef=useRef(null);
  const fetchData=useCallback(async()=>{
    setLoading(true);setError('');
    const calls=[supabase.from('projects').select('*').order('updated_at',{ascending:false}),supabase.from('project_tasks').select('*').order('due_at',{ascending:true}),supabase.from('content_items').select('*').order('scheduled_at',{ascending:true}),supabase.from('clients').select('id,name,company_name,color').order('name')];
    const results=await Promise.all(calls);const failed=results.find(result=>result.error);
    if(failed?.error)setError(safeUiError(failed.error,'تعذر تحميل مساحة المشروعات الآن.'));else{setProjects(results[0].data||[]);setTasks(results[1].data||[]);setContent(results[2].data||[]);setClients(results[3].data||[])}
    const extras=await Promise.all([supabase.from('project_items').select('*').order('sort_order',{ascending:true}),supabase.from('project_milestones').select('*').order('sort_order',{ascending:true}),supabase.from('bookings').select('*').order('date',{ascending:true}),supabase.from('invoices').select('*').order('issued_at',{ascending:false})]);
    if(!extras[0].error)setProjectItems(extras[0].data||[]);if(!extras[1].error)setMilestones(extras[1].data||[]);if(!extras[2].error)setBookings(extras[2].data||[]);if(!extras[3].error)setInvoices(extras[3].data||[]);
    if(canManage){const result=await supabase.request('/users/assignees',{method:'GET'});if(!result.error)setUsers((result.data||[]).filter(user=>user.is_active!==false&&user.role!=='client'));else setUsers(currentUser?[currentUser]:[]);}else setUsers(currentUser?[currentUser]:[]);
    setLoading(false);
  },[canManage,currentUser]);
  // Remote workspace data must be synchronized when the authenticated identity changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{fetchData()},[fetchData]);
  const openModal=(name,event,project=null)=>{if(!modal)triggerRef.current=event?.currentTarget||document.activeElement;if(project)setSelectedProject(project);setModal(name)};
  const closeModal=useCallback(()=>{setModal(null);setEditingChild(null);setTaskForm(blankTask);setContentForm(blankContent)},[]);
  const modalOpen=Boolean(modal);
  useEffect(()=>{if(!modalOpen)return;const list=()=>Array.from(dialogRef.current?.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')||[]);const key=event=>{if(event.key==='Escape')closeModal();if(event.key==='Tab'){const items=list();if(!items.length)return;const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow='';requestAnimationFrame(()=>triggerRef.current?.focus())}},[modalOpen,closeModal]);
  useEffect(()=>{if(modal)requestAnimationFrame(()=>dialogRef.current?.querySelector('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')?.focus())},[modal]);
  const clientName=id=>clients.find(item=>Number(item.id)===Number(id))?.name||'عميل';
  const projectName=id=>projects.find(item=>Number(item.id)===Number(id))?.name||'مشروع';
  const userName=id=>users.find(item=>Number(item.id)===Number(id))?.full_name||(Number(id)===Number(currentUser?.id)?currentUser?.full_name:'غير مسند');
  const projectTasks=id=>tasks.filter(item=>Number(item.project_id)===Number(id)),projectContent=id=>content.filter(item=>Number(item.project_id)===Number(id));
  const projectPaid=project=>Number(project.paid_amount??invoices.find(invoice=>Number(invoice.id)===Number(project.invoice_id))?.paid_amount??0);
  const metrics={active:projects.filter(item=>item.status==='active').length,contracted:projects.reduce((sum,item)=>sum+Number(item.agreed_price||0),0),outstanding:projects.reduce((sum,item)=>sum+Math.max(0,Number(item.agreed_price||0)-projectPaid(item)),0),review:milestones.filter(item=>item.status==='review').length+tasks.filter(item=>item.status==='review').length+content.filter(item=>item.status==='in_review').length};
  const filteredProjects=projects.filter(project=>(filter==='all'||project.status===filter)&&(serviceFilter==='all'||project.service_type===serviceFilter)&&`${project.name} ${clientName(project.client_id)} ${serviceMeta(project.service_type).label}`.toLowerCase().includes(search.toLowerCase()));
  const filteredTasks=tasks.filter(task=>(filter==='all'||task.status===filter)&&`${task.title} ${projectName(task.project_id)}`.toLowerCase().includes(search.toLowerCase()));
  const calendarDays=useMemo(()=>eachDayOfInterval({start:startOfWeek(startOfMonth(month),{weekStartsOn:6}),end:endOfWeek(endOfMonth(month),{weekStartsOn:6})}),[month]);
  const dayContent=day=>content.filter(item=>item.scheduled_at&&isSameDay(new Date(item.scheduled_at.replace(' ','T')),day));
  const selectedContent=dayContent(selectedDay);
  const saveProject=async payload=>{setBusy('project');setError('');const{data,error:requestError}=await supabase.request('/projects/custom-service',{method:'POST',body:JSON.stringify(payload)});setBusy('');if(requestError)return setError(requestError.message||'تعذر إنشاء الخدمة المخصصة.');setNotice(data?.booking_id?'تم إنشاء المشروع وإضافة موعده بانتظار التأكيد.':'تم إنشاء الخدمة المخصصة وربط مسار التنفيذ بنجاح.');['erpProjectsUpdated','erpBookingsUpdated','erpRequestsUpdated','erpFinanceUpdated','erpClientDashboardUpdated'].forEach(name=>window.dispatchEvent(new CustomEvent(name,{detail:{project_id:data?.id,booking_id:data?.booking_id}})));closeModal();await fetchData()};
  const saveTask=async event=>{event.preventDefault();if(!selectedProject)return;setBusy('task');const assignedTo=canManage?(taskForm.assigned_to?Number(taskForm.assigned_to):null):Number(currentUser?.id);const payload={...taskForm,project_id:Number(selectedProject.id),assigned_to:assignedTo,due_at:apiDateTime(taskForm.due_at),status:'todo'};const{error:requestError}=await supabase.from('project_tasks').insert(payload);setBusy('');if(requestError)return setError(requestError.message||'تعذر إضافة المهمة.');setNotice('تمت إضافة المهمة.');closeModal();await fetchData()};
  const saveContent=async event=>{event.preventDefault();if(!selectedProject||!canManage)return setError('إضافة المحتوى متاحة لفريق الإدارة والتشغيل فقط.');setBusy('content');const payload={...contentForm,project_id:Number(selectedProject.id),scheduled_at:apiDateTime(contentForm.scheduled_at)};const{error:requestError}=await supabase.from('content_items').insert(payload);setBusy('');if(requestError)return setError(requestError.message||'تعذر إضافة المحتوى.');setNotice('تمت إضافة عنصر المحتوى.');closeModal();await fetchData()};
  const updateTask=async(task,status)=>{const allowed=canManage||Number(task.assigned_to)===Number(currentUser?.id);if(!allowed)return setError('لا يمكنك تحديث مهمة مسندة إلى مستخدم آخر.');setBusy(`task-${task.id}`);const{error:requestError}=await supabase.from('project_tasks').update({status,completed_at:status==='done'?new Date().toISOString().slice(0,19).replace('T',' '):null}).eq('id',task.id);setBusy('');if(requestError)return setError(requestError.message||'تعذر تحديث المهمة.');await fetchData()};
  const updateProjectStatus=async(project,status)=>{if(!canManage)return setError('لا تملك صلاحية تغيير حالة المشروع.');setBusy(`project-${project.id}`);const{error:requestError}=await supabase.from('projects').update({status}).eq('id',project.id);if(requestError){setBusy('');return setError(requestError.message||'تعذر تحديث حالة المشروع.')}await fetchData();const{data}=await supabase.from('projects').select('*').eq('id',project.id).single();if(data)setSelectedProject(data);setBusy('');setNotice('تم تحديث حالة المشروع.')};
  const saveProjectEdit=async(event)=>{event.preventDefault();if(!isOwner||!selectedProject)return;const form=new FormData(event.currentTarget);const values={name:String(form.get('name')||'').trim(),agreed_price:Number(form.get('agreed_price')||0),starts_at:form.get('starts_at')||null,due_at:form.get('due_at')||null,status:form.get('status'),notes:String(form.get('notes')||'')};setBusy('project-edit');const{error:requestError}=await supabase.from('projects').update(values).eq('id',selectedProject.id);setBusy('');if(requestError)return setError(requestError.message||'تعذر تعديل المشروع.');setNotice('تم تحديث بيانات المشروع.');closeModal();await fetchData()};
  const updateMilestoneStatus=async(milestone,status)=>{if(!canManage)return setError('لا تملك صلاحية تغيير مرحلة المشروع.');setBusy(`milestone-${milestone.id}`);const progress={pending:0,in_progress:50,review:85,completed:100,blocked:Number(milestone.progress_percent||0)}[status]??0;const{error:requestError}=await supabase.request(`/project-milestones/${milestone.id}/status`,{method:'POST',body:JSON.stringify({status,progress_percent:progress})});if(requestError){setBusy('');return setError(requestError.message||'تعذر تحديث مرحلة المشروع.')}await fetchData();const{data}=await supabase.from('projects').select('*').eq('id',milestone.project_id).single();if(data)setSelectedProject(data);setBusy('');setNotice('تم تحديث مرحلة المشروع وظهرت للعميل.')};
  const refreshMilestoneStructure=async(projectId)=>{await fetchData();const{data}=await supabase.from('projects').select('*').eq('id',projectId).single();if(data)setSelectedProject(data)};
  const addMilestone=async(project,title)=>{setBusy('milestone-add');const{error:requestError}=await supabase.request(`/projects/${project.id}/milestones`,{method:'POST',body:JSON.stringify({title,is_client_visible:true})});if(requestError){setBusy('');setError(requestError.message||'تعذر إضافة المرحلة.');return false}await refreshMilestoneStructure(project.id);setBusy('');setNotice('تمت إضافة المرحلة وظهرت في رحلة العميل.');return true};
  const renameMilestone=async(milestone,title)=>{setBusy(`milestone-rename-${milestone.id}`);const{error:requestError}=await supabase.request(`/project-milestones/${milestone.id}`,{method:'PATCH',body:JSON.stringify({title})});if(requestError){setBusy('');setError(requestError.message||'تعذر تعديل اسم المرحلة.');return false}await refreshMilestoneStructure(milestone.project_id);setBusy('');setNotice('تم تحديث اسم المرحلة.');return true};
  const reorderMilestones=async(project,orderedIds)=>{setBusy('milestone-reorder');const{error:requestError}=await supabase.request(`/projects/${project.id}/milestones/reorder`,{method:'POST',body:JSON.stringify({milestone_ids:orderedIds})});if(requestError){setBusy('');setError(requestError.message||'تعذر ترتيب المراحل.');return false}await refreshMilestoneStructure(project.id);setBusy('');setNotice('تم حفظ ترتيب المراحل.');return true};
  const updateContentStatus=async(item,status)=>{if(!canManage)return setError('تحديث المحتوى متاح لفريق الإدارة والتشغيل فقط.');setBusy(`content-${item.id}`);const values={status,published_at:status==='published'?new Date().toISOString().slice(0,19).replace('T',' '):null};const{error:requestError}=await supabase.from('content_items').update(values).eq('id',item.id);setBusy('');if(requestError)return setError(requestError.message||'تعذر تحديث حالة المحتوى.');setNotice('تم تحديث مرحلة المحتوى.');await fetchData()};
  const openChildEdit=(entity,record,event)=>{if(!isOwner)return;setEditingChild({entity,record});openModal('childEdit',event,projects.find(item=>Number(item.id)===Number(record.project_id))||selectedProject)};
  const saveChildEdit=async(event)=>{event.preventDefault();if(!isOwner||!editingChild)return;const form=new FormData(event.currentTarget);const {entity,record}=editingChild;let values;if(entity==='project_tasks')values={title:String(form.get('title')||'').trim(),description:String(form.get('description')||''),priority:form.get('priority'),assigned_to:form.get('assigned_to')?Number(form.get('assigned_to')):null,due_at:apiDateTime(form.get('due_at')),status:form.get('status')};else if(entity==='project_items')values={description:String(form.get('description')||'').trim(),quantity:Number(form.get('quantity')||0),unit:form.get('unit'),unit_price:Number(form.get('unit_price')||0),total_price:Number(form.get('total_price')||0),status:form.get('status'),is_client_visible:form.get('is_client_visible')==='on'?1:0};else if(entity==='content_items')values={title:String(form.get('title')||'').trim(),content_type:form.get('content_type'),platform:form.get('platform'),status:form.get('status'),scheduled_at:apiDateTime(form.get('scheduled_at')),caption:String(form.get('caption')||'')};else values={title:String(form.get('title')||'').trim(),status:form.get('status'),progress_percent:Number(form.get('progress_percent')||0),due_at:form.get('due_at')||null,client_note:String(form.get('client_note')||''),is_client_visible:form.get('is_client_visible')==='on'?1:0};setBusy('child-edit');const{error:requestError}=await supabase.from(entity).update(values).eq('id',record.id);setBusy('');if(requestError)return setError(requestError.message||'تعذر تعديل السجل الفرعي.');setNotice('تم حفظ التعديلات وتحديث مسار المشروع.');closeModal();await fetchData()};
  const showProject=(project,event)=>openModal('detail',event,project);
  const startCustomService=(serviceType,event)=>{setInitialService(serviceType||'custom');openModal('project',event)};

  return <main className="projects-command" dir="rtl">
    <ERPPageHero icon={Sparkles} eyebrow={`مركز الخدمات المخصصة · ${format(month,'MMMM yyyy',{locale:ar})}`} title="المشروعات والمحتوى" description="مركز تشغيل الخدمات المرنة: من الاتفاق والمتطلبات إلى المراحل والتسليم والتحصيل." actions={canManage&&<button data-variant="primary" onClick={event=>startCustomService('custom',event)}><Plus/> خدمة مخصصة جديدة</button>}/>
    <CustomServiceCatalog selected={serviceFilter} onSelect={setServiceFilter} onCreate={(type)=>startCustomService(type)} canManage={canManage}/>
    <section className="projects-metrics"><Metric icon={FolderKanban} label="مشروعات نشطة" value={metrics.active}/><Metric icon={WalletCards} label="قيمة التعاقدات" value={`${metrics.contracted.toLocaleString('ar-EG')} ج.م`} tone="cyan"/><Metric icon={CircleDollarSign} label="رصيد مستحق" value={`${metrics.outstanding.toLocaleString('ar-EG')} ج.م`} tone="amber"/><Metric icon={ClipboardCheck} label="بنود بانتظار الاعتماد" value={metrics.review} tone="red"/></section>
    {notice&&<div className="projects-feedback success"><CheckCircle2/>{notice}<button onClick={()=>setNotice('')}><X/></button></div>}{error&&<div className="projects-feedback error"><CircleAlert/>{error}<button onClick={()=>setError('')}><X/></button></div>}
    <section className="projects-toolbar"><nav><button className={tab==='projects'?'active':''} onClick={()=>{setTab('projects');setFilter('all')}}><FolderKanban/> المشروعات</button><button className={tab==='calendar'?'active':''} onClick={()=>{setTab('calendar');setFilter('all')}}><CalendarDays/> تقويم المحتوى</button><button className={tab==='tasks'?'active':''} onClick={()=>{setTab('tasks');setFilter('all')}}><LayoutList/> المهام</button></nav>{tab!=='calendar'&&<div className="projects-filters"><label><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={tab==='projects'?'ابحث عن مشروع أو عميل':'ابحث عن مهمة أو مشروع'}/></label><label><Filter/><select value={filter} onChange={event=>setFilter(event.target.value)}>{tab==='projects'?<><option value="all">كل الحالات</option>{Object.entries(PROJECT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</>:<><option value="all">كل المراحل</option>{Object.entries(TASK_STATUS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</>}</select></label></div>}<button className="projects-refresh" onClick={fetchData} aria-label="تحديث"><RefreshCw className={loading?'spin':''}/></button></section>
    {loading?<Empty icon={RefreshCw} spin title="جارٍ تجهيز مركز الخدمات" text="نرتب المشروعات والمراحل والتقويم والمهام..."/>:tab==='projects'?<ProjectsView projects={filteredProjects} clients={clients} tasks={tasks} content={content} milestones={milestones} invoices={invoices} onOpen={showProject}/>:tab==='calendar'?<CalendarView month={month} setMonth={setMonth} days={calendarDays} selectedDay={selectedDay} setSelectedDay={setSelectedDay} dayContent={dayContent} selectedContent={selectedContent} projectName={projectName} clientName={clientName} canEdit={canManage} busy={busy} onContentStatus={updateContentStatus}/>:<TasksView tasks={filteredTasks} projects={projects} users={users} currentUser={currentUser} canManage={canManage} busy={busy} onUpdate={updateTask} onEdit={(record,event)=>openChildEdit('project_tasks',record,event)} onChanged={fetchData}/>} {/* active workspace */}
    {modal && (
      <div className="project-modal" onMouseDown={event => event.target === event.currentTarget && closeModal()}>
        <section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="project-modal-title" className={`project-dialog ${['detail', 'project', 'projectEdit'].includes(modal) ? 'wide' : ''}`}>
          <button className="dialog-close" onClick={closeModal} aria-label="إغلاق"><X /></button>
          {modal === 'project' ? (
            <CustomServiceForm key={initialService} initialService={initialService} clients={clients} busy={busy === 'project'} onSubmit={saveProject} />
          ) : modal === 'projectEdit' ? (
            <ProjectEditForm project={selectedProject} busy={busy === 'project-edit'} onSubmit={saveProjectEdit} />
          ) : modal === 'childEdit' ? (
            <ChildEditForm entry={editingChild} users={users} busy={busy === 'child-edit'} onSubmit={saveChildEdit} />
          ) : modal === 'task' ? (
            <TaskForm form={taskForm} setForm={setTaskForm} users={users} currentUser={currentUser} canManage={canManage} busy={busy} project={selectedProject} onSubmit={saveTask} />
          ) : modal === 'content' ? (
            <ContentForm form={contentForm} setForm={setContentForm} busy={busy} project={selectedProject} onSubmit={saveContent} />
          ) : (
            <ProjectDetail
              project={selectedProject}
              clientName={clientName}
              tasks={projectTasks(selectedProject?.id)}
              content={projectContent(selectedProject?.id)}
              milestones={milestones.filter(item => Number(item.project_id) === Number(selectedProject?.id))}
              items={projectItems.filter(item => Number(item.project_id) === Number(selectedProject?.id))}
              booking={bookings.find(item => Number(item.project_id) === Number(selectedProject?.id))}
              invoice={invoices.find(item => Number(item.id) === Number(selectedProject?.invoice_id))}
              userName={userName}
              canManage={canManage}
              currentUser={currentUser}
              busy={busy}
              onProjectStatus={updateProjectStatus}
              onMilestoneStatus={updateMilestoneStatus}
              onAddMilestone={addMilestone}
              onRenameMilestone={renameMilestone}
              onReorderMilestones={reorderMilestones}
              onContentStatus={updateContentStatus}
              onTask={event => openModal('task', event, selectedProject)}
              onContent={event => openModal('content', event, selectedProject)}
              onEdit={event => openModal('projectEdit', event, selectedProject)}
              onEditChild={openChildEdit}
              onChanged={async () => { closeModal(); await fetchData() }}
            />
          )}
        </section>
      </div>
    )}
  </main>
}

function Metric({icon:Icon,label,value,tone=''}){return <article className={tone}><Icon/><div><span>{label}</span><strong>{value}</strong></div></article>}
function Status({meta}){return <span className={`project-status ${meta?.[1]||'muted'}`}>{meta?.[0]||'غير محدد'}</span>}
function Empty({icon:Icon,title,text,spin}){return <div className="projects-empty"><Icon className={spin?'spin':''}/><h3>{title}</h3><p>{text}</p></div>}
function ProjectsView({projects,clients,tasks,content,milestones,invoices,onOpen}){const name=id=>clients.find(item=>Number(item.id)===Number(id))?.name||'عميل';if(!projects.length)return <Empty icon={FolderKanban} title="لا توجد مشروعات مطابقة" text="أنشئ أول خدمة مخصصة أو غيّر خيارات البحث والتصفية."/>;return <section className="project-cards">{projects.map(project=>{const pt=tasks.filter(item=>Number(item.project_id)===Number(project.id)),pc=content.filter(item=>Number(item.project_id)===Number(project.id)),pm=milestones.filter(item=>Number(item.project_id)===Number(project.id)),invoice=invoices.find(item=>Number(item.id)===Number(project.invoice_id)),done=pt.filter(item=>item.status==='done').length,published=pc.filter(item=>item.status==='published').length,derivedProgress=pt.length?Math.round(done/pt.length*100):0,progress=Number(project.progress_percent??derivedProgress),nextMilestone=pm.find(item=>['active','in_progress'].includes(item.status))||pm.find(item=>!['completed','done'].includes(item.status)),nextTask=pt.find(item=>item.status!=='done'&&item.due_at),agreed=Number(project.agreed_price||invoice?.total||0),paid=Number(project.paid_amount??invoice?.paid_amount??0),remaining=Math.max(0,agreed-paid);return <button key={project.id} className="project-card" onClick={event=>onOpen(project,event)}><header><div><small>{serviceMeta(project.service_type).label}</small><h2>{project.name}</h2><p>{name(project.client_id)}</p></div><Status meta={PROJECT_STATUS[project.status]}/></header><div className="project-dates"><span><CalendarDays/> {dateText(project.starts_at)}</span><span>حتى {dateText(project.due_at)}</span></div><div className="project-progress"><div><span>تقدم المشروع</span><strong>{progress}%</strong></div><i><b style={{width:`${Math.min(100,Math.max(0,progress))}%`}}/></i></div><div className="project-card-finance"><span><small>قيمة الاتفاق</small><strong>{agreed.toLocaleString('ar-EG')} ج.م</strong></span><span><small>المدفوع</small><strong>{paid.toLocaleString('ar-EG')} ج.م</strong></span><span className={remaining?'due':''}><small>المتبقي</small><strong>{remaining.toLocaleString('ar-EG')} ج.م</strong></span></div><footer><span>{done}/{pt.length} مهام</span><span>{published}/{pc.length} محتوى</span><span className={nextTask&&new Date(nextTask.due_at.replace(' ','T'))<new Date()?'late':''}><Clock3/> {nextMilestone?.title||nextTask?.title||'لا توجد خطوة تالية'}</span></footer></button>})}</section>}
function CalendarView({month,setMonth,days,selectedDay,setSelectedDay,dayContent,selectedContent,projectName,clientName,canEdit,busy,onContentStatus}){return <section className="content-calendar"><div className="calendar-main"><header><div><button onClick={()=>setMonth(subMonths(month,1))} aria-label="الشهر السابق"><ChevronRight/></button><button onClick={()=>setMonth(startOfMonth(new Date()))}>اليوم</button><button onClick={()=>setMonth(addMonths(month,1))} aria-label="الشهر التالي"><ChevronLeft/></button></div><h2>{format(month,'MMMM yyyy',{locale:ar})}</h2></header><div className="calendar-weekdays">{['السبت','الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة'].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-grid">{days.map(day=>{const items=dayContent(day),selected=isSameDay(day,selectedDay);return <button key={day.toISOString()} className={`${!isSameMonth(day,month)?'outside':''} ${selected?'selected':''}`} onClick={()=>setSelectedDay(day)}><time>{format(day,'d')}</time><div>{items.slice(0,3).map(item=><span className={`content-dot ${CONTENT_STATUS[item.status]?.[1]||'muted'}`} key={item.id}><b>{format(new Date(item.scheduled_at.replace(' ','T')),'h:mm a',{locale:ar})}</b>{clientName(item.client_id)} · {item.title}</span>)}{items.length>3&&<em>+{items.length-3} أخرى</em>}</div></button>})}</div></div><aside className="calendar-focus"><span>تفاصيل اليوم</span><h3>{format(selectedDay,'EEEE، d MMMM',{locale:ar})}</h3>{selectedContent.map(item=><article key={item.id}><header>{canEdit?<select className="lifecycle-select" aria-label={`مرحلة ${item.title}`} disabled={busy===`content-${item.id}`} value={item.status} onChange={event=>onContentStatus(item,event.target.value)}>{Object.entries(CONTENT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select>:<Status meta={CONTENT_STATUS[item.status]}/>}<time>{dateTimeText(item.scheduled_at)}</time></header><h4>{item.title}</h4><p>{clientName(item.client_id)} · {projectName(item.project_id)}</p><footer>{PLATFORM[item.platform]||item.platform} · {CONTENT_TYPE[item.content_type]||item.content_type}</footer></article>)}{!selectedContent.length&&<Empty icon={CalendarDays} title="اليوم هادئ" text="لا يوجد محتوى مجدول في هذا اليوم."/>}</aside></section>}
function TasksView({tasks,projects,users,currentUser,canManage,busy,onUpdate,onEdit,onChanged}){const pn=id=>projects.find(item=>Number(item.id)===Number(id))?.name||'مشروع',un=id=>users.find(item=>Number(item.id)===Number(id))?.full_name||(Number(id)===Number(currentUser?.id)?currentUser?.full_name:'غير مسند');if(!tasks.length)return <Empty icon={ClipboardCheck} title="لا توجد مهام مطابقة" text="أضف مهمة من تفاصيل أي مشروع."/>;return <section className="tasks-pipeline">{Object.entries(TASK_STATUS).map(([status,label])=>{const list=tasks.filter(item=>item.status===status);return <section key={status}><header><h3>{label}</h3><span>{list.length}</span></header>{list.map(task=>{const canUpdate=canManage||Number(task.assigned_to)===Number(currentUser?.id);return <article key={task.id} className={task.due_at&&task.status!=='done'&&new Date(task.due_at.replace(' ','T'))<new Date()?'overdue':''}><div><small>{pn(task.project_id)}</small><h4>{task.title}</h4><p>{task.description||'بدون وصف إضافي'}</p></div><footer><span className={`priority ${task.priority}`}>{PRIORITY[task.priority]}</span><span>{un(task.assigned_to)}</span><time><Clock3/>{dateTimeText(task.due_at)}</time>{canUpdate?<select aria-label={`تغيير حالة ${task.title}`} disabled={busy===`task-${task.id}`} value={task.status} onChange={event=>onUpdate(task,event.target.value)}>{Object.entries(TASK_STATUS).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select>:<span className="task-locked">للقراءة فقط · المهمة مسندة لزميل آخر</span>}{currentUser?.role==='owner'&&<OwnerRecordActions compact user={currentUser} entity="project_tasks" record={task} label={task.title} onEdit={event=>onEdit(task,event)} onChanged={onChanged}/>}</footer></article>})}</section>})}</section>}

function ProjectEditForm({project,busy,onSubmit}){return <form onSubmit={onSubmit}><span className="dialog-kicker">تحكم المالك</span><h2 id="project-modal-title">تعديل بيانات المشروع</h2><div className="form-grid"><label className="wide-field">اسم المشروع<input name="name" required defaultValue={project?.name}/></label><label>قيمة الاتفاق<input name="agreed_price" type="number" min="0" step="0.01" defaultValue={project?.agreed_price||0}/></label><label>الحالة<select name="status" defaultValue={project?.status}>{Object.entries(PROJECT_STATUS).map(([value,meta])=><option key={value} value={value}>{meta[0]}</option>)}</select></label><label>تاريخ البداية<input name="starts_at" type="date" defaultValue={String(project?.starts_at||'').slice(0,10)}/></label><label>تاريخ التسليم<input name="due_at" type="date" defaultValue={String(project?.due_at||'').slice(0,10)}/></label><label className="wide-field">الملاحظات<textarea name="notes" rows="4" defaultValue={project?.notes||''}/></label></div><button className="dialog-submit" disabled={busy}><Save/> {busy?'جارٍ الحفظ...':'حفظ التعديلات'}</button></form>}
function ChildEditForm({entry,users,busy,onSubmit}){const entity=entry?.entity,record=entry?.record||{};if(!entity)return null;const titles={project_tasks:'تعديل المهمة',project_items:'تعديل بند التسليم',project_milestones:'تعديل مرحلة الإنتاج',content_items:'تعديل المحتوى'};return <form onSubmit={onSubmit}><span className="dialog-kicker">تحكم المالك · سجل موثق</span><h2 id="project-modal-title">{titles[entity]}</h2><div className="form-grid">
  {entity==='project_tasks'&&<><label className="wide-field">العنوان<input name="title" required defaultValue={record.title}/></label><label>الحالة<select name="status" defaultValue={record.status}>{Object.entries(TASK_STATUS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>الأولوية<select name="priority" defaultValue={record.priority||'normal'}>{Object.entries(PRIORITY).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>مسندة إلى<select name="assigned_to" defaultValue={record.assigned_to||''}><option value="">غير مسندة</option>{users.map(user=><option key={user.id} value={user.id}>{user.full_name}</option>)}</select></label><label>موعد التنفيذ<input name="due_at" type="datetime-local" defaultValue={String(record.due_at||'').slice(0,16).replace(' ','T')}/></label><label className="wide-field">الوصف<textarea name="description" rows="4" defaultValue={record.description||''}/></label></>}
  {entity==='project_items'&&<><label className="wide-field">وصف بند التسليم<input name="description" required defaultValue={record.description}/></label><label>الكمية<input name="quantity" type="number" min="0" step="0.01" defaultValue={record.quantity||1}/></label><label>الوحدة<select name="unit" defaultValue={record.unit||'project'}>{Object.entries(UNIT_LABEL).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>سعر الوحدة<input name="unit_price" type="number" min="0" step="0.01" defaultValue={record.unit_price||0}/></label><label>الإجمالي<input name="total_price" type="number" min="0" step="0.01" defaultValue={record.total_price||0}/></label><label>الحالة<select name="status" defaultValue={record.status||'draft'}>{[['draft','مسودة'],['planning','تخطيط'],['in_progress','قيد التنفيذ'],['in_review','للمراجعة'],['completed','مكتمل']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="policy-checkbox"><input name="is_client_visible" type="checkbox" defaultChecked={Number(record.is_client_visible??1)===1}/> ظاهر للعميل</label></>}
  {entity==='project_milestones'&&<><label className="wide-field">اسم المرحلة<input name="title" required defaultValue={record.title}/></label><label>الحالة<select name="status" defaultValue={record.status||'pending'}>{Object.entries(MILESTONE_STATUS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>نسبة الإنجاز<input name="progress_percent" type="number" min="0" max="100" defaultValue={record.progress_percent||0}/></label><label>تاريخ الاستحقاق<input name="due_at" type="date" defaultValue={String(record.due_at||'').slice(0,10)}/></label><label className="wide-field">ملاحظة للعميل<textarea name="client_note" rows="3" defaultValue={record.client_note||''}/></label><label className="policy-checkbox"><input name="is_client_visible" type="checkbox" defaultChecked={Number(record.is_client_visible??1)===1}/> ظاهر للعميل</label></>}
  {entity==='content_items'&&<><label className="wide-field">العنوان<input name="title" required defaultValue={record.title}/></label><label>النوع<select name="content_type" defaultValue={record.content_type||'post'}>{Object.entries(CONTENT_TYPE).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>المنصة<select name="platform" defaultValue={record.platform||'instagram'}>{Object.entries(PLATFORM).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>الحالة<select name="status" defaultValue={record.status||'idea'}>{Object.entries(CONTENT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select></label><label>موعد النشر<input name="scheduled_at" type="datetime-local" defaultValue={String(record.scheduled_at||'').slice(0,16).replace(' ','T')}/></label><label className="wide-field">النص / Caption<textarea name="caption" rows="5" defaultValue={record.caption||''}/></label></>}
</div><button className="dialog-submit" disabled={busy}><Save/> {busy?'جارٍ الحفظ...':'حفظ التعديلات'}</button></form>}
function TaskForm({form,setForm,users,currentUser,canManage,busy,project,onSubmit}){return <form onSubmit={onSubmit}><span className="dialog-kicker">{project?.name}</span><h2 id="project-modal-title">إضافة مهمة تشغيلية</h2><div className="form-grid"><label className="wide-field">عنوان المهمة<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>الأولوية<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{Object.entries(PRIORITY).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{canManage?<label>مسندة إلى<select value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}><option value="">غير مسندة</option>{users.map(user=><option key={user.id} value={user.id}>{user.full_name}</option>)}</select></label>:<label>مسندة إلى<input value={currentUser?.full_name||'حسابي'} disabled/></label>}<label className="wide-field">موعد التنفيذ<input required type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label className="wide-field">الوصف<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button className="dialog-submit" disabled={busy==='task'}><Plus/> {busy==='task'?'جارٍ الحفظ...':'إضافة المهمة'}</button></form>}
function ContentForm({form,setForm,busy,project,onSubmit}){return <form onSubmit={onSubmit}><span className="dialog-kicker">{project?.name}</span><h2 id="project-modal-title">إضافة محتوى للتقويم</h2><div className="form-grid"><label className="wide-field">عنوان المحتوى<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>النوع<select value={form.content_type} onChange={e=>setForm({...form,content_type:e.target.value})}>{Object.entries(CONTENT_TYPE).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>المنصة<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}>{Object.entries(PLATFORM).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(CONTENT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select></label><label>موعد النشر<input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></label><label className="wide-field">النص / Caption<textarea rows="5" value={form.caption} onChange={e=>setForm({...form,caption:e.target.value})}/></label></div><button className="dialog-submit" disabled={busy==='content'}><Plus/> {busy==='content'?'جارٍ الحفظ...':'إضافة المحتوى'}</button></form>}
function ProjectDetail({project,clientName,tasks,content,milestones,items,booking,invoice,userName,canManage,currentUser,busy,onProjectStatus,onMilestoneStatus,onAddMilestone,onRenameMilestone,onReorderMilestones,onContentStatus,onTask,onContent,onEdit,onEditChild,onChanged}){
  if(!project)return null;
  const agreed=Number(project.agreed_price||invoice?.total||0),paid=Number(project.paid_amount||invoice?.paid_amount||0),remaining=Math.max(0,agreed-paid);
  const requirements=typeof project.requirements_json==='string'?(()=>{try{return JSON.parse(project.requirements_json)}catch{return {notes:project.requirements_json}}})():project.requirements_json||{};
  return <div>
    <span className="dialog-kicker">{serviceMeta(project.service_type).label}</span>
    <div className="detail-head"><div><h2 id="project-modal-title">{project.name}</h2><p>{clientName(project.client_id)} · {dateText(project.starts_at)} — {dateText(project.due_at)}</p></div>{canManage?<label className="lifecycle-control">مرحلة المشروع<select disabled={busy===`project-${project.id}`} value={project.status} onChange={event=>onProjectStatus(project,event.target.value)}>{Object.entries(PROJECT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select></label>:<Status meta={PROJECT_STATUS[project.status]}/>}</div>
    <OwnerRecordActions user={currentUser} entity="projects" record={project} label={project.name} onEdit={onEdit} onChanged={onChanged}/>
    <div className="project-detail-summary"><article><span>قيمة الاتفاق</span><strong>{agreed.toLocaleString('ar-EG')} ج.م</strong></article><article><span>المدفوع</span><strong>{paid.toLocaleString('ar-EG')} ج.م</strong></article><article><span>المتبقي</span><strong>{remaining.toLocaleString('ar-EG')} ج.م</strong></article><article><span>الكمية</span><strong>{Number(project.quantity||1).toLocaleString('ar-EG')} {UNIT_LABEL[project.unit_label]||UNIT_LABEL[serviceMeta(project.service_type).unit]||project.unit_label||serviceMeta(project.service_type).unit}</strong></article></div>
    <ProjectMilestoneSection project={project} milestones={milestones} canManage={canManage} currentUser={currentUser} busy={busy} onStatus={onMilestoneStatus} onAdd={onAddMilestone} onRename={onRenameMilestone} onEdit={(record,event)=>onEditChild('project_milestones',record,event)} onChanged={onChanged} onReorder={onReorderMilestones}/>
    {requirements.notes&&<p className="project-requirements">{requirements.notes}</p>}{project.notes&&<p className="detail-note">{project.notes}</p>}{booking&&<p className="detail-note"><strong>الموعد المرتبط:</strong> {dateText(booking.date)} · {formatTime12(booking.start_time,'')} — {formatTime12(booking.end_time,'')}</p>}
    <div className="detail-actions"><button onClick={onTask}><Plus/> مهمة</button>{canManage&&<button onClick={onContent}><Plus/> محتوى</button>}{!canManage&&<small>يمكنك إنشاء وتحديث مهامك المسندة فقط.</small>}</div>
    <div className="detail-columns"><section><header><h3>بنود التسليم والمهام</h3><span>{items.length+tasks.length}</span></header>{items.map(item=><article key={`item-${item.id}`}><div><strong>{item.description}</strong><Status meta={[item.status==='completed'?'مكتمل':item.status==='in_review'?'للمراجعة':'قيد التنفيذ',item.status==='completed'?'done':item.status==='in_review'?'review':'planning']}/></div><small>{Number(item.quantity||1).toLocaleString('ar-EG')} {UNIT_LABEL[item.unit]||item.unit||'وحدة'}</small><OwnerRecordActions compact user={currentUser} entity="project_items" record={item} label={item.description} onEdit={event=>onEditChild('project_items',item,event)} onChanged={onChanged}/></article>)}{tasks.map(task=><article key={task.id}><div><strong>{task.title}</strong><span>{userName(task.assigned_to)}</span></div><small>{TASK_STATUS[task.status]} · {dateTimeText(task.due_at)}</small><OwnerRecordActions compact user={currentUser} entity="project_tasks" record={task} label={task.title} onEdit={event=>onEditChild('project_tasks',task,event)} onChanged={onChanged}/></article>)}{!items.length&&!tasks.length&&<p className="detail-empty">لم تُضف بنود أو مهام بعد.</p>}</section><section><header><h3>المحتوى</h3><span>{content.length}</span></header>{content.map(item=><article key={item.id}><div><strong>{item.title}</strong>{canManage?<select className="lifecycle-select" aria-label={`مرحلة ${item.title}`} disabled={busy===`content-${item.id}`} value={item.status} onChange={event=>onContentStatus(item,event.target.value)}>{Object.entries(CONTENT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select>:<Status meta={CONTENT_STATUS[item.status]}/>}</div><small>{PLATFORM[item.platform]||item.platform} · {dateTimeText(item.scheduled_at)}</small><OwnerRecordActions compact user={currentUser} entity="content_items" record={item} label={item.title} onEdit={event=>onEditChild('content_items',item,event)} onChanged={onChanged}/></article>)}{!content.length&&<p className="detail-empty">لم يُضف محتوى بعد.</p>}</section></div>
  </div>
}

function ProjectMilestoneSection({project,milestones,canManage,currentUser,busy,onStatus,onAdd,onRename,onEdit,onChanged,onReorder}){
  const [editing,setEditing]=useState(false),[drafts,setDrafts]=useState(()=>Object.fromEntries(milestones.map(item=>[item.id,item.title]))),[newTitle,setNewTitle]=useState(''),[localError,setLocalError]=useState('');
  const move=async(index,direction)=>{const target=index+direction;if(target<0||target>=milestones.length)return;const next=[...milestones];[next[index],next[target]]=[next[target],next[index]];const ok=await onReorder(project,next.map(item=>item.id));if(!ok)setLocalError('تعذر حفظ ترتيب المراحل. حاول مرة أخرى.')};
  const rename=async milestone=>{const title=String(drafts[milestone.id]||'').trim();if(!title)return setLocalError('اسم المرحلة لا يمكن أن يكون فارغًا.');if(title===milestone.title)return;const ok=await onRename(milestone,title);setLocalError(ok?'':'تعذر تعديل اسم المرحلة.')};
  const add=async()=>{const title=newTitle.trim();if(!title)return setLocalError('اكتب اسم المرحلة الجديدة أولًا.');const ok=await onAdd(project,title);if(ok){setNewTitle('');setLocalError('')}else setLocalError('تعذر إضافة المرحلة.')};
  return <section className="milestone-workflow">
    <header><div><span>مسار الإنتاج</span><h3>مراحل المشروع</h3></div>{canManage&&<button type="button" className={editing?'active':''} onClick={()=>{setEditing(value=>!value);setLocalError('')}}><Settings2/> {editing?'إنهاء التعديل':'تعديل المراحل'}</button>}</header>
    {milestones.length?<div className="project-detail-journey">{milestones.map((milestone,index)=>{const done=['completed','done'].includes(milestone.status),active=['active','in_progress'].includes(milestone.status);return <div key={milestone.id||index} className={`${done?'done':''} ${active?'active':''}`}><span>{done?'✓':index+1}</span><strong>{milestone.title}</strong><small>{MILESTONE_STATUS[milestone.status]||'قادمة'}</small>{canManage&&<select aria-label={`تحديث مرحلة ${milestone.title}`} disabled={busy===`milestone-${milestone.id}`} value={milestone.status==='active'?'in_progress':milestone.status==='done'?'completed':milestone.status} onChange={event=>onStatus(milestone,event.target.value)}>{Object.entries(MILESTONE_STATUS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>}<OwnerRecordActions compact user={currentUser} entity="project_milestones" record={milestone} label={milestone.title} onEdit={event=>onEdit(milestone,event)} onChanged={onChanged}/></div>})}</div>:<p className="milestone-empty">لم تُضف مراحل إنتاج لهذا المشروع بعد.</p>}
    {editing&&<div className="milestone-manager">
      <p>عدّل المسار المحفوظ لهذا المشروع. المراحل المكتملة محمية من الحذف، ويجب الإبقاء على مرحلتين على الأقل.</p>
      <div className="milestone-manager-list">{milestones.map((milestone,index)=><div key={milestone.id} className="milestone-manager-row">
        <b>{(index+1).toLocaleString('ar-EG')}</b>
        <input value={drafts[milestone.id]??milestone.title} onChange={event=>setDrafts(values=>({...values,[milestone.id]:event.target.value}))} onBlur={()=>rename(milestone)} aria-label={`اسم مرحلة ${index+1}`}/>
        <button type="button" onClick={()=>rename(milestone)} disabled={busy===`milestone-rename-${milestone.id}`||drafts[milestone.id]===milestone.title} aria-label={`حفظ اسم ${milestone.title}`}><Save/></button>
        <div><button type="button" disabled={index===0||busy==='milestone-reorder'} onClick={()=>move(index,-1)} aria-label={`تحريك ${milestone.title} لأعلى`}><ArrowUp/></button><button type="button" disabled={index===milestones.length-1||busy==='milestone-reorder'} onClick={()=>move(index,1)} aria-label={`تحريك ${milestone.title} لأسفل`}><ArrowDown/></button></div>
        <OwnerRecordActions compact user={currentUser} entity="project_milestones" record={milestone} label={milestone.title} onEdit={event=>onEdit(milestone,event)} onChanged={onChanged}/>
      </div>)}</div>
      <div className="milestone-manager-add"><input value={newTitle} onChange={event=>setNewTitle(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();add()}}} placeholder="اسم مرحلة جديدة"/><button type="button" onClick={add} disabled={busy==='milestone-add'}>{busy==='milestone-add'?<RefreshCw className="spin"/>:<Plus/>} إضافة المرحلة</button></div>
      {localError&&<p className="milestone-manager-error" role="alert">{localError}</p>}
    </div>}
  </section>
}
