import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, startOfMonth, startOfWeek, subMonths } from 'date-fns';
import { ar } from 'date-fns/locale';
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, ClipboardCheck, Clock3, Filter, FolderKanban, LayoutList, Plus, RefreshCw, Search, Sparkles, X } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { useData } from '../store/DataContext';
import './ERPProjects.css';
import './ERPProjectsLifecycle.css';

const PROJECT_STATUS={planning:['تخطيط','planning'],active:['نشط','active'],on_hold:['متوقف مؤقتًا','hold'],completed:['مكتمل','done'],cancelled:['ملغي','muted']};
const TASK_STATUS={todo:'قيد الانتظار',in_progress:'قيد التنفيذ',review:'للمراجعة',done:'مكتملة',blocked:'متوقفة'};
const CONTENT_STATUS={idea:['فكرة','muted'],draft:['مسودة','planning'],in_review:['للمراجعة','review'],approved:['معتمد','approved'],scheduled:['مجدول','scheduled'],published:['منشور','done'],rejected:['مرفوض','danger']};
const CATEGORY={social_media:'إدارة سوشيال',digital_marketing:'تسويق رقمي',ad_production:'إنتاج إعلاني'};
const PLATFORM={instagram:'Instagram',facebook:'Facebook',tiktok:'TikTok',youtube:'YouTube',linkedin:'LinkedIn',website:'Website'};
const CONTENT_TYPE={post:'منشور',reel:'ريل',story:'ستوري',video:'فيديو',ad:'إعلان',article:'مقال'};
const PRIORITY={low:'منخفضة',normal:'عادية',high:'عالية',urgent:'عاجلة'};
const blankProject={client_id:'',client_package_id:'',name:'',category:'social_media',starts_at:'',due_at:'',monthly_cycle_day:'',notes:''};
const blankTask={title:'',description:'',priority:'normal',assigned_to:'',due_at:''};
const blankContent={title:'',content_type:'post',platform:'instagram',status:'idea',scheduled_at:'',caption:''};
const dateText=value=>value?format(new Date(`${String(value).slice(0,10)}T12:00:00`),'d MMMM yyyy',{locale:ar}):'غير محدد';
const dateTimeText=value=>value?format(new Date(value.replace(' ','T')),'d MMM، h:mm a',{locale:ar}):'غير محدد';
const apiDateTime=value=>value?`${value.replace('T',' ')}:00`:null;

export default function ERPProjects(){
  const{currentUser}=useData();
  const canManage=['owner','admin','operations'].includes(currentUser?.role);
  const[projects,setProjects]=useState([]),[tasks,setTasks]=useState([]),[content,setContent]=useState([]),[clients,setClients]=useState([]),[packages,setPackages]=useState([]),[users,setUsers]=useState([]);
  const[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('projects'),[search,setSearch]=useState(''),[filter,setFilter]=useState('all');
  const[month,setMonth]=useState(startOfMonth(new Date())),[selectedDay,setSelectedDay]=useState(new Date()),[projectForm,setProjectForm]=useState(blankProject),[taskForm,setTaskForm]=useState(blankTask),[contentForm,setContentForm]=useState(blankContent);
  const[modal,setModal]=useState(null),[selectedProject,setSelectedProject]=useState(null),[busy,setBusy]=useState('');
  const[now]=useState(()=>new Date());
  const dialogRef=useRef(null),triggerRef=useRef(null);
  const fetchData=useCallback(async()=>{
    setLoading(true);setError('');
    const packagesQuery=currentUser?.role==='staff'?Promise.resolve({data:[],error:null}):supabase.from('client_packages').select('*').order('expires_at');
    const calls=[supabase.from('projects').select('*').order('updated_at',{ascending:false}),supabase.from('project_tasks').select('*').order('due_at',{ascending:true}),supabase.from('content_items').select('*').order('scheduled_at',{ascending:true}),supabase.from('clients').select('id,name,company_name,color').order('name'),packagesQuery];
    const results=await Promise.all(calls);const failed=results.find(result=>result.error);
    if(failed?.error)setError(failed.error.message||'تعذر تحميل مساحة المشروعات.');else{setProjects(results[0].data||[]);setTasks(results[1].data||[]);setContent(results[2].data||[]);setClients(results[3].data||[]);setPackages(results[4].data||[])}
    if(canManage){const result=await supabase.request('/users/assignees',{method:'GET'});if(!result.error)setUsers((result.data||[]).filter(user=>user.is_active!==false&&user.role!=='client'));else setUsers(currentUser?[currentUser]:[]);}else setUsers(currentUser?[currentUser]:[]);
    setLoading(false);
  },[canManage,currentUser]);
  // Remote workspace data must be synchronized when the authenticated identity changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{fetchData()},[fetchData]);
  const openModal=(name,event,project=null)=>{if(!modal)triggerRef.current=event?.currentTarget||document.activeElement;if(project)setSelectedProject(project);setModal(name)};
  const closeModal=useCallback(()=>{setModal(null);setProjectForm(blankProject);setTaskForm(blankTask);setContentForm(blankContent)},[]);
  const modalOpen=Boolean(modal);
  useEffect(()=>{if(!modalOpen)return;const list=()=>Array.from(dialogRef.current?.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')||[]);const key=event=>{if(event.key==='Escape')closeModal();if(event.key==='Tab'){const items=list();if(!items.length)return;const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow='';requestAnimationFrame(()=>triggerRef.current?.focus())}},[modalOpen,closeModal]);
  useEffect(()=>{if(modal)requestAnimationFrame(()=>dialogRef.current?.querySelector('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')?.focus())},[modal]);
  const clientName=id=>clients.find(item=>Number(item.id)===Number(id))?.name||'عميل';
  const projectName=id=>projects.find(item=>Number(item.id)===Number(id))?.name||'مشروع';
  const userName=id=>users.find(item=>Number(item.id)===Number(id))?.full_name||(Number(id)===Number(currentUser?.id)?currentUser?.full_name:'غير مسند');
  const projectTasks=id=>tasks.filter(item=>Number(item.project_id)===Number(id)),projectContent=id=>content.filter(item=>Number(item.project_id)===Number(id));
  const weekEnd=new Date(now.getTime()+7*86400000);
  const metrics={active:projects.filter(item=>item.status==='active').length,week:content.filter(item=>item.scheduled_at&&new Date(item.scheduled_at.replace(' ','T'))>=now&&new Date(item.scheduled_at.replace(' ','T'))<=weekEnd).length,review:content.filter(item=>item.status==='in_review').length,overdue:tasks.filter(item=>item.due_at&&item.status!=='done'&&new Date(item.due_at.replace(' ','T'))<now).length};
  const filteredProjects=projects.filter(project=>(filter==='all'||project.status===filter)&&`${project.name} ${clientName(project.client_id)}`.toLowerCase().includes(search.toLowerCase()));
  const filteredTasks=tasks.filter(task=>(filter==='all'||task.status===filter)&&`${task.title} ${projectName(task.project_id)}`.toLowerCase().includes(search.toLowerCase()));
  const calendarDays=useMemo(()=>eachDayOfInterval({start:startOfWeek(startOfMonth(month),{weekStartsOn:6}),end:endOfWeek(endOfMonth(month),{weekStartsOn:6})}),[month]);
  const dayContent=day=>content.filter(item=>item.scheduled_at&&isSameDay(new Date(item.scheduled_at.replace(' ','T')),day));
  const selectedContent=dayContent(selectedDay);
  const saveProject=async event=>{event.preventDefault();setBusy('project');const payload={...projectForm,client_id:Number(projectForm.client_id),client_package_id:projectForm.client_package_id?Number(projectForm.client_package_id):null,monthly_cycle_day:projectForm.monthly_cycle_day?Number(projectForm.monthly_cycle_day):null,status:'planning'};const{error:requestError}=await supabase.from('projects').insert(payload);setBusy('');if(requestError)return setError(requestError.message||'تعذر إنشاء المشروع.');setNotice('تم إنشاء المشروع بنجاح.');closeModal();await fetchData()};
  const saveTask=async event=>{event.preventDefault();if(!selectedProject)return;setBusy('task');const assignedTo=canManage?(taskForm.assigned_to?Number(taskForm.assigned_to):null):Number(currentUser?.id);const payload={...taskForm,project_id:Number(selectedProject.id),assigned_to:assignedTo,due_at:apiDateTime(taskForm.due_at),status:'todo'};const{error:requestError}=await supabase.from('project_tasks').insert(payload);setBusy('');if(requestError)return setError(requestError.message||'تعذر إضافة المهمة.');setNotice('تمت إضافة المهمة.');closeModal();await fetchData()};
  const saveContent=async event=>{event.preventDefault();if(!selectedProject||!canManage)return setError('إضافة المحتوى متاحة لفريق الإدارة والتشغيل فقط.');setBusy('content');const payload={...contentForm,project_id:Number(selectedProject.id),scheduled_at:apiDateTime(contentForm.scheduled_at)};const{error:requestError}=await supabase.from('content_items').insert(payload);setBusy('');if(requestError)return setError(requestError.message||'تعذر إضافة المحتوى.');setNotice('تمت إضافة عنصر المحتوى.');closeModal();await fetchData()};
  const updateTask=async(task,status)=>{const allowed=canManage||Number(task.assigned_to)===Number(currentUser?.id);if(!allowed)return setError('لا يمكنك تحديث مهمة مسندة إلى مستخدم آخر.');setBusy(`task-${task.id}`);const{error:requestError}=await supabase.from('project_tasks').update({status,completed_at:status==='done'?new Date().toISOString().slice(0,19).replace('T',' '):null}).eq('id',task.id);setBusy('');if(requestError)return setError(requestError.message||'تعذر تحديث المهمة.');await fetchData()};
  const updateProjectStatus=async(project,status)=>{if(!canManage)return setError('لا تملك صلاحية تغيير حالة المشروع.');setBusy(`project-${project.id}`);const{error:requestError}=await supabase.from('projects').update({status}).eq('id',project.id);if(requestError){setBusy('');return setError(requestError.message||'تعذر تحديث حالة المشروع.')}await fetchData();const{data}=await supabase.from('projects').select('*').eq('id',project.id).single();if(data)setSelectedProject(data);setBusy('');setNotice('تم تحديث حالة المشروع.')};
  const updateContentStatus=async(item,status)=>{if(!canManage)return setError('تحديث المحتوى متاح لفريق الإدارة والتشغيل فقط.');setBusy(`content-${item.id}`);const values={status,published_at:status==='published'?new Date().toISOString().slice(0,19).replace('T',' '):null};const{error:requestError}=await supabase.from('content_items').update(values).eq('id',item.id);setBusy('');if(requestError)return setError(requestError.message||'تعذر تحديث حالة المحتوى.');setNotice('تم تحديث مرحلة المحتوى.');await fetchData()};
  const showProject=(project,event)=>openModal('detail',event,project);
  const packagesForClient=packages.filter(item=>Number(item.client_id)===Number(projectForm.client_id));

  return <main className="projects-command" dir="rtl">
    <header className="projects-head"><div><span><Sparkles/> مركز الإنتاج · {format(month,'MMMM yyyy',{locale:ar})}</span><h1>المشروعات والمحتوى</h1><p>مسار واحد للحملات والمهام وجدول النشر، من الفكرة حتى التسليم.</p></div>{canManage&&<button onClick={event=>openModal('project',event)}><Plus/> مشروع جديد</button>}</header>
    <section className="projects-metrics"><Metric icon={FolderKanban} label="مشروعات نشطة" value={metrics.active}/><Metric icon={CalendarDays} label="محتوى هذا الأسبوع" value={metrics.week} tone="cyan"/><Metric icon={ClipboardCheck} label="بانتظار الاعتماد" value={metrics.review} tone="amber"/><Metric icon={CircleAlert} label="مهام متأخرة" value={metrics.overdue} tone="red"/></section>
    {notice&&<div className="projects-feedback success"><CheckCircle2/>{notice}<button onClick={()=>setNotice('')}><X/></button></div>}{error&&<div className="projects-feedback error"><CircleAlert/>{error}<button onClick={()=>setError('')}><X/></button></div>}
    <section className="projects-toolbar"><nav><button className={tab==='projects'?'active':''} onClick={()=>{setTab('projects');setFilter('all')}}><FolderKanban/> المشروعات</button><button className={tab==='calendar'?'active':''} onClick={()=>{setTab('calendar');setFilter('all')}}><CalendarDays/> تقويم المحتوى</button><button className={tab==='tasks'?'active':''} onClick={()=>{setTab('tasks');setFilter('all')}}><LayoutList/> المهام</button></nav>{tab!=='calendar'&&<div className="projects-filters"><label><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={tab==='projects'?'ابحث عن مشروع أو عميل':'ابحث عن مهمة أو مشروع'}/></label><label><Filter/><select value={filter} onChange={event=>setFilter(event.target.value)}>{tab==='projects'?<><option value="all">كل الحالات</option>{Object.entries(PROJECT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</>:<><option value="all">كل المراحل</option>{Object.entries(TASK_STATUS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</>}</select></label></div>}<button className="projects-refresh" onClick={fetchData} aria-label="تحديث"><RefreshCw className={loading?'spin':''}/></button></section>
    {loading?<Empty icon={RefreshCw} spin title="جارٍ تجهيز مركز الإنتاج" text="نرتب المشروعات والتقويم والمهام..."/>:tab==='projects'?<ProjectsView projects={filteredProjects} clients={clients} tasks={tasks} content={content} onOpen={showProject}/>:tab==='calendar'?<CalendarView month={month} setMonth={setMonth} days={calendarDays} selectedDay={selectedDay} setSelectedDay={setSelectedDay} dayContent={dayContent} selectedContent={selectedContent} projectName={projectName} clientName={clientName} canEdit={canManage} busy={busy} onContentStatus={updateContentStatus}/>:<TasksView tasks={filteredTasks} projects={projects} users={users} currentUser={currentUser} canManage={canManage} busy={busy} onUpdate={updateTask}/>} {/* active workspace */}
    {modal&&<div className="project-modal" onMouseDown={event=>event.target===event.currentTarget&&closeModal()}><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="project-modal-title" className={`project-dialog ${modal==='detail'?'wide':''}`}><button className="dialog-close" onClick={closeModal} aria-label="إغلاق"><X/></button>{modal==='project'?<ProjectForm form={projectForm} setForm={setProjectForm} clients={clients} packages={packagesForClient} busy={busy} onSubmit={saveProject}/>:modal==='task'?<TaskForm form={taskForm} setForm={setTaskForm} users={users} currentUser={currentUser} canManage={canManage} busy={busy} project={selectedProject} onSubmit={saveTask}/>:modal==='content'?<ContentForm form={contentForm} setForm={setContentForm} busy={busy} project={selectedProject} onSubmit={saveContent}/>:<ProjectDetail project={selectedProject} clientName={clientName} tasks={projectTasks(selectedProject?.id)} content={projectContent(selectedProject?.id)} userName={userName} canManage={canManage} busy={busy} onProjectStatus={updateProjectStatus} onContentStatus={updateContentStatus} onTask={event=>openModal('task',event,selectedProject)} onContent={event=>openModal('content',event,selectedProject)}/>}</section></div>}
  </main>
}

function Metric({icon:Icon,label,value,tone=''}){return <article className={tone}><Icon/><div><span>{label}</span><strong>{value}</strong></div></article>}
function Status({meta}){return <span className={`project-status ${meta?.[1]||'muted'}`}>{meta?.[0]||'غير محدد'}</span>}
function Empty({icon:Icon,title,text,spin}){return <div className="projects-empty"><Icon className={spin?'spin':''}/><h3>{title}</h3><p>{text}</p></div>}
function ProjectsView({projects,clients,tasks,content,onOpen}){const name=id=>clients.find(item=>Number(item.id)===Number(id))?.name||'عميل';if(!projects.length)return <Empty icon={FolderKanban} title="لا توجد مشروعات مطابقة" text="أنشئ أول مشروع أو غيّر خيارات البحث."/>;return <section className="project-cards">{projects.map(project=>{const pt=tasks.filter(item=>Number(item.project_id)===Number(project.id)),pc=content.filter(item=>Number(item.project_id)===Number(project.id)),done=pt.filter(item=>item.status==='done').length,published=pc.filter(item=>item.status==='published').length,progress=pt.length?Math.round(done/pt.length*100):0,next=pt.find(item=>item.status!=='done'&&item.due_at);return <button key={project.id} className="project-card" onClick={event=>onOpen(project,event)}><header><div><small>{CATEGORY[project.category]||project.category}</small><h2>{project.name}</h2><p>{name(project.client_id)}</p></div><Status meta={PROJECT_STATUS[project.status]}/></header><div className="project-dates"><span><CalendarDays/> {dateText(project.starts_at)}</span><span>حتى {dateText(project.due_at)}</span></div><div className="project-progress"><div><span>تقدم المهام</span><strong>{progress}%</strong></div><i><b style={{width:`${progress}%`}}/></i></div><footer><span>{done}/{pt.length} مهام</span><span>{published}/{pc.length} منشور</span><span className={next&&new Date(next.due_at.replace(' ','T'))<new Date()?'late':''}><Clock3/> {next?next.title:'لا توجد مهمة تالية'}</span></footer></button>})}</section>}
function CalendarView({month,setMonth,days,selectedDay,setSelectedDay,dayContent,selectedContent,projectName,clientName,canEdit,busy,onContentStatus}){return <section className="content-calendar"><div className="calendar-main"><header><div><button onClick={()=>setMonth(subMonths(month,1))} aria-label="الشهر السابق"><ChevronRight/></button><button onClick={()=>setMonth(startOfMonth(new Date()))}>اليوم</button><button onClick={()=>setMonth(addMonths(month,1))} aria-label="الشهر التالي"><ChevronLeft/></button></div><h2>{format(month,'MMMM yyyy',{locale:ar})}</h2></header><div className="calendar-weekdays">{['السبت','الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة'].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-grid">{days.map(day=>{const items=dayContent(day),selected=isSameDay(day,selectedDay);return <button key={day.toISOString()} className={`${!isSameMonth(day,month)?'outside':''} ${selected?'selected':''}`} onClick={()=>setSelectedDay(day)}><time>{format(day,'d')}</time><div>{items.slice(0,3).map(item=><span className={`content-dot ${CONTENT_STATUS[item.status]?.[1]||'muted'}`} key={item.id}><b>{format(new Date(item.scheduled_at.replace(' ','T')),'h:mm a',{locale:ar})}</b>{clientName(item.client_id)} · {item.title}</span>)}{items.length>3&&<em>+{items.length-3} أخرى</em>}</div></button>})}</div></div><aside className="calendar-focus"><span>تفاصيل اليوم</span><h3>{format(selectedDay,'EEEE، d MMMM',{locale:ar})}</h3>{selectedContent.map(item=><article key={item.id}><header>{canEdit?<select className="lifecycle-select" aria-label={`مرحلة ${item.title}`} disabled={busy===`content-${item.id}`} value={item.status} onChange={event=>onContentStatus(item,event.target.value)}>{Object.entries(CONTENT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select>:<Status meta={CONTENT_STATUS[item.status]}/>}<time>{dateTimeText(item.scheduled_at)}</time></header><h4>{item.title}</h4><p>{clientName(item.client_id)} · {projectName(item.project_id)}</p><footer>{PLATFORM[item.platform]||item.platform} · {CONTENT_TYPE[item.content_type]||item.content_type}</footer></article>)}{!selectedContent.length&&<Empty icon={CalendarDays} title="اليوم هادئ" text="لا يوجد محتوى مجدول في هذا اليوم."/>}</aside></section>}
function TasksView({tasks,projects,users,currentUser,canManage,busy,onUpdate}){const pn=id=>projects.find(item=>Number(item.id)===Number(id))?.name||'مشروع',un=id=>users.find(item=>Number(item.id)===Number(id))?.full_name||(Number(id)===Number(currentUser?.id)?currentUser?.full_name:'غير مسند');if(!tasks.length)return <Empty icon={ClipboardCheck} title="لا توجد مهام مطابقة" text="أضف مهمة من تفاصيل أي مشروع."/>;return <section className="tasks-pipeline">{Object.entries(TASK_STATUS).map(([status,label])=>{const list=tasks.filter(item=>item.status===status);return <section key={status}><header><h3>{label}</h3><span>{list.length}</span></header>{list.map(task=>{const canUpdate=canManage||Number(task.assigned_to)===Number(currentUser?.id);return <article key={task.id} className={task.due_at&&task.status!=='done'&&new Date(task.due_at.replace(' ','T'))<new Date()?'overdue':''}><div><small>{pn(task.project_id)}</small><h4>{task.title}</h4><p>{task.description||'بدون وصف إضافي'}</p></div><footer><span className={`priority ${task.priority}`}>{PRIORITY[task.priority]}</span><span>{un(task.assigned_to)}</span><time><Clock3/>{dateTimeText(task.due_at)}</time>{canUpdate?<select aria-label={`تغيير حالة ${task.title}`} disabled={busy===`task-${task.id}`} value={task.status} onChange={event=>onUpdate(task,event.target.value)}>{Object.entries(TASK_STATUS).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select>:<span className="task-locked">للقراءة فقط · المهمة مسندة لزميل آخر</span>}</footer></article>})}</section>})}</section>}
function ProjectForm({form,setForm,clients,packages,busy,onSubmit}){return <form onSubmit={onSubmit}><span className="dialog-kicker">مشروع جديد</span><h2 id="project-modal-title">ابدأ دورة إنتاج واضحة</h2><div className="form-grid"><label>العميل<select required value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value,client_package_id:''})}><option value="">اختر العميل</option>{clients.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>الباقة المباعة (اختياري)<select value={form.client_package_id} onChange={e=>setForm({...form,client_package_id:e.target.value})}><option value="">بدون ربط</option>{packages.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="wide-field">اسم المشروع<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="مثال: حملة العودة للمدارس"/></label><label>التصنيف<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{Object.entries(CATEGORY).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>يوم الدورة الشهرية<input type="number" min="1" max="31" value={form.monthly_cycle_day} onChange={e=>setForm({...form,monthly_cycle_day:e.target.value})}/></label><label>تاريخ البداية<input type="date" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>موعد التسليم<input type="date" min={form.starts_at||undefined} value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label className="wide-field">ملاحظات<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button className="dialog-submit" disabled={busy==='project'}>{busy==='project'?<RefreshCw className="spin"/>:<Plus/>}{busy==='project'?'جارٍ الإنشاء...':'إنشاء المشروع'}</button></form>}
function TaskForm({form,setForm,users,currentUser,canManage,busy,project,onSubmit}){return <form onSubmit={onSubmit}><span className="dialog-kicker">{project?.name}</span><h2 id="project-modal-title">إضافة مهمة تشغيلية</h2><div className="form-grid"><label className="wide-field">عنوان المهمة<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>الأولوية<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{Object.entries(PRIORITY).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{canManage?<label>مسندة إلى<select value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}><option value="">غير مسندة</option>{users.map(user=><option key={user.id} value={user.id}>{user.full_name}</option>)}</select></label>:<label>مسندة إلى<input value={currentUser?.full_name||'حسابي'} disabled/></label>}<label className="wide-field">موعد التنفيذ<input required type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label className="wide-field">الوصف<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button className="dialog-submit" disabled={busy==='task'}><Plus/> {busy==='task'?'جارٍ الحفظ...':'إضافة المهمة'}</button></form>}
function ContentForm({form,setForm,busy,project,onSubmit}){return <form onSubmit={onSubmit}><span className="dialog-kicker">{project?.name}</span><h2 id="project-modal-title">إضافة محتوى للتقويم</h2><div className="form-grid"><label className="wide-field">عنوان المحتوى<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>النوع<select value={form.content_type} onChange={e=>setForm({...form,content_type:e.target.value})}>{Object.entries(CONTENT_TYPE).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>المنصة<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}>{Object.entries(PLATFORM).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>الحالة<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(CONTENT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select></label><label>موعد النشر<input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></label><label className="wide-field">النص / Caption<textarea rows="5" value={form.caption} onChange={e=>setForm({...form,caption:e.target.value})}/></label></div><button className="dialog-submit" disabled={busy==='content'}><Plus/> {busy==='content'?'جارٍ الحفظ...':'إضافة المحتوى'}</button></form>}
function ProjectDetail({project,clientName,tasks,content,userName,canManage,busy,onProjectStatus,onContentStatus,onTask,onContent}){if(!project)return null;return <div><span className="dialog-kicker">{CATEGORY[project.category]}</span><div className="detail-head"><div><h2 id="project-modal-title">{project.name}</h2><p>{clientName(project.client_id)} · {dateText(project.starts_at)} — {dateText(project.due_at)}</p></div>{canManage?<label className="lifecycle-control">مرحلة المشروع<select disabled={busy===`project-${project.id}`} value={project.status} onChange={event=>onProjectStatus(project,event.target.value)}>{Object.entries(PROJECT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select></label>:<Status meta={PROJECT_STATUS[project.status]}/>}</div>{project.notes&&<p className="detail-note">{project.notes}</p>}<div className="detail-actions"><button onClick={onTask}><Plus/> مهمة</button>{canManage&&<button onClick={onContent}><Plus/> محتوى</button>}{!canManage&&<small>يمكنك إنشاء وتحديث مهامك المسندة فقط.</small>}</div><div className="detail-columns"><section><header><h3>المهام</h3><span>{tasks.length}</span></header>{tasks.map(task=><article key={task.id}><div><strong>{task.title}</strong><span>{userName(task.assigned_to)}</span></div><small>{TASK_STATUS[task.status]} · {dateTimeText(task.due_at)}</small></article>)}{!tasks.length&&<p className="detail-empty">لم تُضف مهام بعد.</p>}</section><section><header><h3>المحتوى</h3><span>{content.length}</span></header>{content.map(item=><article key={item.id}><div><strong>{item.title}</strong>{canManage?<select className="lifecycle-select" aria-label={`مرحلة ${item.title}`} disabled={busy===`content-${item.id}`} value={item.status} onChange={event=>onContentStatus(item,event.target.value)}>{Object.entries(CONTENT_STATUS).map(([value,meta])=><option value={value} key={value}>{meta[0]}</option>)}</select>:<Status meta={CONTENT_STATUS[item.status]}/>}</div><small>{PLATFORM[item.platform]||item.platform} · {dateTimeText(item.scheduled_at)}</small></article>)}{!content.length&&<p className="detail-empty">لم يُضف محتوى بعد.</p>}</section></div></div>}
