import { useCallback, useEffect, useId, useMemo, useRef, useState } from 'react';
import { BarChart3, CalendarRange, Download, FileWarning, Plus, Printer, ReceiptText, Search, Share2, ShieldCheck, TrendingUp, Video, X } from 'lucide-react';
import { supabase } from '../supabaseClient';
import useChangeSync from '../hooks/useChangeSync';
import ERPPageHero from './ERPPageHero';
import { socialAmountToCents } from '../lib/socialProfitMath';
import './ERPSocialProfits.css';

const money = new Intl.NumberFormat('ar-EG', { style: 'currency', currency: 'EGP', minimumFractionDigits: 2, maximumFractionDigits: 2 });
const formatMoney = value => money.format(Number(value || 0));
const months = ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];
const cairoToday = () => new Date().toLocaleDateString('en-CA', { timeZone: 'Africa/Cairo' });
const cairoYear = () => Number(new Intl.DateTimeFormat('en', { year: 'numeric', timeZone: 'Africa/Cairo' }).format(new Date()));
const formatDate = value => new Intl.DateTimeFormat('ar-EG', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Africa/Cairo' }).format(new Date(`${value}T12:00:00+02:00`));

const Dialog = ({ title, description, onClose, children }) => {
  const panelRef = useRef(null); const closeRef = useRef(onClose); const returnFocusRef = useRef(typeof document !== 'undefined' ? document.activeElement : null);
  const titleId = useId(); const descriptionId = useId();
  useEffect(() => { closeRef.current = onClose; }, [onClose]);
  useEffect(() => { const panel = panelRef.current; const returnFocus = returnFocusRef.current; const background = [...document.querySelectorAll('.erp-sidebar,.erp-mobile-header,.erp-bottom-nav,.social-profits-page > :not(.social-dialog-backdrop)')]; const previous = background.map(element => ({ element, inert: element.inert, hidden: element.getAttribute('aria-hidden') })); background.forEach(element => { element.inert = true; element.setAttribute('aria-hidden','true'); }); const focusable = () => [...panel.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[href]')].filter(element => element.offsetParent !== null); const keydown = event => { if(event.key === 'Escape'){event.preventDefault();closeRef.current();return;} if(event.key !== 'Tab')return;const items=focusable();if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&(document.activeElement===first||!panel.contains(document.activeElement))){event.preventDefault();last.focus();}else if(!event.shiftKey&&(document.activeElement===last||!panel.contains(document.activeElement))){event.preventDefault();first.focus();} }; document.addEventListener('keydown',keydown);focusable()[0]?.focus();return()=>{document.removeEventListener('keydown',keydown);previous.forEach(({element,inert,hidden})=>{element.inert=inert;if(hidden===null)element.removeAttribute('aria-hidden');else element.setAttribute('aria-hidden',hidden);});requestAnimationFrame(()=>returnFocus?.focus?.());}; },[]);
  return <div className="social-dialog-backdrop" onMouseDown={event => event.target===event.currentTarget&&onClose()}><section className="social-dialog" role="dialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={description ? descriptionId : undefined} ref={panelRef}><header><div><h2 id={titleId}>{title}</h2>{description&&<p id={descriptionId}>{description}</p>}</div><button type="button" onClick={onClose} aria-label="إغلاق"><X /></button></header>{children}</section></div>;
};

const EntryForm = ({ year, onClose, onSaved }) => {
  const [form,setForm]=useState({platform:'youtube',amount:'',receipt_date:cairoToday(),earning_year:year,earning_month:new Date().getMonth()+1,channel_name:'',payout_reference:'',note:''});const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const amountRef=useRef(null);const amountErrorId=useId();const amountInvalid=error==='أدخل مبلغًا من 0.01 جنيه وبدقة منزلتين بحد أقصى.';
  const submit=async event=>{event.preventDefault();if(socialAmountToCents(form.amount)===null){setError('أدخل مبلغًا من 0.01 جنيه وبدقة منزلتين بحد أقصى.');requestAnimationFrame(()=>amountRef.current?.focus());return;}setSaving(true);setError('');const {error:requestError}=await supabase.request('/social-profits',{method:'POST',body:JSON.stringify(form)});setSaving(false);if(requestError)return setError(requestError.message);onSaved();};
  return <form className="social-form" onSubmit={submit}><fieldset className="social-platform-fieldset"><legend>المنصة المستلمة منها الدفعة</legend><div className="social-platform-pick"><button type="button" aria-pressed={form.platform==='youtube'} className={form.platform==='youtube'?'active youtube':''} onClick={()=>setForm({...form,platform:'youtube'})}><Video /> يوتيوب</button><button type="button" aria-pressed={form.platform==='facebook'} className={form.platform==='facebook'?'active facebook':''} onClick={()=>setForm({...form,platform:'facebook'})}><Share2 /> فيسبوك</button></div></fieldset><div className="social-form-grid"><label>قيمة الإيراد<input ref={amountRef} required inputMode="decimal" placeholder="0.00" value={form.amount} aria-invalid={amountInvalid} aria-describedby={amountInvalid?amountErrorId:undefined} onChange={event=>{setForm({...form,amount:event.target.value});if(amountInvalid)setError('');}}/>{amountInvalid&&<small id={amountErrorId} className="social-field-error">استخدم رقمًا موجبًا بمنزلتين عشريتين بحد أقصى، مثل 123.45.</small>}</label><label>تاريخ الاستلام<input required type="date" value={form.receipt_date} onChange={event=>setForm({...form,receipt_date:event.target.value})}/></label></div><div className="social-form-grid"><label>سنة الاستحقاق<input required type="number" min="2000" max="2100" value={form.earning_year} onChange={event=>setForm({...form,earning_year:Number(event.target.value)})}/></label><label>شهر الاستحقاق<select value={form.earning_month} onChange={event=>setForm({...form,earning_month:Number(event.target.value)})}>{months.map((month,index)=><option key={month} value={index+1}>{month}</option>)}</select></label></div><label>اسم القناة أو الصفحة<input required maxLength="180" value={form.channel_name} onChange={event=>setForm({...form,channel_name:event.target.value})} placeholder="مثال: MT Agency Studio"/></label><label>معرّف الدفعة / المرجع<input maxLength="140" value={form.payout_reference} onChange={event=>setForm({...form,payout_reference:event.target.value})}/></label><label>ملاحظات<textarea rows="3" value={form.note} onChange={event=>setForm({...form,note:event.target.value})}/></label>{error&&!amountInvalid&&<p className="social-error" role="alert">{error}</p>}<footer><button type="button" className="social-btn ghost" onClick={onClose}>إلغاء</button><button className="social-btn primary" disabled={saving}>{saving?'جارٍ الحفظ...':'حفظ الإيراد'}</button></footer></form>;
};

const VoidForm=({entry,onClose,onSaved})=>{const[reason,setReason]=useState('');const[error,setError]=useState('');const[saving,setSaving]=useState(false);const submit=async event=>{event.preventDefault();if(reason.trim().length<3)return setError('اكتب سبب الإبطال بوضوح.');setSaving(true);const{error:requestError}=await supabase.request(`/social-profits/${entry.id}/void`,{method:'POST',body:JSON.stringify({reason:reason.trim()})});setSaving(false);if(requestError)return setError(requestError.message);onSaved();};return <form className="social-form" onSubmit={submit}><div className="social-void-summary"><span className={`social-platform ${entry.platform}`}>{entry.platform==='youtube'?'يوتيوب':'فيسبوك'}</span><div><strong>{entry.channel_name}</strong><small>{months[entry.earning_month-1]} {entry.earning_year}</small></div><b>{formatMoney(entry.amount)}</b></div><div className="social-warning"><FileWarning/><p>سيخرج هذا الإيراد من كل الإجماليات والتقارير النشطة، مع بقاء القيد وسبب الإبطال في السجل الدائم.</p></div><label>سبب الإبطال<input required minLength="3" maxLength="500" value={reason} onChange={event=>setReason(event.target.value)} placeholder="مثال: دفعة مكررة"/></label>{error&&<p className="social-error" role="alert">{error}</p>}<footer><button type="button" className="social-btn ghost" onClick={onClose}>رجوع</button><button className="social-btn danger" disabled={saving}>{saving?'جارٍ الإبطال...':'إبطال القيد'}</button></footer></form>};

const ERPSocialProfits=()=>{const[year,setYear]=useState(cairoYear());const[platform,setPlatform]=useState('all');const[status,setStatus]=useState('all');const[search,setSearch]=useState('');const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[modal,setModal]=useState(null);const[voidTarget,setVoidTarget]=useState(null);
  const fetchData=useCallback(async()=>{setLoading(true);const params=new URLSearchParams({year:String(year),platform,status,q:search});const{data:response,error:requestError}=await supabase.request(`/social-profits?${params}`,{method:'GET'});if(requestError)setError(requestError.message);else{setData(response);setError('');}setLoading(false);},[year,platform,status,search]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{fetchData();},[fetchData]);useChangeSync(useCallback(topics=>{if(topics.includes('social_profits'))fetchData();},[fetchData]));const refresh=()=>{setModal(null);setVoidTarget(null);fetchData();};
  const chartData=useMemo(()=>(data?.months||[]).map(row=>({name:months[row.month-1],youtube:Number(row.youtube),facebook:Number(row.facebook),total:Number(row.total)})),[data]);
  const maxMonthly=useMemo(()=>Math.max(1,...chartData.map(row=>row.total)),[chartData]);
  const peakMonth=useMemo(()=>chartData.reduce((peak,row)=>row.total>peak.total?row:peak,{total:-1}),[chartData]);
  const exportCsv=()=>{const headers=['المنصة','القيمة EGP','تاريخ الاستلام','فترة الاستحقاق','القناة/الصفحة','مرجع الدفعة','الحالة','بواسطة','سبب الإبطال'];const escape=value=>`"${String(value??'').replaceAll('"','""')}"`;const rows=(data?.entries||[]).map(entry=>[entry.platform==='youtube'?'يوتيوب':'فيسبوك',entry.amount,entry.receipt_date,`${entry.earning_year}-${String(entry.earning_month).padStart(2,'0')}`,entry.channel_name,entry.payout_reference,entry.status==='active'?'نشط':'مُبطل',entry.creator_name,entry.void_reason].map(escape).join(','));const blob=new Blob([`\uFEFF${headers.join(',')}\r\n${rows.join('\r\n')}`],{type:'text/csv;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`social-profits-${year}.csv`;link.click();URL.revokeObjectURL(link.href);};
  if(loading&&!data)return <main className="social-profits-page"><div className="social-loading"><TrendingUp/><span>جارٍ إعداد التقرير السنوي...</span></div></main>;
  return <main className="social-profits-page"><ERPPageHero icon={TrendingUp} eyebrow="سجل إيرادات المنصات" title="أرباح السوشيال" description="سجل إجمالي دخل يوتيوب وفيسبوك لإعداد الفحص السنوي؛ لا يحتوي مصروفات ولا يمثل صافي الربح." actions={<><button data-variant="primary" onClick={()=>setModal('add')}><Plus/> تسجيل إيراد</button><button onClick={exportCsv}><Download/> تصدير CSV</button><button onClick={()=>window.print()}><Printer/> طباعة التقرير</button></>}/>{error&&<div className="social-alert" role="alert">{error}<button onClick={fetchData}>إعادة المحاولة</button></div>}
    <section className="social-year-bar"><div><CalendarRange/><span>السنة الضريبية</span><select value={year} onChange={event=>setYear(Number(event.target.value))}>{(data?.available_years||[year]).map(item=><option key={item}>{item}</option>)}</select></div><p><ShieldCheck/> الإجماليات تشمل القيود النشطة فقط، وتُعرض القيود المُبطلة للتدقيق.</p></section>
    <section className="social-kpis"><article className="total"><span><BarChart3/> إجمالي إيرادات السنة</span><strong>{formatMoney(data?.summary.total)}</strong><small>{year} · إجمالي دخل قبل أي مصروفات</small></article><article className="youtube"><span><Video/> إيرادات يوتيوب</span><strong>{formatMoney(data?.summary.youtube)}</strong></article><article className="facebook"><span><Share2/> إيرادات فيسبوك</span><strong>{formatMoney(data?.summary.facebook)}</strong></article><article><span><ReceiptText/> الدفعات النشطة</span><strong>{data?.summary.active_count||0}</strong></article></section>
    <section className="social-timeline"><header><div><span>المحور السنوي</span><h2>مسار الدخل من يناير إلى ديسمبر</h2></div><div className="social-platform-legend"><span><i className="yt"/> يوتيوب</span><span><i className="fb"/> فيسبوك</span><strong>{formatMoney(data?.summary.total)}</strong></div></header><p className="social-rail-cue">مرّر أفقيًا لاستكشاف أشهر السنة ←</p><div className="social-year-rail" aria-label={`المسار السنوي لإيرادات ${year}`}>{chartData.map((row,index)=>{const youtubeHeight=Math.max(row.youtube>0?4:0,(row.youtube/maxMonthly)*100);const facebookHeight=Math.max(row.facebook>0?4:0,(row.facebook/maxMonthly)*100);return <article key={row.name} className={row.name===peakMonth.name?'peak':''} aria-label={`${row.name}: يوتيوب ${formatMoney(row.youtube)}، فيسبوك ${formatMoney(row.facebook)}، الإجمالي ${formatMoney(row.total)}`}><div className="social-rail-total"><strong>{row.total?formatMoney(row.total):'—'}</strong>{row.name===peakMonth.name&&<small>ذروة السنة</small>}</div><div className="social-rail-bars" aria-hidden="true"><i className="youtube" style={{height:`${youtubeHeight}%`}}/><i className="facebook" style={{height:`${facebookHeight}%`}}/></div><div className="social-rail-node"><span>{String(index+1).padStart(2,'0')}</span></div><h3>{row.name}</h3></article>})}</div><div className="social-months" aria-label="تفصيل الأشهر ذات الإيراد">{chartData.filter(row=>row.total>0).map(row=><article key={row.name}><span>{row.name}</span><strong>{formatMoney(row.total)}</strong><small><i className="yt"/> {formatMoney(row.youtube)} <i className="fb"/> {formatMoney(row.facebook)}</small></article>)}</div></section>
    <aside className="social-info"><ShieldCheck/><p>هذه الصفحة للإيرادات فقط ولا تحتوي على مصروفات ولا تمثل صافي الربح أو الإقرار الضريبي النهائي.</p></aside>
      <section className="social-ledger"><header><div><span>السجل الدائم</span><h2>دفعات المنصات</h2></div><div className="social-filters"><label>المنصة<select value={platform} onChange={event=>setPlatform(event.target.value)}><option value="all">الكل</option><option value="youtube">يوتيوب</option><option value="facebook">فيسبوك</option></select></label><label>الحالة<select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">الكل</option><option value="active">نشط</option><option value="voided">مُبطل</option></select></label><label className="search"><Search/><input aria-label="بحث في السجل" value={search} onChange={event=>setSearch(event.target.value)} placeholder="قناة أو مرجع"/></label></div></header>{data?.entries.length?<><div className="social-table-wrap"><table><thead><tr><th>الاستلام</th><th>المنصة</th><th>فترة الربح</th><th>القناة / الصفحة</th><th>المرجع</th><th>القيمة</th><th>الحالة</th><th>بواسطة</th><th></th></tr></thead><tbody>{data.entries.map(entry=><tr key={entry.id} className={entry.status==='voided'?'voided':''}><td><time dateTime={entry.receipt_date}>{formatDate(entry.receipt_date)}</time></td><td><span className={`social-platform ${entry.platform}`}>{entry.platform==='youtube'?'يوتيوب':'فيسبوك'}</span></td><td>{months[entry.earning_month-1]} {entry.earning_year}</td><td><strong>{entry.channel_name}</strong><small>{entry.note}</small></td><td>{entry.payout_reference||'—'}</td><td className="amount">{formatMoney(entry.amount)}</td><td><span className={`social-status ${entry.status}`}>{entry.status==='active'?'نشط':'مُبطل'}</span>{entry.void_reason&&<small>{entry.void_reason}</small>}</td><td>{entry.creator_name}</td><td>{entry.status==='active'&&<button onClick={()=>setVoidTarget(entry)}>إبطال</button>}</td></tr>)}</tbody></table></div><div className="social-ledger-cards">{data.entries.map(entry=><article key={entry.id} className={entry.status==='voided'?'voided':''}><header><span className={`social-platform ${entry.platform}`}>{entry.platform==='youtube'?'يوتيوب':'فيسبوك'}</span><strong>{formatMoney(entry.amount)}</strong><span className={`social-status ${entry.status}`}>{entry.status==='active'?'نشط':'مُبطل'}</span></header><div><h3>{entry.channel_name}</h3><small><time dateTime={entry.receipt_date}>{formatDate(entry.receipt_date)}</time> · {months[entry.earning_month-1]} {entry.earning_year}</small></div><details><summary>التفاصيل والتدقيق</summary><p>المرجع: {entry.payout_reference||'—'}<br/>بواسطة: {entry.creator_name}{entry.void_reason&&<><br/>سبب الإبطال: {entry.void_reason}</>}</p></details>{entry.status==='active'&&<button onClick={()=>setVoidTarget(entry)}>إبطال القيد</button>}</article>)}</div></>:<div className="social-empty"><ReceiptText/><strong>لا توجد دفعات مطابقة.</strong><span>سجّل أول إيراد أو غيّر مرشحات التقرير.</span></div>}</section>
    {modal==='add'&&<Dialog title="تسجيل إيراد منصة" description="يُضاف كسجل دخل إجمالي مستقل وقابل للإبطال فقط." onClose={()=>setModal(null)}><EntryForm year={year} onClose={()=>setModal(null)} onSaved={refresh}/></Dialog>}{voidTarget&&<Dialog title="إبطال قيد إيراد" description="سيبقى القيد محفوظًا لأغراض التدقيق." onClose={()=>setVoidTarget(null)}><VoidForm entry={voidTarget} onClose={()=>setVoidTarget(null)} onSaved={refresh}/></Dialog>}
  </main>};

export default ERPSocialProfits;
