import { useEffect, useRef, useState } from 'react';
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Copy, ImagePlus, Package, Plus, Trash2 } from 'lucide-react';
import { dataClient } from '../dataClient';
import { cairoDateKey, formatBookingDate, formatDateTime12, formatDurationMinutes, formatEGP, formatTime12 } from '../lib/businessFormat';
import { CANCELLATION_TERMS, REGISTRATION_TERMS_VERSION, registrationValidityLabel, isClientBookingDateClosed } from '../lib/registrationPolicy';
import { STUDIO_SUCCESS_MESSAGE, STUDIO_TRANSFER_ACCOUNT, sortedStudioBookings, studioSelectedMinutes, validateStudioBookings, validateStudioProof } from '../lib/studioBookingPolicy';
import { safeUiError } from '../lib/uiError';
import './ClientStudioBooking.css';
const stepLabels = ['اختيار الباقة', 'مواعيد التصوير', 'التحويل وإرسال الطلب'];
export default function ClientStudioBooking({ onClose, onRequests }) {
  const [services, setServices] = useState([]); const [loading, setLoading] = useState(true); const [step, setStep] = useState(0); const [serviceId, setServiceId] = useState('');
  const [bookings, setBookings] = useState([]); const [date, setDate] = useState(''); const [duration, setDuration] = useState(60); const [slots, setSlots] = useState([]); const [slotKey, setSlotKey] = useState(''); const [slotBusy, setSlotBusy] = useState(false);
  const [proof, setProof] = useState(null); const [preview, setPreview] = useState(''); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(null); const [copied, setCopied] = useState(false);
  const retry = useRef(null); const fileInput = useRef(null); const service = services.find(s => String(s.id) === serviceId); const totalMinutes = studioSelectedMinutes(bookings); const deposit = Number(service?.deposit_amount || 0);
  const loadCatalog = async () => { const result = await dataClient.request('/registration/catalog'); if (result.error) setError(safeUiError(result.error, 'تعذر تحميل الباقات. أعد المحاولة.')); else setServices(result.data?.services || []); setLoading(false); return result; };
  useEffect(() => { void loadCatalog(); }, []); // eslint-disable-line react-hooks/set-state-in-effect -- Initial remote loading state.
  useEffect(() => { if (!proof) return; const objectUrl = URL.createObjectURL(proof); setPreview(objectUrl); return () => URL.revokeObjectURL(objectUrl); }, [proof]); // eslint-disable-line react-hooks/set-state-in-effect
  useEffect(() => {
    let active = true; setSlots([]); setSlotKey(''); setSlotBusy(false); // eslint-disable-line react-hooks/set-state-in-effect
    if (!serviceId || !date || isClientBookingDateClosed(date)) return () => { active = false; };
    setSlotBusy(true);
    void dataClient.request(`/registration/availability?service_id=${serviceId}&date=${date}&duration_minutes=${duration}`).then(result => { if (!active) return; setSlotBusy(false); if (result.error) setError(safeUiError(result.error, 'تعذر تحميل المواعيد.')); else setSlots(result.data?.slots || []); });
    return () => { active = false; };
  }, [serviceId, date, duration]);
  const chooseService = value => { setServiceId(value); setConsent(false); setError(''); const next = services.find(s => String(s.id) === value); if (next) setDuration(Math.min(60, Number(next.total_hours) * 60)); };
  const slotId = slot => `${slot.resource_id}-${slot.start_time}-${slot.end_time}`;
  const addAppointment = async () => {
    const chosen = slots.find(s => slotId(s) === slotKey); if (!chosen) { setError('اختر موعدًا متاحًا أولًا.'); return; }
    const candidate = { ...chosen, date, duration_minutes: Number(duration) }; const next = sortedStudioBookings([...bookings, candidate]); const validation = validateStudioBookings(service, next); if (validation) { setError(validation); return; }
    setSlotBusy(true); setError(''); const result = await dataClient.request(`/registration/availability?service_id=${serviceId}&date=${date}&duration_minutes=${duration}`); setSlotBusy(false);
    if (result.error) { setError(safeUiError(result.error, 'تعذر التحقق من الموعد. حاول مجددًا.')); return; }
    setSlots(result.data?.slots || []); if (!result.data?.slots?.some(s => slotId(s) === slotKey)) { setSlotKey(''); setError('هذا الموعد لم يعد متاحًا. اختر موعدًا آخر.'); return; }
    setBookings(next); setSlotKey(''); setConsent(false);
  };
  const nextStep = () => { const validation = step === 0 ? (!service ? 'اختر باقة تصوير.' : '') : validateStudioBookings(service, bookings); if (validation) { setError(validation); return; } setError(''); setStep(step + 1); };
  const changeProof = file => { const validation = validateStudioProof(file); if (validation) { setError(validation); return; } setProof(file); setError(''); };
  const submit = async () => {
    const validation = validateStudioBookings(service, bookings) || validateStudioProof(proof) || (!consent ? 'وافق على سياسة تعديل وإلغاء المواعيد.' : ''); if (validation) { setError(validation); return; }
    if (busy) return; setBusy(true); setError('');
    const payload = { service_id: Number(serviceId), service_terms_fingerprint: service.terms_fingerprint, bookings, terms_accepted: true, terms_version: REGISTRATION_TERMS_VERSION };
    const identity = JSON.stringify(payload); if (!retry.current || retry.current.identity !== identity || retry.current.file !== proof) retry.current = { identity, file: proof, key: crypto.randomUUID() };
    const body = new FormData(); body.append('payload', JSON.stringify({ ...payload, idempotency_key: retry.current.key })); body.append('proof', proof);
    const result = await dataClient.request('/client/studio-booking-requests', { method: 'POST', body }); setBusy(false);
    if (result.error) { setError(safeUiError(result.error, 'تعذر إرسال الطلب. يمكنك المحاولة مجددًا بأمان.')); if (result.error.code === 'service_terms_changed') { await loadCatalog(); setConsent(false); setStep(0); } else if (['booking_conflict', 'insufficient_package_balance', 'booking_outside_package_validity', 'booking_in_past', 'past_booking', 'invalid_booking_date', 'invalid_booking_time'].includes(result.error.code)) setStep(1); return; } setSuccess(result.data);
  };
  if (success) return <section className="studio-wizard studio-success" dir="rtl"><span className="studio-success-icon"><CheckCircle2/></span><span className="studio-eyebrow">طلبك وصل إلينا · #{success.id}</span><h2>خطوة أقرب لجلسة تصويرك</h2><p>{STUDIO_SUCCESS_MESSAGE}</p><div className="studio-review-date"><span>موعد المراجعة المتوقع بتوقيت القاهرة</span><strong>{formatDateTime12(success.review_due_at)}</strong></div><p className="studio-note">المواعيد تصبح مؤكدة بعد مراجعة الإدارة. إيصال التحويل قيد المراجعة.</p><button className="studio-primary" onClick={onRequests}>متابعة طلباتي <ChevronLeft/></button><button className="studio-back" onClick={onClose}>العودة للرئيسية</button></section>;
  return <section className="studio-wizard" dir="rtl"><header className="studio-heading"><div><span className="studio-eyebrow">MULTI TASK · حجز الاستديو</span><h2>احجز موعد تصوير</h2><p>اختر باقتك، رتّب مواعيدك، وأرسل طلبك في 3 خطوات.</p></div><button className="studio-back" onClick={onClose}><ChevronRight/> الرئيسية</button></header>
    <ol className="studio-progress" aria-label="خطوات الحجز">{stepLabels.map((label, index) => <li key={label} className={index === step ? 'is-current' : index < step ? 'is-done' : ''} aria-current={index === step ? 'step' : undefined}><span>{index < step ? <CheckCircle2/> : index + 1}</span><strong>{label}</strong></li>)}</ol>
    {error && <p className="studio-error" role="alert">{error}</p>}
    <div className="studio-layout"><div className="studio-main-panel">
      {step === 0 && <><div className="studio-section-heading"><Package/><div><h3>باقة تناسب خطتك</h3><p>كل التفاصيل أمامك قبل اختيار مواعيدك.</p></div></div>{loading ? <p role="status">جارٍ تحميل الباقات…</p> : !services.length ? <div className="studio-empty"><p>لا توجد باقات متاحة الآن.</p><button onClick={loadCatalog}>إعادة المحاولة</button></div> : <><label className="studio-field">اختر نظام التصوير والباقة<select value={serviceId} onChange={e => chooseService(e.target.value)}><option value="">اختر باقة التصوير</option>{['hourly', 'daily', 'monthly'].map(kind => <optgroup key={kind} label={{ hourly: 'التصوير بالساعة', daily: 'الباقات اليومية', monthly: 'الباقات الشهرية' }[kind]}>{services.filter(s => s.kind === kind).map(s => <option key={s.id} value={s.id}>{s.name} — {formatEGP(s.price)}</option>)}</optgroup>)}</select></label>{service ? <><h3 className="studio-package-name">{service.name}</h3><dl className="studio-package-facts"><div><dt>ساعات التصوير</dt><dd>{formatDurationMinutes(Number(service.total_hours) * 60)}</dd></div><div><dt>صلاحية الباقة</dt><dd>{registrationValidityLabel(service)}</dd></div><div><dt>إجمالي الباقة</dt><dd>{formatEGP(service.price)}</dd></div><div><dt>مقدم الحجز · 50%</dt><dd>{formatEGP(deposit)}</dd></div></dl><p className="studio-note">{service.payment_due_text}</p><div className="studio-policy"><strong>التأجيل والإلغاء</strong><p>{CANCELLATION_TERMS}</p></div></> : <div className="studio-empty"><CalendarDays/><p>ابدأ باختيار باقتك لعرض ساعاتها وصلاحيتها وتفاصيل السداد.</p></div>}</> }</>}
      {step === 1 && <><div className="studio-section-heading"><CalendarDays/><div><h3>رتّب أيام التصوير</h3><p>أضف موعدًا أو أكثر حتى رصيد باقتك. كل الأيام عدا الجمعة، من 12 ظهرًا إلى 10 مساءً.</p></div></div><div className="studio-date-fields"><label className="studio-field">يوم التصوير<input type="date" min={cairoDateKey()} value={date} onChange={e => { setDate(e.target.value); setError(''); }}/></label><label className="studio-field">مدة التصوير<select value={duration} onChange={e => { setDuration(Number(e.target.value)); setError(''); }}>{Array.from({ length: Math.floor(Math.min(600, Number(service?.total_hours || 1) * 60) / 30) }, (_, i) => (i + 1) * 30).map(m => <option key={m} value={m}>{formatDurationMinutes(m)}</option>)}</select></label></div>
      <fieldset className="studio-slots"><legend>المواعيد المتاحة</legend>{slotBusy ? <p role="status">جارٍ التحقق من المواعيد…</p> : !date ? <p>اختر اليوم لعرض المواعيد.</p> : isClientBookingDateClosed(date) ? <p>الجمعة إجازة. اختر يومًا آخر.</p> : !slots.length ? <p>لا توجد مواعيد متاحة بهذه المدة. جرّب يومًا أو مدة أخرى.</p> : <div className="studio-slot-grid">{slots.map(slot => <label key={slotId(slot)} className={slotKey === slotId(slot) ? 'selected' : ''}><input type="radio" name="studio-slot" checked={slotKey === slotId(slot)} onChange={() => setSlotKey(slotId(slot))}/><span>{formatTime12(slot.start_time)} <small>إلى</small> {formatTime12(slot.end_time)}</span></label>)}</div>}</fieldset><button className="studio-add" disabled={!slotKey || slotBusy} onClick={addAppointment}><Plus/> إضافة الموعد للقائمة</button><div className="studio-selected-heading"><h4>مواعيدك المختارة <span>({bookings.length})</span></h4><strong>{formatDurationMinutes(totalMinutes)}</strong></div>{!bookings.length ? <p className="studio-note">لم تضف أي موعد بعد. الاختيارات لا تحجز الاستديو حتى اعتماد الطلب.</p> : <ol className="studio-appointments">{bookings.map((row, index) => <li key={`${row.date}-${row.start_time}-${row.resource_id}`}><span className="studio-date-icon"><CalendarDays/></span><div><strong>{formatBookingDate(row.date)}</strong><p>{formatTime12(row.start_time)} إلى {formatTime12(row.end_time)} <span>· {formatDurationMinutes(row.duration_minutes)}</span></p></div><button aria-label={`حذف الموعد ${index + 1}`} onClick={() => { setBookings(bookings.filter((_, i) => index !== i)); setConsent(false); }}><Trash2/></button></li>)}</ol>}<p className="studio-note">المواعيد مقترحة وتخضع لتأكيد الإتاحة من الإدارة.</p></>}
      {step === 2 && <><div className="studio-section-heading"><ImagePlus/><div><h3>مقدم الحجز وإثبات التحويل</h3><p>حوّل 50% من قيمة الباقة، ثم أرفق صورة التحويل.</p></div></div><div className="studio-transfer"><span>فودافون كاش · حساب التحويل</span><div><strong dir="ltr">{STUDIO_TRANSFER_ACCOUNT}</strong><button onClick={async () => { try { await navigator.clipboard.writeText(STUDIO_TRANSFER_ACCOUNT); setCopied(true); } catch { setError('تعذر النسخ التلقائي. يمكنك نسخ الرقم الظاهر.'); } }}><Copy/>{copied ? 'تم النسخ' : 'نسخ الرقم'}</button></div><p>المبلغ المطلوب تحويله <b>{formatEGP(deposit)}</b></p></div><label className="studio-upload"><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { if (e.target.files?.[0]) changeProof(e.target.files[0]); e.target.value = ''; }}/><ImagePlus/><strong>{proof ? 'استبدال صورة التحويل' : 'أرفق صورة إيصال التحويل'}</strong><span>JPEG أو PNG أو WebP · حتى 5 ميجابايت</span></label>{proof && <div className="studio-proof-preview"><img src={preview} alt="معاينة إيصال التحويل"/><div><strong>{proof.name}</strong><button onClick={() => { setProof(null); setPreview(''); }}><Trash2/> إزالة الصورة</button></div></div>}<p className="studio-note">يُراجع المالك وصول التحويل قبل اعتماد المقدم وإضافته لحسابك.</p><label className="studio-consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)}/><span>أوافق على سياسة المواعيد: {CANCELLATION_TERMS}</span></label></>}
    </div><aside className="studio-summary"><span className="studio-eyebrow">ملخص طلبك</span><h3>{service?.name || 'باقة تصوير جديدة'}</h3><dl><div><dt>قيمة الباقة</dt><dd>{formatEGP(service?.price || 0)}</dd></div><div className="studio-summary-deposit"><dt>مقدم الحجز · 50%</dt><dd>{formatEGP(deposit)}</dd></div><div><dt>باقي التكلفة</dt><dd>{formatEGP(Number(service?.price || 0) - deposit)}</dd></div></dl>{service && <p>{service.payment_due_text}</p>}<div className="studio-hours-summary"><span>ساعات المواعيد المختارة<strong>{formatDurationMinutes(totalMinutes)}</strong></span><span>المتبقي للتخطيط<strong>{formatDurationMinutes(Math.max(0, Number(service?.total_hours || 0) * 60 - totalMinutes))}</strong></span></div><p className="studio-note">تبدأ الصلاحية من أول موعد معتمد. يمكنك استخدام باقي ساعات الباقة لاحقًا خلال صلاحيتها.</p></aside></div>
    <footer className="studio-footer"><span>الخطوة {step + 1} من 3</span><div>{step > 0 && <button className="studio-back" disabled={busy} onClick={() => { setStep(step - 1); setError(''); }}><ChevronRight/> السابق</button>}{step < 2 ? <button className="studio-primary" disabled={loading || !service || slotBusy} onClick={nextStep}>التالي <ChevronLeft/></button> : <button className="studio-primary" disabled={busy || !proof || !consent} onClick={submit}>{busy ? 'جارٍ إرسال الطلب…' : 'إرسال طلب الحجز'}<ChevronLeft/></button>}</div></footer>
  </section>;
}
