import { useEffect, useMemo, useRef, useState } from 'react';
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Copy, ImagePlus, Package, Plus, Trash2 } from 'lucide-react';
import { dataClient } from '../dataClient';
import { formatBookingDate, formatDateTime12, formatDurationMinutes, formatEGP, formatTime12 } from '../lib/businessFormat';
import { CANCELLATION_TERMS, REGISTRATION_TERMS_VERSION, registrationValidityLabel } from '../lib/registrationPolicy';
import { STUDIO_SUCCESS_MESSAGE, STUDIO_TRANSFER_ACCOUNT, studioPurchaseSelection, sortedStudioBookings, studioSelectedMinutes, validateStudioBookings, validateStudioProof } from '../lib/studioBookingPolicy';
import { safeUiError } from '../lib/uiError';
import './ClientStudioBooking.css';
import ClientAvailabilityCalendar from '../components/ClientAvailabilityCalendar';
import { packageBookingMonthWindow, shiftBookingMonth, shiftBookingDate } from '../lib/packageBookingCalendar';
import { earliestClientBookingDate, clientBookingDateError } from '../lib/clientBookingDate';
const stepLabels = ['اختيار الباقة', 'مواعيد التصوير', 'التحويل وإرسال الطلب'];
export default function ClientStudioBooking({ onClose, onRequests, onBookExisting }) {
  const [eligibility, setEligibility] = useState(null);
  const [selectedHours, setSelectedHours] = useState(1);
  const [services, setServices] = useState([]); const [loading, setLoading] = useState(true); const [step, setStep] = useState(0); const [serviceId, setServiceId] = useState('');
  const [bookings, setBookings] = useState([]); const [date, setDate] = useState(''); const [duration, setDuration] = useState(60); const [availability, setAvailability] = useState({ data: null, loading: false, error: '' }); const [availabilityMonth, setAvailabilityMonth] = useState(''); const [revision, setRevision] = useState(0); const [slotKey, setSlotKey] = useState(''); const [slotBusy, setSlotBusy] = useState(false);
  const [proof, setProof] = useState(null); const [preview, setPreview] = useState(''); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(null); const [copied, setCopied] = useState(false);
  const appointmentBusyRef = useRef(false); const retry = useRef(null); const fileInput = useRef(null); const baseService = services.find(s => String(s.id) === serviceId); const service = studioPurchaseSelection(baseService, selectedHours); const daily = service?.kind === 'daily' || service?.package_validity_mode === 'shooting_day'; const totalMinutes = studioSelectedMinutes(bookings); const deposit = Number(service?.deposit_amount || 0);
  const firstDraftDate = sortedStudioBookings(bookings)[0]?.date;
  const draftValidity = useMemo(() => firstDraftDate && service?.kind !== 'hourly' ? { starts_at: firstDraftDate, expires_at: service?.kind === 'daily' || service?.package_validity_mode === 'shooting_day' ? firstDraftDate : shiftBookingDate(firstDraftDate, Math.max(1, Number(service?.validity_days || 1)) - 1) } : null, [firstDraftDate, service]);
  const [earliestDate, setEarliestDate] = useState(earliestClientBookingDate);
  useEffect(() => { const refresh = () => setEarliestDate(earliestClientBookingDate()); const timer = window.setInterval(refresh, 30000); window.addEventListener('focus', refresh); return () => { window.clearInterval(timer); window.removeEventListener('focus', refresh); }; }, []);
  const monthWindow = useMemo(() => packageBookingMonthWindow(draftValidity, availabilityMonth, earliestDate), [draftValidity, availabilityMonth, earliestDate]);
  const slots = availability.data?.days?.find(day => day.date === date)?.slots || [];
  const moveMonth = amount => { if (amount < 0 && !monthWindow.canPrevious || amount > 0 && !monthWindow.canNext) return; setAvailabilityMonth(shiftBookingMonth(monthWindow.month, amount)); setDate(''); setSlotKey(''); setAvailability({ data: null, loading: true, error: '' }); };
  const loadCatalog = async () => { setLoading(true); const eligibilityResult = await dataClient.request('/client/package-eligibility'); if (eligibilityResult.error) { setEligibility(null); setError(safeUiError(eligibilityResult.error, 'تعذر التحقق من باقتك الحالية. أعد المحاولة.')); setLoading(false); return eligibilityResult; } setEligibility(eligibilityResult.data); if (!eligibilityResult.data?.can_purchase) { setLoading(false); return eligibilityResult; } const result = await dataClient.request('/registration/catalog'); if (result.error) setError(safeUiError(result.error, 'تعذر تحميل الباقات. أعد المحاولة.')); else setServices(result.data?.services || []); setLoading(false); return result; };
  useEffect(() => { void loadCatalog(); }, []); // eslint-disable-line react-hooks/set-state-in-effect -- Initial remote loading state.
  useEffect(() => { if (!proof) return; const objectUrl = URL.createObjectURL(proof); setPreview(objectUrl); return () => URL.revokeObjectURL(objectUrl); }, [proof]); // eslint-disable-line react-hooks/set-state-in-effect
  useEffect(() => {
    if (!serviceId || step !== 1 || monthWindow.days < 1) return undefined;
    const controller = new AbortController();
    const timer = window.setTimeout(async () => {
      setAvailability({ data: null, loading: true, error: '' }); setSlotKey('');
      const query = new URLSearchParams({ service_id: serviceId, duration_minutes: String(duration), start_date: monthWindow.startDate, days: String(monthWindow.days) });
      const result = await dataClient.request(`/client/studio-availability?${query}`, { signal: controller.signal });
      if (controller.signal.aborted) return;
      setAvailability(result.error ? { data: null, loading: false, error: safeUiError(result.error, 'تعذر تحميل المواعيد. أعد المحاولة.') } : { data: result.data, loading: false, error: '' });
    }, 150);
    return () => { window.clearTimeout(timer); controller.abort(); };
  }, [serviceId, step, duration, monthWindow.startDate, monthWindow.days, revision]);
  const chooseService = value => { const chosen = services.find(item => String(item.id) === value); setSelectedHours(Math.max(1, Number(chosen?.total_hours || 1))); setServiceId(value); setBookings([]); setDate(''); setSlotKey(''); setAvailabilityMonth(''); setAvailability({ data: null, loading: false, error: '' }); setConsent(false); setError(''); setDuration(chosen?.kind === 'daily' || chosen?.package_validity_mode === 'shooting_day' ? Number(chosen.total_hours) * 60 : 60); };
  const slotId = slot => `${slot.resource_id}-${slot.start_time}-${slot.end_time}`;
  const addAppointment = async () => {
    if (appointmentBusyRef.current || availability.loading) return;
    const dateError = clientBookingDateError(date); if (dateError) { setError(dateError); return; }
    if (bookings.some(row => row.date === date)) { setError('يمكن حجز فترة واحدة متصلة فقط في اليوم. احذف الموعد السابق قبل تغيير الفترة.'); return; }
    const chosen = slots.find(s => slotId(s) === slotKey); if (!chosen) { setError('اختر موعدًا متاحًا أولًا.'); return; }
    const candidate = { ...chosen, date, duration_minutes: Number(duration) }; const next = sortedStudioBookings([...bookings, candidate]); const validation = validateStudioBookings(service, next, true, false); if (validation) { setError(validation); return; }
    appointmentBusyRef.current = true; setSlotBusy(true); setError(''); const result = await dataClient.request(`/client/studio-availability?service_id=${serviceId}&start_date=${date}&days=1&duration_minutes=${duration}`); appointmentBusyRef.current = false; setSlotBusy(false);
    if (result.error) { setError(safeUiError(result.error, 'تعذر التحقق من الموعد. حاول مجددًا.')); return; }
    const checkedDay = result.data?.days?.[0]; if (!checkedDay?.available || !checkedDay.slots?.some(s => slotId(s) === slotKey)) { setSlotKey(''); setRevision(value => value + 1); setError('هذا الموعد لم يعد متاحًا. اختر موعدًا آخر.'); return; }
    setBookings(next); if (!daily) { const remaining = Math.round(Number(service.total_hours) * 60) - studioSelectedMinutes(next); if (remaining >= 60) setDuration(current => Math.min(current, remaining)); } setSlotKey(''); setConsent(false);
  };
  const nextStep = () => { const validation = step === 0 ? (!service ? 'اختر باقة تصوير.' : '') : validateStudioBookings(service, bookings); if (validation) { setError(validation); return; } setError(''); setStep(step + 1); };
  const changeProof = file => { const validation = validateStudioProof(file); if (validation) { setError(validation); return; } setProof(file); setError(''); };
  const submit = async () => {
    const validation = validateStudioBookings(service, bookings) || validateStudioProof(proof) || (!consent ? 'وافق على سياسة تعديل وإلغاء المواعيد.' : ''); if (validation) { setError(validation); return; }
    if (busy) return; setBusy(true); setError('');
    const payload = { service_id: Number(serviceId), ...(baseService?.kind === 'hourly' ? { selected_hours: Number(selectedHours) } : {}), service_terms_fingerprint: service.terms_fingerprint, bookings, terms_accepted: true, terms_version: REGISTRATION_TERMS_VERSION };
    const identity = JSON.stringify(payload); if (!retry.current || retry.current.identity !== identity || retry.current.file !== proof) retry.current = { identity, file: proof, key: crypto.randomUUID() };
    const body = new FormData(); body.append('payload', JSON.stringify({ ...payload, idempotency_key: retry.current.key })); body.append('proof', proof);
    const result = await dataClient.request('/client/studio-booking-requests', { method: 'POST', body }); setBusy(false);
    if (result.error) { setError(safeUiError(result.error, 'تعذر إرسال الطلب. يمكنك المحاولة مجددًا بأمان.')); if (result.error.code === 'client_active_package') { await loadCatalog(); } else if (result.error.code === 'service_terms_changed') { await loadCatalog(); setConsent(false); setStep(0); } else if (['booking_conflict', 'insufficient_package_balance', 'booking_outside_package_validity', 'booking_in_past', 'past_booking', 'invalid_booking_date', 'invalid_booking_time', 'client_day_already_booked', 'same_day_booking_not_allowed', 'client_booking_before_tomorrow'].includes(result.error.code)) { setStep(1); setSlotKey(''); setRevision(value => value + 1); }; return; } setSuccess(result.data);
  };
  if (success) return <section className="studio-wizard studio-success" dir="rtl"><span className="studio-success-icon"><CheckCircle2/></span><span className="studio-eyebrow">طلبك وصل إلينا · #{success.id}</span><h2>خطوة أقرب لجلسة تصويرك</h2><p>{STUDIO_SUCCESS_MESSAGE}</p><div className="studio-review-date"><span>موعد المراجعة المتوقع بتوقيت القاهرة</span><strong>{formatDateTime12(success.review_due_at)}</strong></div><p className="studio-note">المواعيد تصبح مؤكدة بعد مراجعة الإدارة. إيصال التحويل قيد المراجعة.</p><button className="studio-primary" onClick={onRequests}>متابعة طلباتي <ChevronLeft/></button><button className="studio-back" onClick={onClose}>العودة للرئيسية</button></section>;
  if (loading || !eligibility) return <section className="studio-wizard" dir="rtl">{loading ? <p role="status">جارٍ التحقق من باقتك الحالية…</p> : <><p role="alert">{error}</p><button className="studio-primary" onClick={loadCatalog}>إعادة المحاولة</button></>}</section>;
  if (!eligibility.can_purchase) return <section className="studio-wizard" dir="rtl"><h2>احجز من باقتك الحالية</h2><p>{eligibility.message}</p><button className="studio-primary" onClick={onBookExisting}>حجز موعد تصوير جديد</button><button className="studio-back" onClick={onClose}>العودة للرئيسية</button></section>;
  return <section className="studio-wizard" dir="rtl"><header className="studio-heading"><div><span className="studio-eyebrow">MULTI TASK · حجز الاستديو</span><h2>حجز باقة تصوير جديدة</h2><p>اختر باقتك، رتّب مواعيدك، وأرسل طلبك في 3 خطوات.</p></div><button className="studio-back" onClick={onClose}><ChevronRight/> الرئيسية</button></header>
    <ol className="studio-progress" aria-label="خطوات الحجز">{stepLabels.map((label, index) => <li key={label} className={index === step ? 'is-current' : index < step ? 'is-done' : ''} aria-current={index === step ? 'step' : undefined}><span>{index < step ? <CheckCircle2/> : index + 1}</span><strong>{label}</strong></li>)}</ol>
    {error && <p className="studio-error" role="alert">{error}</p>}
    <div className="studio-layout"><div className="studio-main-panel">
      {step === 0 && <><div className="studio-section-heading"><Package/><div><h3>باقة تناسب خطتك</h3><p>كل التفاصيل أمامك قبل اختيار مواعيدك.</p></div></div>{loading ? <p role="status">جارٍ تحميل الباقات…</p> : !services.length ? <div className="studio-empty"><p>لا توجد باقات متاحة الآن.</p><button onClick={loadCatalog}>إعادة المحاولة</button></div> : <><label className="studio-field">اختر نظام التصوير والباقة<select value={serviceId} onChange={e => chooseService(e.target.value)}><option value="">اختر باقة التصوير</option>{['hourly', 'daily', 'monthly'].map(kind => <optgroup key={kind} label={{ hourly: 'التصوير بالساعة', daily: 'الباقات اليومية', monthly: 'الباقات الشهرية' }[kind]}>{services.filter(s => s.kind === kind).map(s => <option key={s.id} value={s.id}>{s.name} — {formatEGP(s.price)}</option>)}</optgroup>)}</select></label>{baseService?.kind === 'hourly' && <label className="studio-field">عدد ساعات التصوير المطلوبة<input type="number" min="1" max="300" step="1" value={selectedHours} onChange={event => { setSelectedHours(event.target.value); setBookings([]); setDate(''); setSlotKey(''); setDuration(60); setConsent(false); }}/><small>يمكن تقسيمها على أيام مختلفة؛ ساعة متصلة على الأقل لكل يوم. السعر يتحدّد حسب عدد الساعات.</small></label>}{service ? <><h3 className="studio-package-name">{service.name}</h3><dl className="studio-package-facts"><div><dt>ساعات التصوير</dt><dd>{formatDurationMinutes(Number(service.total_hours) * 60)}</dd></div><div><dt>صلاحية الباقة</dt><dd>{registrationValidityLabel(service)}</dd></div><div><dt>إجمالي الباقة</dt><dd>{formatEGP(service.price)}</dd></div><div><dt>مقدم الحجز · 50%</dt><dd>{formatEGP(deposit)}</dd></div></dl><p className="studio-note">{service.payment_due_text}</p><div className="studio-policy"><strong>التأجيل والإلغاء</strong><p>{CANCELLATION_TERMS}</p></div></> : <div className="studio-empty"><CalendarDays/><p>ابدأ باختيار باقتك لعرض ساعاتها وصلاحيتها وتفاصيل السداد.</p></div>}</> }</>}
      {step === 1 && <><div className="studio-section-heading"><CalendarDays/><div><h3>رتّب أيام التصوير</h3><p>{daily ? 'احجز ساعات الباقة كاملة في جلسة واحدة متصلة؛ الصلاحية في يوم التصوير فقط.' : service?.kind === 'hourly' ? 'وزّع كل الساعات على أيام تختارها، بحد أدنى ساعة متصلة في اليوم. يمكن اختيار تواريخ بعد شهر؛ ساعات كل موعد صالحة في يومه فقط.' : 'اختر موعدًا أو أكثر في أيام مختلفة، ضمن ساعات وصلاحية باقتك.'} الحجز من الغد، عدا الجمعة، من 12 ظهرًا إلى 10 مساءً.</p></div></div><div className="studio-date-fields studio-calendar-duration"><label className="studio-field">مدة الجلسة المتصلة<select disabled={slotBusy || daily} value={duration} onChange={e => { setDuration(Number(e.target.value)); setSlotKey(''); setAvailability({ data: null, loading: true, error: '' }); setError(''); }}>{(daily ? [Number(service.total_hours) * 60] : Array.from({ length: Math.max(0, Math.floor(Math.min(600, Number(service?.total_hours || 1) * 60 - totalMinutes) / 30) - 1) }, (_, i) => (i + 2) * 30)).map(m => <option key={m} value={m}>{formatDurationMinutes(m)}</option>)}</select></label></div>
      <ClientAvailabilityCalendar monthWindow={monthWindow} data={availability.data} loading={availability.loading} error={availability.error} onRetry={() => setRevision(value => value + 1)} onMonthChange={moveMonth} selectedDate={date} onDateChange={value => { setDate(value); setSlotKey(''); setError(''); }} selectedSlot={slots.find(slot => slotId(slot) === slotKey)} onSlotChange={slot => setSlotKey(slotId(slot))} durationMinutes={Number(duration)} disabledDates={bookings.map(row => row.date)} disabled={slotBusy || totalMinutes >= Number(service?.total_hours || 0) * 60} validityLabel={service?.kind === 'hourly' ? 'كل موعد له رصيد ساعات وصلاحية في يومه فقط · يمكن اختيار أي شهر قادم' : draftValidity ? `ضمن صلاحية الباقة حتى ${formatBookingDate(draftValidity.expires_at)}` : 'الحجز يبدأ من الغد · الصلاحية تبدأ من أول موعد مختار'}/><button className="studio-add" disabled={!slotKey || slotBusy || availability.loading || bookings.some(row => row.date === date)} onClick={addAppointment}><Plus/> إضافة الموعد للقائمة</button><div className="studio-selected-heading"><h4>مواعيدك المختارة <span>({bookings.length})</span></h4><strong>{formatDurationMinutes(totalMinutes)}</strong></div>{!bookings.length ? <p className="studio-note">لم تضف أي موعد بعد. الاختيارات لا تحجز الاستديو حتى اعتماد الطلب.</p> : <ol className="studio-appointments">{bookings.map((row, index) => <li key={`${row.date}-${row.start_time}-${row.resource_id}`}><span className="studio-date-icon"><CalendarDays/></span><div><strong>{formatBookingDate(row.date)}</strong><p>{formatTime12(row.start_time)} إلى {formatTime12(row.end_time)} <span>· {formatDurationMinutes(row.duration_minutes)}</span></p></div><button disabled={slotBusy} aria-label={`حذف الموعد ${index + 1}`} onClick={() => { setBookings(bookings.filter((_, i) => index !== i)); setConsent(false); }}><Trash2/></button></li>)}</ol>}<p className="studio-note">المواعيد مقترحة وتخضع لتأكيد الإتاحة من الإدارة.</p></>}
      {step === 2 && <><div className="studio-section-heading"><ImagePlus/><div><h3>مقدم الحجز وإثبات التحويل</h3><p>حوّل 50% من قيمة الباقة، ثم أرفق صورة التحويل.</p></div></div><div className="studio-transfer"><span>فودافون كاش · حساب التحويل</span><div><strong dir="ltr">{STUDIO_TRANSFER_ACCOUNT}</strong><button onClick={async () => { try { await navigator.clipboard.writeText(STUDIO_TRANSFER_ACCOUNT); setCopied(true); } catch { setError('تعذر النسخ التلقائي. يمكنك نسخ الرقم الظاهر.'); } }}><Copy/>{copied ? 'تم النسخ' : 'نسخ الرقم'}</button></div><p>المبلغ المطلوب تحويله <b>{formatEGP(deposit)}</b></p></div><label className="studio-upload"><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" onChange={e => { if (e.target.files?.[0]) changeProof(e.target.files[0]); e.target.value = ''; }}/><ImagePlus/><strong>{proof ? 'استبدال صورة التحويل' : 'أرفق صورة إيصال التحويل'}</strong><span>JPEG أو PNG أو WebP · حتى 5 ميجابايت</span></label>{proof && <div className="studio-proof-preview"><img src={preview} alt="معاينة إيصال التحويل"/><div><strong>{proof.name}</strong><button onClick={() => { setProof(null); setPreview(''); }}><Trash2/> إزالة الصورة</button></div></div>}<p className="studio-note">يُراجع المالك وصول التحويل قبل اعتماد المقدم وإضافته لحسابك.</p><label className="studio-consent"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)}/><span>أوافق على سياسة المواعيد: {CANCELLATION_TERMS}</span></label></>}
    </div><aside className="studio-summary"><span className="studio-eyebrow">ملخص طلبك</span><h3>{service?.name || 'باقة تصوير جديدة'}</h3><dl><div><dt>قيمة الباقة</dt><dd>{formatEGP(service?.price || 0)}</dd></div><div className="studio-summary-deposit"><dt>مقدم الحجز · 50%</dt><dd>{formatEGP(deposit)}</dd></div><div><dt>باقي التكلفة</dt><dd>{formatEGP(Number(service?.price || 0) - deposit)}</dd></div></dl>{service && <p>{service.payment_due_text}</p>}<div className="studio-hours-summary"><span>ساعات المواعيد المختارة<strong>{formatDurationMinutes(totalMinutes)}</strong></span><span>المتبقي للتخطيط<strong>{formatDurationMinutes(Math.max(0, Number(service?.total_hours || 0) * 60 - totalMinutes))}</strong></span></div><p className="studio-note">{daily ? 'كل ساعات الباقة تُحجز في يوم تصوير واحد وتنتهي صلاحيتها في نفس اليوم.' : service?.kind === 'hourly' ? 'طلب واحد لكل المواعيد. يُخصص لكل يوم رصيد ساعاته وسعره، وتنتهي صلاحيته في نفس اليوم.' : 'تبدأ الصلاحية من أول موعد معتمد. يمكنك استخدام باقي ساعات الباقة لاحقًا خلال صلاحيتها.'}</p></aside></div>
    <footer className="studio-footer"><span>الخطوة {step + 1} من 3</span><div>{step > 0 && <button className="studio-back" disabled={busy || slotBusy} onClick={() => { setStep(step - 1); setError(''); }}><ChevronRight/> السابق</button>}{step < 2 ? <button className="studio-primary" disabled={loading || !service || slotBusy} onClick={nextStep}>التالي <ChevronLeft/></button> : <button className="studio-primary" disabled={busy || !proof || !consent} onClick={submit}>{busy ? 'جارٍ إرسال الطلب…' : 'إرسال طلب الحجز'}<ChevronLeft/></button>}</div></footer>
  </section>;
}
