import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, Check, Clock3, Eye, Inbox, Package, RefreshCw, ShieldCheck, X } from 'lucide-react';
import { dataClient } from '../dataClient';
import { formatBookingDate, formatDateTime12, formatDurationMinutes, formatEGP, formatTime12 } from '../lib/businessFormat';
import { registrationValidityLabel } from '../lib/registrationPolicy';
import { sortedStudioBookings, studioBookingReady } from '../lib/studioBookingPolicy';
import { safeUiError } from '../lib/uiError';
import { IntakeRequestCards } from './IntakeRequests';
import './StudioBookingRequests.css';
import useModalDialog from '../hooks/useModalDialog';
const labels = { pending: 'قيد المراجعة', approved: 'تمت الموافقة', rejected: 'لم تتم الموافقة' };
export function StudioBookingRequestCards({ items = [], role = 'client', onChanged }) {
  const [decision, setDecision] = useState(null); const [note, setNote] = useState(''); const [received, setReceived] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [proofPreview, setProofPreview] = useState(null);
  const proofDialogRef = useModalDialog(Boolean(proofPreview), () => setProofPreview(null), { isolateBackground: true });
  const canBookings = ['owner', 'admin', 'operations'].includes(role);
  const choose = (item, stage, action, appointment) => { setDecision({ item, stage, action, appointment }); setNote(''); setReceived(false); setError(''); };
  const submit = async event => { event.preventDefault(); if (busy || !decision) return; if (decision.stage === 'package' && decision.action === 'approve' && !received) return; setBusy(true); setError('');
    const payload = { stage: decision.stage, action: decision.action, note, ...(decision.appointment ? { booking_request_id: decision.appointment.id } : {}), ...(decision.stage === 'package' && decision.action === 'approve' ? { payment_received_confirmed: received } : {}) };
    const result = await dataClient.request(`/studio-booking-requests/${decision.item.id}/decision`, { method: 'POST', body: JSON.stringify(payload) }); setBusy(false); if (result.error) { setError(safeUiError(result.error, 'تعذر حفظ القرار. راجع الموعد وحاول مجددًا.')); return; } setDecision(null); await onChanged?.(); window.dispatchEvent(new CustomEvent('erpRequestsUpdated'));
  };
  const decisionForm = (item, stage, appointment) => decision?.item.id === item.id && decision.stage === stage && decision.appointment?.id === appointment?.id ? <form className="studio-request-decision" onSubmit={submit}><strong>{decision.action === 'approve' ? 'تأكيد الموافقة' : 'تأكيد الرفض'}</strong>{stage === 'package' && decision.action === 'approve' && <label className="studio-receipt-confirm"><input type="checkbox" checked={received} onChange={e => setReceived(e.target.checked)}/><span>راجعت التحويل وتأكدت من وصول مبلغ {formatEGP(item.deposit_amount)} إلى فودافون كاش.</span></label>}<label>ملاحظة للعميل (اختياري)<textarea rows="2" maxLength="1000" value={note} onChange={e => setNote(e.target.value)}/></label>{error && <p className="intake-error" role="alert">{error}</p>}<div className="studio-request-actions"><button className={decision.action === 'approve' ? 'approve' : 'reject'} disabled={busy || (stage === 'package' && decision.action === 'approve' && !received)}>{busy ? 'جارٍ الحفظ…' : 'تأكيد القرار'}</button><button type="button" disabled={busy} onClick={() => setDecision(null)}>تراجع</button></div></form> : null;
  if (!items.length) return <div className="intake-empty"><Inbox/><h3>لا توجد طلبات حجز حتى الآن</h3><p>ستظهر الباقة والمقدم ومواعيد التصوير هنا، كل موعد بحالته المستقلة.</p></div>;
  return <div className="studio-request-list">{items.map(item => <article key={item.id} className="studio-request-card"><header><span className="studio-request-avatar">{item.client_name?.charAt(0)}</span><div><span className="intake-eyebrow">طلب تصوير #{item.id}</span><h3>{item.client_name}</h3><p><bdi>{item.phone}</bdi>{role !== 'client' && <> · <bdi>{item.email}</bdi></>}</p></div><div className="studio-request-deadline"><Clock3/><span>المراجعة المتوقعة<strong>{formatDateTime12(item.review_due_at)}</strong></span></div></header>
    <section className="studio-request-package"><div className="studio-request-title"><Package/><h4>مراجعة المقدم والباقة</h4><span className={`intake-status ${item.package_status}`}>{labels[item.package_status]}</span></div><h3>{item.service_snapshot?.name}</h3><div className="studio-request-facts"><span>{formatDurationMinutes(Number(item.service_snapshot?.total_hours || 0) * 60)}</span><span>{registrationValidityLabel(item.service_snapshot || {})}</span><span>القيمة <b>{formatEGP(item.service_snapshot?.price)}</b></span><span>المقدم · 50% <b>{formatEGP(item.deposit_amount)}</b></span></div><p className="studio-request-note">فودافون كاش · <bdi>{item.transfer_account}</bdi> · {item.service_snapshot?.payment_due_text}</p>{item.package_note && <p className="intake-review-note">ملاحظة الإدارة: {item.package_note}</p>}<div className="studio-request-actions">{item.proof_url && <button onClick={() => setProofPreview(item)}><Eye/> عرض إثبات التحويل</button>}{item.package_status === 'pending' && role === 'owner' && <><button className="approve" onClick={() => choose(item, 'package', 'approve')}><Check/> اعتماد المقدم والباقة</button><button className="reject" onClick={() => choose(item, 'package', 'reject')}><X/> رفض</button></>}</div>{item.package_status === 'pending' && role !== 'owner' && <p className="studio-request-note"><ShieldCheck/> بانتظار مراجعة المالك للتحويل واعتماد الباقة.</p>}{decisionForm(item, 'package')}</section>
    <section className="studio-request-appointments"><div className="studio-request-title"><CalendarDays/><h4>مواعيد التصوير</h4><span className="studio-request-count">{item.bookings.length} مواعيد</span></div><ol>{sortedStudioBookings(item.bookings).map((row, index) => <li key={row.id}><div className="studio-request-appointment-heading"><span className="studio-request-order">{String(index + 1).padStart(2, '0')}</span><div><strong>{formatBookingDate(row.date)}</strong><p>{formatTime12(row.start_time)} إلى {formatTime12(row.end_time)} · {formatDurationMinutes(row.duration_minutes)}</p></div><span className={`intake-status ${row.status}`}>{labels[row.status]}</span></div>{row.note && <p className="intake-review-note">ملاحظة الإدارة: {row.note}</p>}{canBookings && row.status === 'pending' && <div className="studio-request-actions"><button className="approve" disabled={!studioBookingReady(item, row)} onClick={() => choose(item, 'booking', 'approve', row)}><Check/> تأكيد الموعد</button><button className="reject" disabled={item.package_status === 'rejected'} onClick={() => choose(item, 'booking', 'reject', row)}><X/> رفض الموعد</button>{!studioBookingReady(item, row) && <small>{item.package_status !== 'approved' ? 'بانتظار اعتماد الباقة.' : 'راجع الموعد الأسبق أولًا؛ منه تبدأ صلاحية الباقة.'}</small>}</div>}{decisionForm(item, 'booking', row)}</li>)}</ol></section></article>)}
    {proofPreview && <div ref={proofDialogRef} tabIndex={-1} className="studio-proof-dialog" role="dialog" aria-modal="true" aria-label="إثبات التحويل" onClick={e => { if (e.target === e.currentTarget) setProofPreview(null); }} onKeyDown={e => { if (e.key === 'Escape') setProofPreview(null); }}><section><header><h3>إثبات التحويل · طلب #{proofPreview.id}</h3><button autoFocus aria-label="إغلاق الإثبات" onClick={() => setProofPreview(null)}><X/></button></header><img src={proofPreview.proof_url} alt={`إيصال تحويل مقدم ${proofPreview.client_name}`}/><p>{formatEGP(proofPreview.deposit_amount)} · فودافون كاش</p></section></div>}
  </div>;
}
export default function ClientStudioRequests() {
  const [items, setItems] = useState([]); const [legacy, setLegacy] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); const [result, old] = await Promise.all([dataClient.request('/client/studio-booking-requests'), dataClient.request('/client/intake-requests')]); if (result.error) setError(safeUiError(result.error, 'تعذر تحميل طلباتك.')); else setItems(result.data?.items || []); if (!old.error) setLegacy(old.data?.items || []); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]); // eslint-disable-line react-hooks/set-state-in-effect
  return <section className="client-intake" dir="rtl"><header className="intake-heading"><div><span className="intake-eyebrow">خطوات حجزك في مكان واحد</span><h2>صندوق طلباتك</h2><p>تابع اعتماد المقدم والباقة، ثم تأكيد كل موعد تصوير.</p></div><button onClick={load} disabled={loading}><RefreshCw/> تحديث الحالة</button></header>{error && <p className="intake-error" role="alert">{error}</p>}{loading ? <p role="status">جارٍ تحميل طلباتك…</p> : <StudioBookingRequestCards items={items}/>} {!!legacy.length && <details className="studio-legacy"><summary>طلبات تسجيل سابقة</summary><IntakeRequestCards items={legacy}/></details>}</section>;
}
