SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  client_id BIGINT UNSIGNED NOT NULL,
  client_package_id BIGINT UNSIGNED NULL,
  name VARCHAR(190) NOT NULL,
  category VARCHAR(40) NOT NULL DEFAULT 'social_media',
  status VARCHAR(32) NOT NULL DEFAULT 'planning',
  starts_at DATE NULL,
  due_at DATE NULL,
  monthly_cycle_day TINYINT UNSIGNED NULL,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_projects_org_status (organization_id, status),
  KEY idx_projects_client (client_id, status),
  CONSTRAINT fk_projects_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_projects_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_projects_package FOREIGN KEY (client_package_id) REFERENCES client_packages(id) ON DELETE SET NULL,
  CONSTRAINT fk_projects_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_tasks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  project_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(220) NOT NULL,
  description TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'todo',
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  assigned_to BIGINT UNSIGNED NULL,
  due_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_project_tasks_project (project_id, status),
  KEY idx_project_tasks_assignee (assigned_to, status),
  CONSTRAINT fk_project_tasks_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_project_tasks_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_project_tasks_assignee FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_project_tasks_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS content_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL DEFAULT 1,
  project_id BIGINT UNSIGNED NOT NULL,
  client_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(220) NOT NULL,
  content_type VARCHAR(32) NOT NULL DEFAULT 'post',
  platform VARCHAR(40) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'idea',
  scheduled_at DATETIME NULL,
  published_at DATETIME NULL,
  caption LONGTEXT NULL,
  asset_url VARCHAR(500) NULL,
  published_url VARCHAR(500) NULL,
  client_note TEXT NULL,
  client_approved_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_content_org_schedule (organization_id, scheduled_at),
  KEY idx_content_project (project_id, status),
  KEY idx_content_client (client_id, status),
  CONSTRAINT fk_content_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_content_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_content_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_content_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
