CREATE TABLE IF NOT EXISTS registration_email_challenges (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 organization_id BIGINT UNSIGNED NOT NULL,
 challenge_hash CHAR(64) NOT NULL,
 email VARCHAR(190) NOT NULL,
 code_hash VARCHAR(255) NOT NULL,
 attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 expires_at DATETIME NOT NULL,
 verified_at DATETIME NULL,
 grant_hash CHAR(64) NULL,
 grant_expires_at DATETIME NULL,
 consumed_at DATETIME NULL,
 user_id BIGINT UNSIGNED NULL,
 request_id BIGINT UNSIGNED NULL,
 request_hash CHAR(64) NULL,
 revoked_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_registration_challenge (challenge_hash),
 UNIQUE KEY uq_registration_grant (grant_hash),
 KEY idx_registration_email (organization_id,email,created_at),
 KEY idx_registration_expiry (expires_at),
 CONSTRAINT fk_registration_challenge_org FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_intake_requests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 organization_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 client_id BIGINT UNSIGNED NULL,
 name VARCHAR(180) NOT NULL,
 phone VARCHAR(32) NOT NULL,
 email VARCHAR(190) NOT NULL,
 job VARCHAR(160) NULL,
 service_id BIGINT UNSIGNED NULL,
 service_snapshot JSON NULL,
 booking_snapshot JSON NULL,
 registration_status VARCHAR(24) NOT NULL DEFAULT 'pending',
 package_status VARCHAR(24) NOT NULL DEFAULT 'not_requested',
 booking_status VARCHAR(24) NOT NULL DEFAULT 'not_requested',
 registration_note TEXT NULL,
 package_note TEXT NULL,
 booking_note TEXT NULL,
 registration_decided_by BIGINT UNSIGNED NULL,
 package_decided_by BIGINT UNSIGNED NULL,
 booking_decided_by BIGINT UNSIGNED NULL,
 registration_decided_at DATETIME NULL,
 package_decided_at DATETIME NULL,
 booking_decided_at DATETIME NULL,
 client_package_id BIGINT UNSIGNED NULL,
 booking_id BIGINT UNSIGNED NULL,
 terms_version VARCHAR(32) NOT NULL,
 terms_accepted_at DATETIME NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_intake_registration_user (user_id),
 KEY idx_intake_org_status (organization_id,registration_status,package_status,booking_status),
 KEY idx_intake_client (organization_id,client_id),
 CONSTRAINT fk_intake_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
 CONSTRAINT fk_intake_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 CONSTRAINT fk_intake_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
 CONSTRAINT fk_intake_package FOREIGN KEY (client_package_id) REFERENCES client_packages(id) ON DELETE SET NULL,
 CONSTRAINT fk_intake_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
