CREATE TABLE IF NOT EXISTS client_studio_booking_requests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 organization_id BIGINT UNSIGNED NOT NULL,
 client_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 service_id BIGINT UNSIGNED NOT NULL,
 service_snapshot JSON NOT NULL,
 deposit_amount DECIMAL(12,2) NOT NULL,
 payment_method VARCHAR(32) NOT NULL DEFAULT 'vodafone_cash',
 transfer_account VARCHAR(32) NOT NULL DEFAULT '01094084424',
 proof_path VARCHAR(255) NOT NULL,
 proof_mime VARCHAR(80) NOT NULL,
 proof_original_name VARCHAR(255) NOT NULL,
 proof_hash CHAR(64) NOT NULL,
 package_status VARCHAR(24) NOT NULL DEFAULT 'pending',
 package_note TEXT NULL,
 package_decided_by BIGINT UNSIGNED NULL,
 package_decided_at DATETIME NULL,
 client_package_id BIGINT UNSIGNED NULL,
 payment_id BIGINT UNSIGNED NULL,
 payment_proof_id BIGINT UNSIGNED NULL,
 idempotency_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 terms_version VARCHAR(32) NOT NULL,
 terms_accepted_at DATETIME NOT NULL,
 review_due_at DATETIME NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_studio_request_retry (organization_id,user_id,idempotency_key),
 KEY idx_studio_request_client (organization_id,client_id,created_at),
 KEY idx_studio_request_pending (organization_id,package_status,created_at),
 CONSTRAINT fk_studio_request_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
 CONSTRAINT fk_studio_request_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
 CONSTRAINT fk_studio_request_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 CONSTRAINT fk_studio_request_package FOREIGN KEY (client_package_id) REFERENCES client_packages(id) ON DELETE SET NULL,
 CONSTRAINT fk_studio_request_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL,
 CONSTRAINT fk_studio_request_proof FOREIGN KEY (payment_proof_id) REFERENCES payment_proofs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_studio_booking_dates (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 organization_id BIGINT UNSIGNED NOT NULL,
 request_id BIGINT UNSIGNED NOT NULL,
 resource_id BIGINT UNSIGNED NOT NULL,
 date DATE NOT NULL,
 start_time TIME NOT NULL,
 end_time TIME NOT NULL,
 duration_minutes SMALLINT UNSIGNED NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'pending',
 note TEXT NULL,
 decided_by BIGINT UNSIGNED NULL,
 decided_at DATETIME NULL,
 booking_id BIGINT UNSIGNED NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY idx_studio_request_dates (request_id,status,date,start_time),
 CONSTRAINT fk_studio_date_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
 CONSTRAINT fk_studio_date_request FOREIGN KEY (request_id) REFERENCES client_studio_booking_requests(id) ON DELETE CASCADE,
 CONSTRAINT fk_studio_date_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
