<?php
declare(strict_types=1);

/** Shared receipt review; keeps package, payment and finance changes in the caller transaction. */
function reviewPaymentProof(PDO $pdo,array $user,int $id,array $payload): array {
    requireRole($user,['owner']);$action=(string)($payload['action']??'');if(!in_array($action,['approve','reject'],true))fail('القرار غير صالح.',422);
    $ownTransaction=!$pdo->inTransaction();if($ownTransaction)$pdo->beginTransaction();try{
        $stmt=$pdo->prepare("SELECT p.*,c.name AS client_name FROM payment_proofs p JOIN clients c ON c.id=p.client_id AND c.organization_id=p.organization_id WHERE p.id=? AND p.organization_id=? AND p.status='pending' FOR UPDATE");$stmt->execute([$id,$user['organization_id']]);$proof=$stmt->fetch();if(!$proof){$pdo->rollBack();fail('الإثبات غير موجود أو تمت مراجعته.',404);}
        $status=$action==='approve'?'approved':'rejected';$paymentId=null;
        if($status==='approved'){
            $hasPackage=!empty($proof['client_package_id']);$hasInvoice=!empty($proof['invoice_id']);if($hasPackage===$hasInvoice){$pdo->rollBack();fail('يجب أن يكون إثبات التحويل مرتبطًا بباقة أو فاتورة واحدة.',422,'invalid_payment_target');}
            $amountCents=packageMoneyCents($proof['amount']);if($amountCents<=0){$pdo->rollBack();fail('مبلغ التحويل غير صالح.',422,'invalid_payment_amount');}$amount=packageMoney($amountCents);
            $packageId=null;$invoiceId=null;$allocations=[];
            if($hasPackage){
                $stmt=$pdo->prepare('SELECT * FROM client_packages WHERE id=? AND organization_id=? AND client_id=? FOR UPDATE');$stmt->execute([(int)$proof['client_package_id'],$user['organization_id'],$proof['client_id']]);$target=$stmt->fetch();if(!$target){$pdo->rollBack();fail('الباقة المرتبطة بالتحويل غير موجودة.',404);}
                $outstandingCents=max(0,packageMoneyCents($target['total_price'])+packageMoneyCents($target['overage_amount'])-packageMoneyCents($target['paid_amount']));if($amountCents>$outstandingCents){$pdo->rollBack();fail('مبلغ التحويل يتجاوز الرصيد المتبقي على الباقة.',422,'payment_exceeds_outstanding');}
                $packageId=(int)$target['id'];
                $remainingForPackageCents=$amountCents;if(!empty($target['source_invoice_id'])){$stmt=$pdo->prepare('SELECT * FROM invoices WHERE id=? AND organization_id=? AND client_id=? FOR UPDATE');$stmt->execute([(int)$target['source_invoice_id'],$user['organization_id'],$proof['client_id']]);$sourceInvoice=$stmt->fetch();if(!$sourceInvoice){$pdo->rollBack();fail('الفاتورة الأصلية المرتبطة بالباقة غير موجودة.',404,'source_invoice_missing');}$invoiceOutstandingCents=max(0,packageMoneyCents($sourceInvoice['total'])-packageMoneyCents($sourceInvoice['paid_amount']));$invoiceAllocatedCents=min($amountCents,$invoiceOutstandingCents);if($invoiceAllocatedCents>0){$invoiceId=(int)$sourceInvoice['id'];$newInvoicePaidCents=packageMoneyCents($sourceInvoice['paid_amount'])+$invoiceAllocatedCents;$invoiceStatus=$newInvoicePaidCents>=packageMoneyCents($sourceInvoice['total'])?'paid':$sourceInvoice['status'];$pdo->prepare('UPDATE invoices SET paid_amount=?,status=? WHERE id=?')->execute([packageMoney($newInvoicePaidCents),$invoiceStatus,$invoiceId]);$allocations[]=[$packageId,$invoiceId,packageMoney($invoiceAllocatedCents)];$remainingForPackageCents-=$invoiceAllocatedCents;}}
                if($remainingForPackageCents>0)$allocations[]=[$packageId,null,packageMoney($remainingForPackageCents)];
                $pdo->prepare('UPDATE client_packages SET paid_amount=paid_amount+? WHERE id=?')->execute([$amount,$packageId]);
            }
            else{
                $stmt=$pdo->prepare('SELECT * FROM invoices WHERE id=? AND organization_id=? AND client_id=? FOR UPDATE');$stmt->execute([(int)$proof['invoice_id'],$user['organization_id'],$proof['client_id']]);$target=$stmt->fetch();if(!$target){$pdo->rollBack();fail('الفاتورة المرتبطة بالتحويل غير موجودة.',404);}
                $outstandingCents=max(0,packageMoneyCents($target['total'])-packageMoneyCents($target['paid_amount']));if($amountCents>$outstandingCents){$pdo->rollBack();fail('مبلغ التحويل يتجاوز الرصيد المتبقي على الفاتورة.',422,'payment_exceeds_outstanding');}
                $invoiceId=(int)$target['id'];$newPaidCents=packageMoneyCents($target['paid_amount'])+$amountCents;$invoiceStatus=$newPaidCents>=packageMoneyCents($target['total'])?'paid':$target['status'];$pdo->prepare('UPDATE invoices SET paid_amount=?,status=? WHERE id=?')->execute([packageMoney($newPaidCents),$invoiceStatus,$invoiceId]);
                $packageStmt=$pdo->prepare('SELECT id,total_price,paid_amount FROM client_packages WHERE source_invoice_id=? AND organization_id=? AND client_id=? ORDER BY id FOR UPDATE');$packageStmt->execute([$invoiceId,$user['organization_id'],$proof['client_id']]);$remainingAllocationCents=$amountCents;foreach($packageStmt->fetchAll() as $linkedPackage){if($remainingAllocationCents<=0)break;$packageOutstandingCents=max(0,packageMoneyCents($linkedPackage['total_price'])-packageMoneyCents($linkedPackage['paid_amount']));$allocatedCents=min($remainingAllocationCents,$packageOutstandingCents);if($allocatedCents>0){$allocated=packageMoney($allocatedCents);$pdo->prepare('UPDATE client_packages SET paid_amount=paid_amount+? WHERE id=?')->execute([$allocated,$linkedPackage['id']]);$allocations[]=[(int)$linkedPackage['id'],$invoiceId,$allocated];$remainingAllocationCents-=$allocatedCents;}}
                if($remainingAllocationCents>0)$allocations[]=[null,$invoiceId,packageMoney($remainingAllocationCents)];
            }
            $proofMethod=in_array((string)($proof['payment_method']??''),['cash','instapay','vodafone_cash'],true)?(string)$proof['payment_method']:'bank_transfer';
            $methodLabel=['cash'=>'كاش','instapay'=>'انستاباي','vodafone_cash'=>'فودافون كاش','bank_transfer'=>'تحويل بنكي'][$proofMethod];
            $pdo->prepare("INSERT INTO payments (organization_id,client_id,client_name,amount,method,status,reference,reviewed_by,reviewed_at) VALUES (?,?,?,?,?,'approved',?,?,NOW())")->execute([$user['organization_id'],$proof['client_id'],$proof['client_name'],$amount,$proofMethod,'proof-'.$id,$user['id']]);$paymentId=(int)$pdo->lastInsertId();
            $pdo->prepare("INSERT INTO finance (organization_id,client_id,type,entry_kind,category,amount,method,detail,date,entity,source_type,source_id,correlation_id,is_system,created_by) VALUES (?,?,?,'income','client_revenue',?,?,?,?,?,'payment',?,?,1,?)")->execute([$user['organization_id'],$proof['client_id'],'إيراد',$amount,$methodLabel,'دفعة معتمدة من العميل '.$proof['client_name'].' عبر إثبات تحويل رقم '.$id,date('Y-m-d'),'الشركة',$paymentId,'payment:'.$paymentId,$user['id']]);
            $allocationStmt=$pdo->prepare('INSERT INTO payment_allocations (organization_id,client_id,payment_id,payment_proof_id,client_package_id,invoice_id,amount) VALUES (?,?,?,?,?,?,?)');foreach($allocations as [$allocatedPackage,$allocatedInvoice,$allocatedAmount])$allocationStmt->execute([$user['organization_id'],$proof['client_id'],$paymentId,$id,$allocatedPackage,$allocatedInvoice,$allocatedAmount]);
        }
        $pdo->prepare('UPDATE payment_proofs SET payment_id=?,status=?,admin_note=?,reviewed_by=?,reviewed_at=NOW() WHERE id=? AND status=\'pending\'')->execute([$paymentId,$status,$payload['note']??null,$user['id'],$id]);if($status==='approved')dismissSettledPackageNotifications($pdo,(int)$user['organization_id'],(int)$proof['client_id']);audit($pdo,$user,'payment_proof_decision','payment_proofs',$id,$proof,['status'=>$status,'payment_id'=>$paymentId]);if($status==='approved')queueClientWhatsAppSummary($pdo,(int)$user['organization_id'],(int)$proof['client_id']);$ownTransaction&&$pdo->commit();return ['id'=>$id,'status'=>$status,'payment_id'=>$paymentId];
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
