<?php
declare(strict_types=1);

function settlementMinutes(mixed $hours): int { return max(0,(int)round((float)$hours*60)); }
function settlementHours(int $minutes): float { return round(max(0,$minutes)/60,4); }
function settlementPackageMinutes(array $package,string $name): int {
    $minuteKey=$name.'_minutes';$quantityKey=$name.'_quantity';
    return array_key_exists($minuteKey,$package)&&$package[$minuteKey]!==null?max(0,(int)$package[$minuteKey]):settlementMinutes($package[$quantityKey]??0);
}
function settlementLedgerMinutes(PDO $pdo,int $bookingId,int $packageId): int {
    $stmt=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN movement_type='hold' THEN COALESCE(quantity_minutes,ROUND(quantity*60)) WHEN movement_type IN ('release','consume') THEN -COALESCE(quantity_minutes,ROUND(quantity*60)) ELSE 0 END),0) FROM package_usage_ledger WHERE booking_id=? AND client_package_id=?");
    $stmt->execute([$bookingId,$packageId]);return max(0,(int)round((float)$stmt->fetchColumn()));
}
function settlementCanonical(mixed $value): mixed {
    if(!is_array($value))return $value;
    if(array_is_list($value))return array_map('settlementCanonical',$value);
    ksort($value);foreach($value as $key=>$item)$value[$key]=settlementCanonical($item);return $value;
}
function settlementHash(array $value): string { return hash('sha256',json_encode(settlementCanonical($value),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); }

function studioSettlementPreview(PDO $pdo,array $user,int $bookingId,int $actualMinutes,bool $lock=false): array {
    if($actualMinutes<1)fail('حدد مدة تصوير صحيحة بالدقائق، دقيقة واحدة على الأقل.',422,'invalid_actual_duration');
    $lockSql=$lock?' FOR UPDATE':'';
    $stmt=$pdo->prepare("SELECT b.*,cp.billing_unit,cp.purchased_quantity,cp.purchased_minutes,cp.held_quantity,cp.held_minutes,cp.consumed_quantity,cp.consumed_minutes,cp.overage_price_snapshot,cp.service_id AS package_service_id,cp.name AS package_name FROM bookings b LEFT JOIN client_packages cp ON cp.id=b.client_package_id AND cp.organization_id=b.organization_id WHERE b.id=? AND b.organization_id=?$lockSql");
    $stmt->execute([$bookingId,$user['organization_id']]);$booking=$stmt->fetch();if(!$booking)fail('الحجز غير موجود.',404,'booking_not_found');
    $stmt=$pdo->prepare("SELECT * FROM booking_sessions WHERE booking_id=? AND organization_id=?$lockSql");$stmt->execute([$bookingId,$user['organization_id']]);$session=$stmt->fetch();if(!$session)fail('لا توجد جلسة تصوير لهذا الحجز.',404,'session_not_found');if($session['status']!=='active')fail('جلسة التصوير لم تعد نشطة.',409,'invalid_session_state');
    $unit=(string)($booking['billing_unit']??'hour');$packageId=(int)($booking['client_package_id']??0);$heldMinutes=$packageId?settlementLedgerMinutes($pdo,$bookingId,$packageId):0;
    if($packageId&&$heldMinutes<1)fail('لا يوجد رصيد محجوز صالح لهذا الموعد.',409,'missing_package_hold');
    $freeOriginal=0;$covered=$actualMinutes;$excess=0;
    if($unit==='hour'&&$packageId){
        $freeOriginal=max(0,settlementPackageMinutes($booking,'purchased')-settlementPackageMinutes($booking,'consumed')-settlementPackageMinutes($booking,'held'));
        $covered=min($actualMinutes,$heldMinutes+$freeOriginal);$excess=max(0,$actualMinutes-$covered);
    }
    $today=cairoNow()->format('Y-m-d');$eligible=[];
    if($excess>0){
        $sql="SELECT id,name,service_id,purchased_quantity,purchased_minutes,consumed_quantity,consumed_minutes,held_quantity,held_minutes,expires_at FROM client_packages WHERE organization_id=? AND client_id=? AND id<>? AND billing_unit='hour' AND status='active' AND starts_at<=? AND expires_at>=? ORDER BY id$lockSql";
        $other=$pdo->prepare($sql);$other->execute([$user['organization_id'],$booking['client_id'],$packageId,$today,$today]);
        foreach($other->fetchAll() as $row){$free=max(0,settlementPackageMinutes($row,'purchased')-settlementPackageMinutes($row,'consumed')-settlementPackageMinutes($row,'held'));if($free>=$excess)$eligible[]=['id'=>(int)$row['id'],'name'=>$row['name'],'service_id'=>(int)$row['service_id'],'free_minutes'=>$free,'remaining_after_minutes'=>$free-$excess,'expires_at'=>$row['expires_at']];}
    }
    $templates=$pdo->prepare("SELECT id,name,total_hours,validity_days,price,overage_price FROM services WHERE organization_id=? AND billing_unit='hour' AND is_active=1 ORDER BY name");$templates->execute([$user['organization_id']]);$packageTemplates=array_map(fn($row)=>['id'=>(int)$row['id'],'name'=>$row['name'],'total_minutes'=>settlementMinutes($row['total_hours']),'validity_days'=>(int)$row['validity_days'],'price'=>packageMoney(packageMoneyCents($row['price'])),'overage_rate'=>packageMoney(packageMoneyCents($row['overage_price']))],$templates->fetchAll());
    $rate=packageMoney(packageMoneyCents($booking['overage_price_snapshot']??0));if($rate<=0&&!empty($booking['service_id'])){$rateStmt=$pdo->prepare('SELECT overage_price FROM services WHERE id=? AND organization_id=? AND is_active=1');$rateStmt->execute([$booking['service_id'],$user['organization_id']]);$rate=packageMoney(packageMoneyCents($rateStmt->fetchColumn()?:0));}
    $version=max(1,(int)($session['settlement_version']??1));$snapshot=['session_id'=>(int)$session['id'],'session_version'=>$version,'actual_minutes'=>$actualMinutes,'held_minutes'=>$heldMinutes,'free_original_minutes'=>$freeOriginal,'covered_minutes'=>$covered,'excess_minutes'=>$excess,'package_id'=>$packageId,'package_minutes'=>[$packageId?settlementPackageMinutes($booking,'purchased'):0,$packageId?settlementPackageMinutes($booking,'consumed'):0,$packageId?settlementPackageMinutes($booking,'held'):0],'eligible'=>array_map(fn($row)=>[$row['id'],$row['free_minutes']],$eligible),'rate'=>$rate];
    return ['booking'=>$booking,'session'=>$session,'actual_minutes'=>$actualMinutes,'held_for_booking_minutes'=>$heldMinutes,'free_unheld_original_minutes'=>$freeOriginal,'covered_minutes'=>$covered,'excess_minutes'=>$excess,'eligible_packages'=>$eligible,'package_templates'=>$packageTemplates,'overage_rate'=>$rate,'default_mode'=>$eligible?'existing_package':($rate>0?'package_overage':'custom_invoice'),'session_version'=>$version,'preview_hash'=>settlementHash($snapshot)];
}

function settlementCreateInvoice(PDO $pdo,array $user,array $booking,string $description,int $cents,?int $projectId=null): int {
    $number='SET-'.cairoNow()->format('ymdHis').'-'.$booking['id'].'-'.random_int(10,99);$amount=packageMoney($cents);$today=cairoNow()->format('Y-m-d');
    $stmt=$pdo->prepare("INSERT INTO invoices (organization_id,client_id,project_id,invoice_number,status,subtotal,discount,total,paid_amount,issued_at,due_at,notes,created_by) VALUES (?,?,?,?,'issued',?,0,?,0,?,?,?,?)");$stmt->execute([$user['organization_id'],$booking['client_id'],$projectId,$number,$amount,$amount,$today,$today,$description,$user['id']]);$invoiceId=(int)$pdo->lastInsertId();
    $pdo->prepare('INSERT INTO invoice_items (invoice_id,service_id,description,quantity,unit,unit_price,total) VALUES (?,?,?,?,?,?,?)')->execute([$invoiceId,$booking['service_id']?:null,$description,1,'session',$amount,$amount]);return $invoiceId;
}

function settleAndCompleteBookingSession(PDO $pdo,array $user,int $bookingId,array $payload): array {
    $actual=filter_var($payload['actual_minutes']??null,FILTER_VALIDATE_INT);if($actual===false||$actual<1)fail('حدد مدة تصوير صحيحة بالدقائق، دقيقة واحدة على الأقل.',422,'invalid_actual_duration');
    $pdo->beginTransaction();
    try{
        $key=trim((string)($payload['idempotency_key']??''));if(strlen($key)>128)fail('معرّف الاعتماد غير صالح.',422,'invalid_idempotency_key');
        $request=['booking_id'=>$bookingId,'actual_minutes'=>$actual,'actual_reels'=>(int)($payload['actual_reels']??0),'reason'=>trim((string)($payload['reason']??'')),'expected_session_version'=>(int)($payload['expected_session_version']??0),'preview_hash'=>(string)($payload['preview_hash']??''),'settlement'=>$payload['settlement']??null];$requestHash=settlementHash($request);
        if($key!==''){$idem=$pdo->prepare('SELECT request_hash,response_json FROM session_settlements WHERE organization_id=? AND idempotency_key=? FOR UPDATE');$idem->execute([$user['organization_id'],$key]);if($row=$idem->fetch()){if(!hash_equals((string)$row['request_hash'],$requestHash))fail('تم استخدام مفتاح الاعتماد نفسه ببيانات مختلفة.',409,'idempotency_payload_mismatch');$pdo->commit();return json_decode((string)$row['response_json'],true)+['idempotent_replay'=>true];}}
        $completed=$pdo->prepare('SELECT ss.id,ss.idempotency_key FROM session_settlements ss JOIN booking_sessions bs ON bs.id=ss.booking_session_id WHERE bs.booking_id=? AND ss.organization_id=? FOR UPDATE');$completed->execute([$bookingId,$user['organization_id']]);if($completed->fetch())fail('تمت تسوية هذه الجلسة من قبل بعملية اعتماد أخرى.',409,'session_already_settled');
        $preview=studioSettlementPreview($pdo,$user,$bookingId,(int)$actual,true);$booking=$preview['booking'];$session=$preview['session'];$excess=(int)$preview['excess_minutes'];$covered=(int)$preview['covered_minutes'];$unit=(string)($booking['billing_unit']??'hour');$reels=0;if($unit==='reel'){$reels=filter_var($payload['actual_reels']??null,FILTER_VALIDATE_INT);$heldReels=bookingHeldQuantity($pdo,$bookingId,(int)$booking['client_package_id']);if($reels===false||$reels<1||$reels>$heldReels+0.0001)fail('عدد الريلز يجب أن يكون رقمًا صحيحًا داخل الرصيد المحجوز.',422,'invalid_actual_reels');}
        if($key===''&&$excess>0)fail('معرّف اعتماد التسوية مطلوب للوقت الزائد.',422,'idempotency_key_required');if($key==='')$key='session-'.$session['id'].'-v'.$preview['session_version'];
        if($excess>0){$submittedPreviewHash=trim((string)($payload['preview_hash']??''));$submittedVersion=filter_var($payload['expected_session_version']??null,FILTER_VALIDATE_INT);if($submittedPreviewHash===''||$submittedVersion===false||$submittedVersion<1)fail('يجب معاينة تسوية الوقت الزائد قبل اعتمادها.',422,'settlement_preview_required');if(!hash_equals($preview['preview_hash'],$submittedPreviewHash)||(int)$submittedVersion!==(int)$preview['session_version'])fail('تغيّر الرصيد منذ المعاينة. راجع الملخص المحدث.',409,'stale_settlement_preview');}
        $settlement=is_array($payload['settlement']??null)?$payload['settlement']:[];$mode=$excess>0?(string)($settlement['mode']??''):'none';
        if($excess>0&&$user['role']==='operations')fail('اعتماد الوقت الزائد يحتاج المالك أو الإدارة. ما زالت الجلسة نشطة.',403,'settlement_owner_required');
        $allowed=$user['role']==='owner'?['new_package','existing_package','package_overage','custom_invoice','custom_project','waive']:['new_package','existing_package','package_overage'];if($excess>0&&!in_array($mode,$allowed,true))fail('طريقة التسوية غير مسموحة لهذا المستخدم.',403,'settlement_mode_forbidden');
        $originalId=(int)($booking['client_package_id']??0);$targetId=null;$targetPackage=null;$serviceId=null;$invoiceId=null;$projectId=null;$paymentId=null;$dueCents=0;$paidCents=0;$waived=0;$internal=null;$clientNote=trim((string)($settlement['client_note']??''));
        if($mode==='existing_package'){$targetId=(int)($settlement['target_package_id']??0);$eligible=array_filter($preview['eligible_packages'],fn($row)=>(int)$row['id']===$targetId);if(!$eligible)fail('الباقة الأخرى لم تعد تحتوي رصيدًا حرًا كافيًا.',409,'settlement_balance_changed');$target=$pdo->prepare('SELECT * FROM client_packages WHERE id=? AND organization_id=? AND client_id=? FOR UPDATE');$target->execute([$targetId,$user['organization_id'],$booking['client_id']]);$targetPackage=$target->fetch();$serviceId=(int)($targetPackage['service_id']??0);if(!$serviceId)fail('الباقة المستهدفة غير موجودة.',404,'target_package_not_found');}
        elseif($mode==='new_package'){
            $serviceId=(int)($settlement['service_id']??0);$template=$pdo->prepare("SELECT * FROM services WHERE id=? AND organization_id=? AND is_active=1 AND billing_unit='hour' FOR UPDATE");$template->execute([$serviceId,$user['organization_id']]);$tpl=$template->fetch();if(!$tpl)fail('نموذج الباقة الجديدة غير متاح.',422,'invalid_package_template');
            $minutes=filter_var($settlement['purchased_minutes']??null,FILTER_VALIDATE_INT);$days=filter_var($settlement['validity_days']??null,FILTER_VALIDATE_INT);$name=trim((string)($settlement['name']??''));$totalCents=packageMoneyCents($settlement['total_price']??0);$paidCents=packageMoneyCents($settlement['initial_paid']??0);if($minutes===false||$minutes<$excess||$days===false||$days<1||$name===''||$totalCents<0||$paidCents<0||$paidCents>$totalCents)fail('بيانات الباقة الجديدة غير صحيحة أو لا تغطي الوقت الزائد.',422,'invalid_new_package');if($user['role']!=='owner'&&($minutes!==settlementMinutes($tpl['total_hours'])||$days!==(int)$tpl['validity_days']||$totalCents!==packageMoneyCents($tpl['price'])))fail('الإدارة يمكنها بيع نموذج الباقة بالساعات والصلاحية والسعر المعتمد فقط.',403,'custom_package_terms_forbidden');
            $invoiceId=$totalCents>0?settlementCreateInvoice($pdo,$user,$booking,'باقة جديدة لتسوية وقت تصوير زائد — '.$name,$totalCents):null;$starts=(string)$booking['date'];$startDate=DateTimeImmutable::createFromFormat('!Y-m-d',$starts,new DateTimeZone('Africa/Cairo'));$expires=$startDate->modify('+'.(max(1,(int)$days)-1).' days')->format('Y-m-d');
            $paymentDueMinutes=settlementMinutes(max(0,(float)$tpl['payment_due_hours']));$stmt=$pdo->prepare("INSERT INTO client_packages (organization_id,client_id,service_id,source_invoice_id,name,billing_unit,purchased_quantity,purchased_minutes,held_quantity,held_minutes,consumed_quantity,consumed_minutes,payment_due_quantity,payment_due_minutes,deposit_percent_snapshot,overage_price_snapshot,total_price,overage_amount,paid_amount,starts_at,expires_at,validity_mode_snapshot,validity_days_snapshot,status) VALUES (?,?,?,?,?,'hour',?,?,0,0,0,0,?,?,?,?,?,0,?,?,?,'rolling',?,'active')");$stmt->execute([$user['organization_id'],$booking['client_id'],$serviceId,$invoiceId,$name,settlementHours((int)$minutes),(int)$minutes,settlementHours($paymentDueMinutes),$paymentDueMinutes,(float)($tpl['deposit_percent']??0),packageMoney(packageMoneyCents($tpl['overage_price']??0)),packageMoney($totalCents),packageMoney($paidCents),$starts,$expires,(int)$days]);$targetId=(int)$pdo->lastInsertId();$targetPackage=['purchased_minutes'=>(int)$minutes,'consumed_minutes'=>0,'held_minutes'=>0,'purchased_quantity'=>settlementHours((int)$minutes),'consumed_quantity'=>0,'held_quantity'=>0];$dueCents=$totalCents;
            if($paidCents>0){$pdo->prepare("INSERT INTO payments (organization_id,client_id,client_name,amount,method,status,reference,reviewed_by,reviewed_at) VALUES (?,?,?,?,?,'approved',?,?,NOW())")->execute([$user['organization_id'],$booking['client_id'],$booking['client_name'],packageMoney($paidCents),'cash','SET-'.$session['id'],$user['id']]);$paymentId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO payment_allocations (organization_id,client_id,payment_id,payment_proof_id,client_package_id,invoice_id,amount) VALUES (?,?,?,?,?,?,?)')->execute([$user['organization_id'],$booking['client_id'],$paymentId,null,$targetId,$invoiceId,packageMoney($paidCents)]);if($invoiceId)$pdo->prepare("UPDATE invoices SET paid_amount=?,status=IF(? >= total,'paid','partial') WHERE id=?")->execute([packageMoney($paidCents),packageMoney($paidCents),$invoiceId]);$pdo->prepare("INSERT INTO finance (organization_id,client_id,type,entry_kind,category,amount,method,detail,date,entity,source_type,source_id,correlation_id,is_system,created_by) VALUES (?,?,'إيراد','income','client_revenue',?,'cash',?,?,'الشركة','payment',?,?,1,?)")->execute([$user['organization_id'],$booking['client_id'],packageMoney($paidCents),'دفعة باقة جديدة — '.$name,$starts,$paymentId,'session-settlement:'.$session['id'].':payment',$user['id']]);}
        } elseif($mode==='package_overage'){$configured=packageMoneyCents($preview['overage_rate']);$submitted=packageMoneyCents($settlement['hourly_rate']??$preview['overage_rate']);if($submitted<=0)fail('سعر الساعة الإضافية غير مضبوط.',422,'missing_overage_rate');if($user['role']!=='owner'&&$submitted!==$configured)fail('الإدارة يمكنها استخدام السعر المعتمد فقط.',403,'custom_rate_forbidden');$dueCents=(int)round($submitted*$excess/60);if($dueCents<=0)fail('قيمة الوقت الإضافي أقل من قرش واحد.',422,'overage_amount_too_small');$pdo->prepare('UPDATE client_packages SET overage_amount=overage_amount+? WHERE id=?')->execute([packageMoney($dueCents),$originalId]);}
        elseif(in_array($mode,['custom_invoice','custom_project'],true)){$description=trim((string)($settlement['description']??'وقت تصوير إضافي'));$dueCents=packageMoneyCents($settlement['amount']??0);if($dueCents<=0)$dueCents=(int)round(packageMoneyCents($settlement['hourly_rate']??0)*$excess/60);if($description===''||$dueCents<=0)fail('وصف وقيمة التسوية المخصصة مطلوبان.',422,'invalid_custom_settlement');
            if($mode==='custom_project'){$name=trim((string)($settlement['name']??''));if($name==='')fail('اسم المشروع المخصص مطلوب.',422,'invalid_custom_project');$today=cairoNow()->format('Y-m-d');$pdo->prepare("INSERT INTO projects (organization_id,client_id,name,category,service_type,pricing_model,quantity,unit_label,agreed_price,requires_booking,requirements_json,progress_percent,status,starts_at,notes,created_by) VALUES (?,?,?,'custom','custom','custom',1,'project',?,0,?,0,'planning',?,?,?)")->execute([$user['organization_id'],$booking['client_id'],$name,packageMoney($dueCents),json_encode(['session_settlement'=>true,'booking_id'=>$bookingId,'excess_minutes'=>$excess],JSON_UNESCAPED_UNICODE),$today,$description,$user['id']]);$projectId=(int)$pdo->lastInsertId();$invoiceId=settlementCreateInvoice($pdo,$user,$booking,$description,$dueCents,$projectId);$pdo->prepare('UPDATE projects SET invoice_id=? WHERE id=?')->execute([$invoiceId,$projectId]);$pdo->prepare("INSERT INTO project_items (organization_id,project_id,client_id,item_type,description,status,quantity,unit,unit_price,total_price,internal_cost,is_client_visible,sort_order) VALUES (?,?,?,'service',?,'draft',1,'session',?,?,0,1,0)")->execute([$user['organization_id'],$projectId,$booking['client_id'],$description,packageMoney($dueCents),packageMoney($dueCents)]);$pdo->prepare("INSERT INTO project_milestones (organization_id,project_id,client_id,title,status,progress_percent,is_client_visible,sort_order) VALUES (?,?,?,'اعتماد وقت التصوير الإضافي','completed',100,1,0),(?,?,?,'التسليم النهائي','pending',0,1,1)")->execute([$user['organization_id'],$projectId,$booking['client_id'],$user['organization_id'],$projectId,$booking['client_id']]);}else{$invoiceId=settlementCreateInvoice($pdo,$user,$booking,$description,$dueCents);}
        } elseif($mode==='waive'){$internal=trim((string)($settlement['internal_reason']??''));if(mb_strlen($internal)<5)fail('سبب التغاضي الداخلي مطلوب.',422,'waiver_reason_required');$waived=$excess;}
        $billable=$covered+($mode==='waive'?0:$excess);$due=packageMoney($dueCents);$paid=packageMoney($paidCents);
        $stmt=$pdo->prepare('INSERT INTO session_settlements (organization_id,booking_session_id,booking_id,client_id,original_client_package_id,actual_minutes,covered_minutes,excess_minutes,billable_minutes,waived_minutes,settlement_mode,amount_due,amount_paid,internal_reason,client_note,idempotency_key,request_hash,preview_hash,session_version,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$user['organization_id'],$session['id'],$bookingId,$booking['client_id'],$originalId?:null,$actual,$covered,$excess,$billable,$waived,$mode,$due,$paid,$internal,$clientNote?:null,$key,$requestHash,$preview['preview_hash'],$preview['session_version'],$user['id']]);$settlementId=(int)$pdo->lastInsertId();
        $alloc=$pdo->prepare('INSERT INTO session_settlement_allocations (settlement_id,allocation_type,minutes,source_client_package_id,target_client_package_id,service_id,project_id,invoice_id,payment_id,rate_snapshot,unit,amount_snapshot,internal_note,client_note,event_key) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');if($originalId&&$covered)$alloc->execute([$settlementId,'original_package',$covered,$originalId,null,$booking['service_id']?:null,null,null,null,0,'minute',0,null,null,'original']);if($excess)$alloc->execute([$settlementId,$mode,$excess,$originalId?:null,$targetId,$serviceId,$projectId,$invoiceId,$paymentId,$mode==='package_overage'?packageMoney(packageMoneyCents($settlement['hourly_rate']??$preview['overage_rate'])):0,'minute',$due,$internal,$clientNote?:null,'excess']);
        if($originalId){if($unit==='reel'){$heldQuantity=bookingHeldQuantity($pdo,$bookingId,$originalId);$consumeQuantity=(float)$reels;$releaseQuantity=max(0,$heldQuantity-$consumeQuantity);$pdo->prepare('UPDATE client_packages SET held_quantity=GREATEST(0,held_quantity-?),consumed_quantity=LEAST(purchased_quantity,consumed_quantity+?) WHERE id=?')->execute([$heldQuantity,$consumeQuantity,$originalId]);$pdo->prepare("INSERT IGNORE INTO package_usage_ledger (client_package_id,booking_id,movement_type,quantity,quantity_minutes,reason,event_key,created_by) VALUES (?,?,'consume',?,NULL,'الوقت المغطى من جلسة التصوير',?,?)")->execute([$originalId,$bookingId,$consumeQuantity,'settlement:'.$settlementId.':original',$user['id']]);if($releaseQuantity>0)$pdo->prepare("INSERT IGNORE INTO package_usage_ledger (client_package_id,booking_id,movement_type,quantity,quantity_minutes,reason,event_key,created_by) VALUES (?,?,'release',?,NULL,'إعادة رصيد الحجز غير المستخدم',?,?)")->execute([$originalId,$bookingId,$releaseQuantity,'settlement:'.$settlementId.':release',$user['id']]);}else{$oldConsumed=settlementPackageMinutes($booking,'consumed');$oldHeld=settlementPackageMinutes($booking,'held');$purchased=settlementPackageMinutes($booking,'purchased');$newConsumed=$oldConsumed+$covered;$newHeld=max(0,$oldHeld-$preview['held_for_booking_minutes']);if($newConsumed>$purchased)fail('لا يمكن خصم وقت يتجاوز إجمالي رصيد الباقة.',409,'package_overdraft_prevented');$pdo->prepare('UPDATE client_packages SET held_minutes=?,held_quantity=?,consumed_minutes=?,consumed_quantity=? WHERE id=?')->execute([$newHeld,settlementHours($newHeld),$newConsumed,settlementHours($newConsumed),$originalId]);$pdo->prepare("INSERT IGNORE INTO package_usage_ledger (client_package_id,booking_id,movement_type,quantity,quantity_minutes,reason,event_key,created_by) VALUES (?,?,'consume',?,?,'الوقت المغطى من جلسة التصوير',?,?)")->execute([$originalId,$bookingId,settlementHours($covered),$covered,'settlement:'.$settlementId.':original',$user['id']]);$releaseMinutes=max(0,$preview['held_for_booking_minutes']-min($preview['held_for_booking_minutes'],$covered));if($releaseMinutes>0)$pdo->prepare("INSERT IGNORE INTO package_usage_ledger (client_package_id,booking_id,movement_type,quantity,quantity_minutes,reason,event_key,created_by) VALUES (?,?,'release',?,?,'إعادة رصيد الحجز غير المستخدم',?,?)")->execute([$originalId,$bookingId,settlementHours($releaseMinutes),$releaseMinutes,'settlement:'.$settlementId.':release',$user['id']]);}}
        if($targetId&&in_array($mode,['new_package','existing_package'],true)){$targetPurchased=settlementPackageMinutes($targetPackage,'purchased');$targetConsumed=settlementPackageMinutes($targetPackage,'consumed');$targetHeld=settlementPackageMinutes($targetPackage,'held');$targetNewConsumed=$targetConsumed+$excess;if($targetNewConsumed+$targetHeld>$targetPurchased)fail('رصيد الباقة المستهدفة لم يعد كافيًا.',409,'settlement_balance_changed');$pdo->prepare('UPDATE client_packages SET consumed_minutes=?,consumed_quantity=? WHERE id=?')->execute([$targetNewConsumed,settlementHours($targetNewConsumed),$targetId]);$pdo->prepare("INSERT IGNORE INTO package_usage_ledger (client_package_id,booking_id,movement_type,quantity,quantity_minutes,reason,event_key,created_by) VALUES (?,?,'consume',?,?,'تسوية وقت تصوير زائد',?,?)")->execute([$targetId,$bookingId,settlementHours($excess),$excess,'settlement:'.$settlementId.':target',$user['id']]);}
        $ended=cairoNow()->format('Y-m-d H:i:s');$billableQuantity=$unit==='reel'?$reels:settlementHours($billable);$pdo->prepare("UPDATE booking_sessions SET ended_at=?,actual_seconds=?,billable_quantity=?,status='completed',ended_by=?,adjustment_reason=?,settlement_version=settlement_version+1 WHERE id=?")->execute([$ended,$actual*60,$billableQuantity,$user['id'],trim((string)($payload['reason']??''))?:null,$session['id']]);$pdo->prepare("UPDATE bookings SET status='completed',timer_ended_at=?,actual_seconds=?,actual_hours=?,actual_reels=?,billable_quantity=?,overage_quantity=?,overage_amount=?,session_version=session_version+1 WHERE id=?")->execute([$ended,$actual*60,settlementHours($actual),$reels,$billableQuantity,settlementHours($excess),$mode==='package_overage'?$due:0,$bookingId]);releaseBookingSlots($pdo,$bookingId);
        $outcome=$mode==='waive'?'تمت تسوية الوقت الإضافي دون رسوم':($excess?'تمت تسوية الوقت الإضافي وإضافته إلى حساب الخدمة':'اكتملت الجلسة ضمن الرصيد المتاح');appNotification($pdo,(int)$user['organization_id'],(int)$booking['client_id'],'client','session_completed','اكتملت جلسة التصوير',$outcome,'booking_sessions',(int)$session['id'],'session:'.$session['id'].':settlement','info');
        if($originalId)notifyPackagePaymentDue($pdo,(int)$user['organization_id'],(int)$booking['client_id'],$originalId,(string)$booking['client_name']);if($targetId)notifyPackagePaymentDue($pdo,(int)$user['organization_id'],(int)$booking['client_id'],$targetId,(string)$booking['client_name']);
        $response=['booking_id'=>$bookingId,'session_id'=>(int)$session['id'],'settlement_id'=>$settlementId,'status'=>'completed','actual_minutes'=>(int)$actual,'covered_minutes'=>$covered,'excess_minutes'=>$excess,'billable_minutes'=>$billable,'waived_minutes'=>$waived,'settlement_mode'=>$mode,'target_package_id'=>$targetId,'invoice_id'=>$invoiceId,'project_id'=>$projectId,'payment_id'=>$paymentId,'amount_due'=>$due,'amount_paid'=>$paid,'billing_unit'=>$unit];$pdo->prepare('UPDATE session_settlements SET response_json=? WHERE id=?')->execute([json_encode($response,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$settlementId]);audit($pdo,$user,'session_settle_and_complete','booking_sessions',(int)$session['id'],$session,$response+['client_id'=>(int)$booking['client_id']]);$pdo->commit();return $response;
    }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
}
